### ISSUE TITLE
Environmental dependence

### ISSUE THREAD

**Issue by liuzhimindluter** [apache/incubator-linkis#101]
Hive's permission control is implemented based on sentry and ranger. The library where the permission table is located and the name of the permission table are inconsistent.
hive的权限控制有基于sentry去实现的，有基于ranger去实现的，权限表所在库以及权限表名是不一致的。
I would like to consult. The currently released version uses hive's own permissions. Which parameters need to be controlled?
我想咨询一下，我们目前发布的版本使用的是hive自带权限，这个需要控制那些参数？

**Comment by chaogefeng** [comment]
@liuzhimindluter linkis没有参与管理hive底层的权限控制哈
