### ISSUE TITLE
spark subtask进度条bug

### ISSUE THREAD

**Issue by fushuo159** [apache/incubator-linkis#1018]
linkis版本是1.0.1
在跑spark 任务时，会出现总的progress到1 但是subtask会保留在上一次的进度状态 会出现如下图的状态
![image](https://user-images.githubusercontent.com/54495048/134793337-dccd2e20-caeb-4685-8ee5-ab08d6cc93c2.png)
 
debug时看到engine已经将信息sendToEntrance，目前我的解决办法是 注释掉了linkis-entrance模块的EntranceExecutionJob.getProgressInfo的部分代码，问题得到解决，但不清楚会不会带来其他问题
![image](https://user-images.githubusercontent.com/54495048/134793432-ea052503-9695-4af6-9c98-b48a4551490b.png)

**Comment by peacewong** [comment]
Hello, this may be caused by not pushing all the progress information to the front end
