### ISSUE TITLE
维护部署太过复杂了

### ISSUE THREAD

**Issue by melin** [apache/incubator-linkis#1021]
底层技术架构用微服务，需要部署的进程太多，导致部署维护成本很大，大数据平台内部系统，一般内部用的人很少，需要认真考虑是否真的需要微服务，拆分粒度太细。再加上前后端分离部署，更加难维护，可以前后端分离开发，但最好合并部署。建议提供一个zip部署包，解压即可运行。
随便一个项目引入微服务，更像是玩技术...
![image](https://user-images.githubusercontent.com/1145830/135207907-cbe9fbf5-966c-4934-a26b-b1ed57e68056.png)

**Comment by tiger0526** [comment]
这本来就是给技术人员玩的，需要相当的功底才行。。。

**Comment by melin** [comment]
技术为业务服务才有价值，如果只是玩技术，价值会打折扣。Links
这套东西，一般大厂很少使用，都会自己做，一般小公司可能会用，对小公司可维护性是技术架构优先要考虑的。

tiger0526 ***@***.***> 于2021年9月30日周四 下午2:42写道：

**Comment by melin** [comment]
很多公司搞大数据的人，基本能力也就会写一下etl任务，太复杂了，难为他们了。

melin li ***@***.***> 于2021年9月30日周四 下午3:16写道：

**Comment by jacktao007** [comment]
dss1.0正式版 单容器all-in-one体验版0.0.3 ，欢迎体验!
链接: https://pan.baidu.com/s/1XmbThn9ofMGfIPtz1WlkTg 提取码: 6nc6 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by wushengyeyouya** [comment]
We planned to simplify the architecture of Linkis, and will provide the standalone mode, which will remove the micro-services dependencies, so all modules of Linkis can start in one JVM process as much as possible to improve the deployment trial experience.

However, it must be explained that this is a complex process that must take lots of time to complete. Linkis is a quite young **Apache incubator** project, which requires more community partners to participate together to jointly optimize the deployment, and enhance some core features such as orchestration, etc. 

Welcome more partners in the community to join in and build the world's leading computation middleware together.

**Comment by jacktao007** [comment]
> > dss1.0正式版 单容器all-in-one体验版0.0.3 ，欢迎体验! 链接: https://pan.baidu.com/s/1XmbThn9ofMGfIPtz1WlkTg 提取码: 6nc6 复制这段内容后打开百度网盘手机App，操作更方便哦
> 
> 我用了你的镜像，但是发现有一些问题，我这边会一直跳出后台接口异常，请联系开发，我大概看了一下应该是数据没有写进去，但是我不知道源数据应该怎么弄 ![image](https://user-images.githubusercontent.com/26518173/136704305-e1a265f4-8c85-43c9-975b-eda782dcbda8.png)

您好 请使用20303 端口看一下eureka中的服务是否启动正常，可能由于机器性能问题 导致有一部分启动异常，尝试docker exec -it dss bash 进入容器进行调试排查，比如查看日志等操作，查看启动脚本 是否存在未启动情况

**Comment by momomobinx** [comment]
> dss1.0正式版 单容器all-in-one体验版0.0.3 ，欢迎体验! 链接: https://pan.baidu.com/s/1XmbThn9ofMGfIPtz1WlkTg 提取码: 6nc6 复制这段内容后打开百度网盘手机App，操作更方便哦

现在这个连接无了
