### ISSUE TITLE
Linkis1.0.2 资源不足，请重试: errCode: 11012

### ISSUE THREAD

**Issue by CCweixiao** [apache/incubator-linkis#1056]
资源明明够用，sparkengine设置的提交参数也很小，通过Scripts提交依旧报资源不足的错误
![企业微信截图_8fa618d7-37dd-4069-ba27-474b477e627e](https://user-images.githubusercontent.com/27730211/139611591-04670918-1e4c-46ec-ae2f-a603bd1c0cf8.png)

![企业微信截图_16226ff9-23f7-4ee7-a7d6-19d4106d75da](https://user-images.githubusercontent.com/27730211/139611555-dc106fa8-de19-45fd-9a85-b75fc0b84966.png)

job运行报错
![企业微信截图_a5850ef6-bf32-40d7-a3f9-95a41ca0d709](https://user-images.githubusercontent.com/27730211/139611605-5fa49ee2-1359-4176-95fa-9f622b9dfed3.png)

linkis-manager错误日志
![企业微信截图_88549b7b-ce60-4ad2-ac43-3830bad3cd42](https://user-images.githubusercontent.com/27730211/139611615-fe601541-6e86-4009-9b04-29446bcb620e.png)

**Comment by mengfanzhen** [comment]
请问这个问题是否已经解决
