### ISSUE TITLE
How to integrate with kerberized hadoop cluster

### ISSUE THREAD

**Issue by moranrr** [apache/incubator-linkis#1076]
文档中没有找到如何与kerberos的集群集成的章节。
1. kerberized集群中spark如何与linkis集成？
2. kerberized集群中使用ladp认证的Hive如何与linkis集成？
3. linkis文档中没有“用户管理“章节
`
 .setAuthTokenKey("${username}").setAuthTokenValue("${password}")))  //Authentication key, generally the user name; authentication value, generally the password corresponding to the user name
`
不知道上面代码中的username和password是如何在linkis中添加的，这里的用户和kerberos中的用户是不是关系？

The document did not find a chapter on how to integrate with the kerberos cluster.
1. How to integrate spark with linkis in kerberized cluster?
2. How to integrate Hive with LADP authentication in kerberized cluster with linkis?
3. There is no "User Management" chapter in the linkis document
`
 .setAuthTokenKey("${username}").setAuthTokenValue("${password}")))  //Authentication key, generally the user name; authentication value, generally the password corresponding to the user name
`

I don't know how the username and password in the above code are added in linkis. Is there any relationship between linkis users and kerberos users?

**Comment by saLeox** [comment]
Hi, for how to integrate with kerberos, you can refer to
https://github.com/apache/incubator-linkis/wiki/Q&A-问题总结#15.Linkis如何支持kerberos
If you want to know how to achieve proxyuser in kerberized cluster, pls wait for this pr in 1.0.3
https://github.com/apache/incubator-linkis/pull/1027
