### ISSUE TITLE
关于linkis-spring-cloud-gateway 服务的空指针以及gatewayProperties无法赋值问题

### ISSUE THREAD

**Issue by dongjycode** [apache/incubator-linkis#1086]
**问题描述**
  **问题1**
按照文档来操作调试，网关的一切配置准备就绪后，启动网关服务时，SpringCloudGatewayConfiguration.scala 抛出空指针问题，问题截图如下：
![image](https://user-images.githubusercontent.com/91414395/141446523-361340e7-259c-44e5-bef9-a73877134388.png)
另外查看源码时还有一个疑问，如下图
![image](https://user-images.githubusercontent.com/91414395/141446994-ee5f5ef6-a27f-45cf-9ad5-d148571a1ea5.png)
gatewayParsers、gatewayRouters变量是如何赋值的，我的理解是初始时为null,没有找到赋值的地方，故出现以上空指针问题，望解答，谢谢！
**问题2**
如下图：gatewayProperties无法取到yml配置文件的赋值（增加依赖可解决：javax.el-api、javax.el）
![image](https://user-images.githubusercontent.com/91414395/141447872-5dd817ab-6fd7-4e79-9104-0b73300928d8.png)

**本地启动配置如下**
 资源文件列表：
![image](https://user-images.githubusercontent.com/91414395/141447238-0db717db-b95e-4712-9335-03d93307cefc.png)
application.yml:
![image](https://user-images.githubusercontent.com/91414395/141447339-4e117133-40b6-43a4-b681-3ee70d8c6237.png)
linkis.properties:
![image](https://user-images.githubusercontent.com/91414395/141447401-000364c3-adcd-40d5-b110-575ce36d7e2f.png)
linkis-mg-gateway.properties:
![image](https://user-images.githubusercontent.com/91414395/141447485-64a549a7-cb39-44d6-8acf-49b51a6fa965.png)

**Comment by mengfanzhen** [comment]
请问gatewayRouters 为空的问题是怎么解决的？直接判空？

**Comment by dongjycode** [comment]
@mengfanzhen 是的暂时判空，否则服务启动不起来，暂时不知道如何赋值的，可能后续会出现额外的问题

**Comment by dongjycode** [comment]
@peacewong 感谢标记，问题本人已经解决，解决方案如图
![image](https://user-images.githubusercontent.com/91414395/147477315-66c9dcd7-d867-47e9-ad33-b9d5dfb20be1.png)
需要把linkis-gateway-server-support模块加入到linkis-spring-cloud-gateway模块启动classpath中（不是加入依赖，会报循环依赖）即可启动linkis-spring-cloud-gateway服务，且不会报空指针

**Comment by peacewong** [comment]
Thank you, because the gateway module needs to be debugged is linkis-gateway-server-support

**Comment by dongjycode** [comment]
The default behavior is  **DefaultLabelGatewayRouter** by **GatewayRouterConfiguration**
