### ISSUE TITLE
spark.driver.memory 取值范围 1-15 但是正则判断是 3-15

### ISSUE THREAD

**Issue by momomobinx** [apache/incubator-linkis#1096]
![2ea4054b64ddd6eebeb002d8c58ad1c](https://user-images.githubusercontent.com/21970770/141983437-5f0f57cb-7470-40b3-a7ea-7513ba7cb425.png)

**Comment by peacewong** [comment]
Hello, please follow the issue template

**Comment by legendtkl** [comment]
@peacewong  would you help have a look the fix PR https://github.com/apache/incubator-linkis/pull/1111
