### ISSUE TITLE
[Bug]Cannot be processed when the submitted task script is empty code

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis#1143]
**Describe the bug**
Cannot be processed when the submitted task script is empty code.
This scenario should return a prompt message that the script cannot be empty and prohibit submission or end the task directly.
**Expected behavior**
When this method(org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor#toExecuteTask ) is executed, it should be judged whether the executed code is empty.

**Comment by legendtkl** [comment]
hi, @peacewong , would you help review this ?

thanks. kelu.
