### ISSUE TITLE
[Bug]Shell engine  will not append shell-stdout into persisted-log

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis#1157]
**Describe the bug**
Shell engine will not append shell-stdout to the persistent log when executing

**Expected behavior**
When the Shell engine is executed, shell-stdout needs to be appended to the persistent log

**Screenshots**

![企业微信截图_16387793782508](https://user-images.githubusercontent.com/7869972/144819108-d32a1434-7921-4d56-87fa-5ff1e606ca03.png)

**Comment by legendtkl** [comment]
Hi, @casionone @peacewong, would you help review this pr?

Thanks, kelu.

**Comment by peacewong** [comment]
> Hi, @casionone @peacewong, would you help review this pr?
> 
> Thanks, kelu.

ok thanks
