### ISSUE TITLE
[Bug] Add JAVA_HOME for ProcessEngineConnLaunch

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis#1159]
**Describe the bug**
ProcessEngineConnLaunch#initializeEnv should add JAVA_HOME 

**Screenshots**
![image](https://user-images.githubusercontent.com/7869972/144822489-bfa645af-062e-4a48-957d-c91cb862225f.png)

**Comment by legendtkl** [comment]
https://github.com/apache/incubator-linkis/pull/1167   cc @casionone
