### ISSUE TITLE
[BUG]DefaultGatewayRouter init NPE

### ISSUE THREAD

**Issue by peacewong** [apache/incubator-linkis#1235]
**Describe the bug**
DefaultGatewayRouter has the possibility of reporting a NPE
```
[org.springframework.cloud.gateway.filter.GlobalFilter]:  Factory method 'authorizationFilter' threw exception; nested exception is java.lang.NullPointerException
```
![image](https://user-images.githubusercontent.com/11496700/147340486-179140cf-a37f-4faa-aac3-4a3c8cef1a12.png)

**Expected behavior**
It is recommended to make a null judgment
```
class DefaultGatewayRouter(var gatewayRouters: Array[GatewayRouter]) extends AbstractGatewayRouter{

  gatewayRouters = gatewayRouters.sortWith((left, right) => {
    left.order() < right.order()
  })
```

**Comment by dongjycode** [comment]
本人已解决，请参考[https://github.com/apache/incubator-linkis/issues/1086](url)

**Comment by peacewong** [comment]
> 本人已解决，请参考 #1086

Thank you, but NPE still needs to be checked
