### ISSUE TITLE
[Bug] The percentage of resource usage is displayed abnormally

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis#1277]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

web

### What happened + What you expected to happen

The percentage of resource usage is displayed abnormally

![image](https://user-images.githubusercontent.com/7869972/148379866-f9235970-a470-4cce-854b-4ffbe6c9dfbb.png)

### Relevent platform

none

### Reproduction script

none

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by aleneZeng** [comment]
hi, I am willing to submit a PR for this problem.
