### ISSUE TITLE
[Feature] It is recommended that Linkis remove the HDFS strong dependency and can all use the local file system

### ISSUE THREAD

**Issue by peacewong** [apache/incubator-linkis#1312]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

Now Linkis has a strong dependence on HDFS. If there is no HDFS, it cannot
be used. It is recommended that the service can run normally without
 HDFS.

### Description

Remove the strong dependence of modules such as [PublicService][Entrance][EC] on HDFS, and support the use of the local file system.

### Anything else

Welcome to email discussion：https://lists.apache.org/thread/1rbq7gk9jrj8h357kn5hnbl9j9w3wwyp

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Adamyuanyuan** [comment]
+1

peacewong ***@***.***> 于2022年1月18日周二 17:33写道：

**Comment by casionone** [comment]
I think when distributed deployment, the availability of the local file system needs to be considered
