### ISSUE TITLE
[Bug] 在dss切换用户跑shell脚本，报错：user/linkis2/result_set无权限访问，请申请开通数据表权限，请联系您的数据管理人员(Switch user running shell script in DSS, error "user/linkis2/result_set no permission to access, please apply for the data table permission, please contact your data manager")

### ISSUE THREAD

**Issue by aleneZeng** [apache/incubator-linkis#1314]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-entrance

### What happened + What you expected to happen

1，linkis-cg-entrance.properties里配置如下
wds.linkis.resultSet.store.path=hdfs:///user/linkis2/result_set，实际上hdfs上只创建了/user/linkis2(rwxrwxr_x),然后启动linkis+dss，在Scripts以a账号运行shell成功，再切换成b账号运行shell，出现标题的错误
2，b账号也应该能够成功运行
3，发现hdfs上以a账号自动创建了/user/linkis2/result_set(rwxr_xr_x)路径，而b账号在这个路径上没有写权限。如果将/user/linkis2/result_set改为rwxrwxr_x则b账号运行shell脚本成功

### Relevent platform

dss1.0.1
Linkis-1.0.3-rc1
CDH-6.3.2
Centos-7.4

### Reproduction script

Shell脚本很简单：
echo “hello”

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Hi,it is recommended to use English translation. Are you interested in fixing this issue?

**Comment by aleneZeng** [comment]
yes, I am interested in fixing this issue
