### ISSUE TITLE
[Bug]Sometimes Engine Startup Fail,The Locked Resource Not Release

### ISSUE THREAD

**Issue by xiaojie19852006** [apache/incubator-linkis#1316]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-manager

### What happened + What you expected to happen

The engine startup failure,But the engine resource keep in the database,After a while engine startup not enough resource。
I check the table linkis_cg_manager_service_instance as follow,

| id | instance                             | name                        | owner | mark    | update_time         | create_time         | updator | creator |
| ---| ------------------------------------ | ----------------------------| ------| --------| ------------------- |-------------------- |-------- | ------- |
| 42 | 10.30.106.171:9102                   | linkis-cg-engineconnmanager | root  | process | 2022-01-19 13:43:57 | 2022-01-19 13:43:57 | root    | root    |
| 43 | b13f9a97-dea6-4cdd-84e1-a4436db8bc9a | linkis-cg-engineconn        | NULL  | NULL    | 2022-01-19 13:46:18 | 2022-01-19 13:46:18 | NULL    | NULL    |
| 44 | 3c041a44-95c7-4452-b342-b7c70f388647 | linkis-cg-engineconn        | NULL  | NULL    | 2022-01-19 13:47:18 | 2022-01-19 13:47:18 | NULL    | NULL    |
| 45 | 10.30.106.171:36307                  | linkis-cg-engineconn        | hive  | process | 2022-01-19 13:48:31 | 2022-01-19 13:48:28 | ||

  
  

### Relevent platform

The Linkis Version Is dev-1.0.3

### Reproduction script

Test 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by xiaojie19852006** [comment]
Why
Class:DefaultEngineCreateService Function:createEngine 
val engineNode = getEMService().createEngine(engineBuildRequest, emNode)  not to try catch the error?

**Comment by xiaojie19852006** [comment]
How to deal with the linkis manager cash when create engine,the lock resource have keep in the database?

**Comment by casionone** [comment]
> How to deal with the linkis manager cash when create engine,the lock resource have keep in the database?

Some exceptions can be catched and resources can be released during exception handling. Some scenarios may need to be considered, such as the engine process being forced to kill, or the service not starting and stopping gracefully. Personally, I think it may be an option for scheduled tasks to clean up abnormal resources.

**Comment by xiaojie19852006** [comment]
Can I use NodeHeartbeatMonitor to clean the resource?

**Comment by peacewong** [comment]
> Can I use NodeHeartbeatMonitor to clean the resource?
Linkis 1.0.3 version has been cleaned up in NodeHeartbeatMonitor,this scene should be covered.
