### ISSUE TITLE
[Bug] k8s,linkis_ps_instance_info keep the previous instance

### ISSUE THREAD

**Issue by xiaojie19852006** [apache/incubator-linkis#1317]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-manager

### What happened + What you expected to happen

The table linkis_ps_instance_info keep the previous instance all the time ,because the ip not fixed

### Relevent platform

linkis verison 1.0.3

### Reproduction script

k8s test enviroment

### Anything else

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by xiaojie19852006** [comment]
Can I use  NodeHeartbeatMonitor to clear the infomation ?

**Comment by peacewong** [comment]
> Can I use NodeHeartbeatMonitor to clear the infomation ?

Hello, no, it is recommended to add a monitor to the ps module to do this
