### ISSUE TITLE
[Feature] Modify the email notification policy of the git repository

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis#1318]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

The current email notification policy [1] for changes to the git code repository of the linkis project (incubator-linkis/incubator-linkis-website) is as follows:

```
commits: commits@linkis.apache.org
issues: dev@linkis.apache.org
pullrequests: dev@linkis.apache.org
```

This results in more and more messy emails in the dev mailing list, and important emails for other discussions cannot be viewed well.
It is recommended to modify the asf.yaml file configuration [2], and bind the notification emails of issues/pr and other changes to the commits email. Most projects do the same way  (such as spark/hadoop)

The configuration should be as follows:
```
commits: commits@linkis.apache.org
issues: commits@linkis.apache.org
pullrequests: commits@linkis.apache.org
```
[1] https://gitbox.apache.org/schemes.cgi?incubator-linkis-website
[2] https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-ImplementedFeatures

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
I agree with this modification
