### ISSUE TITLE
[Bug] Cannot find an instance in the routing chain of serviceId [linkis-cg-entrance]

### ISSUE THREAD

**Issue by iture123** [apache/incubator-linkis#1321]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-service-gateway

### What happened + What you expected to happen

Request URL: http://localhost:8080/api/rest_j/v1/entrance/execute
Requat param:
`{"executeApplicationName":"spark","executionCode":"select * from test::dual","runType":"sql","params":{"variable":{},"configuration":{}},"source":{"scriptPath":"file:///tmp/linkis/hadoop/fhive/fsql/a1.sql"}}`
The response is:
`{"method":"/api/rest_j/v1/entrance/execute","status":1,"message":"GatewayErrorException: errCode: 11012 ,desc: Cannot find an instance in the routing chain of serviceId [linkis-cg-entrance], please retry ,ip: hadoop-PC ,port: 9001 ,serviceKind: linkis-mg-gateway","data":{"data":"{\"executeApplicationName\":\"spark\",\"executionCode\":\"select * from test::dual\",\"runType\":\"sql\",\"params\":{\"variable\":{},\"configuration\":{}},\"source\":{\"scriptPath\":\"file:///tmp/linkis/hadoop/fhive/fsql/a1.sql\"}}"}}`
The linkis-cg-entrance service lis live.But i see thre request param executeApplicationName=spark,and I do not config Spark in local enviroment,Only hive is available.
![1642952238(1)](https://user-images.githubusercontent.com/12154864/150686271-d86319e8-1c12-43cc-97db-5084611f021a.jpg)
![1642952264(1)](https://user-images.githubusercontent.com/12154864/150686272-344702d3-a22a-4e41-b58e-6081208de3a9.png)

### Relevent platform

system:deepin 20.4
linkis:dev-1.0.3
dss:dev-1.0.1
jdk:1.8.0_301

### Reproduction script

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
This should be caused by instancelabel lookup service error, will you fix this issue?

**Comment by windwhisper-i** [comment]
+1
