### ISSUE TITLE
[BUG]实现新引擎，后台管理页面引擎名称和图标一片空白（Implement a new engine, the name and icon of the background management page engine are blank）

### ISSUE THREAD

**Issue by CCweixiao** [apache/incubator-linkis#1326]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

web

### What happened + What you expected to happen

linkis1.0.3 实现了新引擎，然后引擎正常启动后，在引擎管理页面，引擎图标和名称一片空白

linkis1.0.3 implements a new engine, and after the engine starts normally, the engine icon and name are blank on the engine management page

![image](https://user-images.githubusercontent.com/27730211/151176574-48d81c32-8229-4575-909f-2e449fee763b.png)

### Relevent platform

谷歌浏览器

Google Chrome

### Reproduction script

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by casionone** [comment]
What is the type of engine you have newly implemented?
It may be that the front-end display support of the new engine is not friendly enough

**Comment by CCweixiao** [comment]
> What is the type of engine you have newly implemented? It may be that the front-end display support of the new engine is not friendly enough

The new engine is presto

**Comment by yingeo** [comment]
#1326



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weixiao ***@***.***&gt;
发送时间: 2022年2月17日 21:54
收件人: apache/incubator-linkis ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [apache/incubator-linkis] [BUG]实现新引擎，后台管理页面引擎名称和图标一片空白（Implement a new engine, the name and icon of the background management page engine are blank） (Issue #1326)
