### ISSUE TITLE
[Feature] Optimize the state storage of Statement in the JDBC engine to support richer functions and solve some potential concurrency problems

### ISSUE THREAD

**Issue by CCweixiao** [apache/incubator-linkis#1327]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

优化JDBC引擎中，statement对象的状态存储，以支持更加丰富的功能，例如，利用statement来cancel一些在进行的SQL查询，以及解决潜在的一些并发问题。

In the JDBC engine, the state storage of the statement object is optimized to support richer functions, for example, using the statement to cancel some ongoing SQL queries and solve some potential concurrency problems.

### Description

优化JDBC引擎中，statement对象的状态存储，以支持更加丰富的功能，例如，利用statement来cancel一些在进行的SQL查询，以及解决潜在的一些并发问题。

In the JDBC engine, the state storage of the statement object is optimized to support richer functions, for example, using the statement to cancel some ongoing SQL queries and solve some potential concurrency problems.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Thank you, this is a concurrency issue and needs to be fixed
