### ISSUE TITLE
[Bug] SparkSQL can not exec in Scriptis

### ISSUE THREAD

**Issue by shenbinglife** [apache/incubator-linkis#1328]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-entrance, linkis-cg-manager

### What happened + What you expected to happen

Create SparkSQL In Scriptis run failed ， return error log

2022-01-27 09:58:51.058 ERROR Task is Failed,errorMsg: errCode: 12003 ,desc: hostname-xxxxx:9101_8 Failed  to async get EngineNode FeignException.NotFound: status 404 reading RPCReceiveRemote#receiveAndReply(Message) ,ip: hostname-xxxxx: ,port: 9104 ,serviceKind: linkis-cg-entrance

linkis-cg-linkismanager.log :  
![image](https://user-images.githubusercontent.com/16119667/151282144-10c47a90-4788-4b58-80e8-998381c5b8e0.png)

### Relevent platform

Linkis1.0.2  NOT with CDH

### Reproduction script

SparkSQL: show tables

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by casionone** [comment]
Maybe you can find some detial log info in  engine workdir(ENGINECONN_ROOT_PATH/youruser/workDir, ENGINECONN_ROOT_PATH is configured in linkis-env.sh)

**Comment by peacewong** [comment]
This is similar to question [Q18](https://docs.qq.com/doc/DSGZhdnpMV3lTUUxq)
