### ISSUE TITLE
[Bug] linkis uses a version of jetty that has reported security vulnerabilities

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-linkis#1349]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### What happened + What you expected to happen

https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server shows which versions have issues

If you don't want to use latest jetty release (v11.x.x), you could use the latest v9.x.x release (also CVE free)

### Relevent platform

all

### Reproduction script

n/a

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Thank you, there are Vulnerabilities in the lower version of jetty, it is necessary to upgrade
