### ISSUE TITLE
[Feature] Reduce the maximum idle time of EngineConn resources

### ISSUE THREAD

**Issue by husofskyzy** [apache/incubator-linkis#1376]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

The maximum idle time of engine resources is relatively long. In the multi-user scenario, the competition pressure of engine resources is large and the waiting time is long.

### Description

Reduce the maximum idle time of engine resources

### solutions

Reduce the maximum idle time of engine resources from 1hour to 0.5hour.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Thank you, 0.5h is more reasonable
