### ISSUE TITLE
[Bug]  异常提示“queryDbsWithTables”，后台搜不到这些关键字(Error message "queryDbsWithTables", background search can not find these keywords)

### ISSUE THREAD

**Issue by feicuimeipo** [apache/incubator-linkis#1398]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

web

### What happened + What you expected to happen

[Bug]  异常提示“queryDbsWithTables”，后台搜不到这些关键字。
我想可能只是在前端的界面显示，并没有写入到log中

### Relevent platform

[Bug]  异常提示“queryDbsWithTables”，后台搜不到这些关键字.

### Reproduction script

进入scripts，再左侧菜单，第三项目的主要内容，如果不出现在， 再点“管理”

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by stdnt-xiao** [comment]
1.Find error at logs/linkis-ps-publicservice.log.
![image](https://user-images.githubusercontent.com/20313983/236631050-a8575ab2-d01f-4874-bac3-bc2cae6ebde4.png)


2.Resolvent
vim conf/linkis-ps-publicservice.properties
```
##hive meta
hive.meta.url=jdbc:mysql://192.168.1.34:3306/hive?useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
```
sbin/linkis-daemon.sh restart cg-engineconnmanager


3.Analysis
vim deploy-config/db.sh
```
### Provide the DB information of Hive metadata database.
**### Attention! If there are special characters like "&", they need to be enclosed in quotation marks.**
HIVE_META_URL="jdbc:mysql://ip:port/hive?useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true"
```
Note: 
You may need to transfer the processing. For example, the templates mode of ansible. 
```
HIVE_META_URL="jdbc:mysql://{{ hostvars[groups['mysql'][0]].ansible_ssh_host }}:{{ MYSQL_PORT }}/hive?useSSL=false\&characterEncoding=UTF-8\&allowMultiQueries=true\&useAffectedRows=true"
```
