### ISSUE TITLE
code style issues collect

### ISSUE THREAD

**Issue by legendtkl** [apache/incubator-linkis#1475]
This issue will give a summary of issues related about code styles or little bugs. This will help the new guys to be familiar with the PR workflow. Welcome to contribute!

code styles can be improved:
* typo in classes/methods/fields/comments
* redundant code, such as commented code, unused class/methods/fields
* duplicated code snippet, extract the duplicated code for reusing
* refactor, maybe some best practice

**Comment by linbin66** [comment]
you can assign it to me.
