### ISSUE TITLE
[Bug] [Web]Requested datasource http api address is incorrect

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis#1604]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

web

### What happened + What you expected to happen

The interface of the http request of the data source management page does not match the back-end interface
data_source -> data-source-manager
![企业微信截图_16462937164890](https://user-images.githubusercontent.com/7869972/156685905-e6536507-5707-4f21-bacb-8dcefa7c917f.png)

----------
数据源管理页面http请求的接口和后端接口未匹配上 
data_source -> data-source-manager

### Relevent platform

none

### Reproduction script

none

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by det101** [comment]
fix in #1591
