### ISSUE TITLE
Add junit5 test code for module [linkis-hadoop-common]

### ISSUE THREAD

**Issue by husofskyzy** [apache/incubator-linkis#1647]
## Add junit5 test code for module [linkis-hadoop-common]
- Module: linkis-hadoop-common
- Location:linkis-commons/linkis-hadoop-common
- Task status:&cross;(unfinished)/ &check;(finished) 
- Test code guide:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- Test code example: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test
-------
- 模块名: linkis-hadoop-common
- 代码位置:linkis-commons/linkis-hadoop-common
- 任务状态:&cross;(unfinished)/ &check;(finished) 
- 单测编写指引:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- 参考样例: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test

| Task status| Class | Type| Level of Difficulty | Note|
| :------ | :------ | :------: | :------: | :------: |
| &cross; | org.apache.linkis.hadoop.common.utils.KerberosUtils | Utils | easy |  |
| &cross; | org.apache.linkis.hadoop.common.conf.HadoopConf | Conf | easy |  |
| &cross; | org.apache.linkis.hadoop.common.utils.HDFSUtils | Utils | easy |  |

**Comment by zzs52** [comment]
can i try?

**Comment by ruY9527** [comment]
Commit to dev-1.3.1 branch
