### ISSUE TITLE
Add junit5 test code for module [linkis-httpclient]

### ISSUE THREAD

**Issue by husofskyzy** [apache/incubator-linkis#1648]
## Add junit5 test code for module [linkis-httpclient]
- Module: linkis-httpclient
- Location:linkis-commons/linkis-httpclient
- Task status:&cross;(unfinished)/ &check;(finished) 
- Test code guide:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- Test code example: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test
-------
- 模块名: linkis-httpclient
- 代码位置:linkis-commons/linkis-httpclient
- 任务状态:&cross;(unfinished)/ &check;(finished) 
- 单测编写指引:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- 参考样例: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test

| Task status| Class | Type| Level of Difficulty | Note|
| :------ | :------ | :------: | :------: | :------: |
| &cross; | org.apache.linkis.httpclient.authentication.AbstractAuthenticationStrategy | Auth | normal |  |
| &cross; | org.apache.linkis.httpclient.discovery.AbstractDiscovery | discovery | normal |  |
| &cross; | org.apache.linkis.httpclient.exception.* | Exception | easy |  |
| &cross; | org.apache.linkis.httpclient.loadbalancer.AbstractLoadBalancer | balancer | normal |  |
| &cross; | org.apache.linkis.httpclient.loadbalancer.DefaultLoadbalancerStrategy | balancer | normal |  |
| &cross; | org.apache.linkis.httpclient.request.GetAction | request | easy |  |
| &cross; | org.apache.linkis.httpclient.request.POSTAction | request | easy |  |
| &cross; | org.apache.linkis.httpclient.request.UploadAction | request | easy |  |
| &cross; | org.apache.linkis.httpclient.response.HashMapHttpResult | request | easy |  |
| &cross; | org.apache.linkis.httpclient.response.impl.DefaultHttpResult | request | easy |  |
| &cross; | org.apache.linkis.httpclient.AbstractHttpClient | client | easy |  |
| &cross; | org.apache.linkis.httpclient.GenericHttpClient | client | easy |  |

**Comment by complone** [comment]
I want to try this task

**Comment by ruY9527** [comment]
Commit to dev-1.3.1 branch
