### ISSUE TITLE
Add junit5 test code for module [linkis-message-scheduler]

### ISSUE THREAD

**Issue by husofskyzy** [apache/incubator-linkis#1657]
## Add junit5 test code for module [linkis-message-scheduler]
- Module: linkis-message-scheduler
- Location:linkis-commons/linkis-message-scheduler
- Task status:&cross;(unfinished)/ &check;(finished) 
- Test code guide:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- Test code example: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test
-------
- 模块名: linkis-message-scheduler
- 代码位置:linkis-commons/linkis-message-scheduler
- 任务状态:&cross;(unfinished)/ &check;(finished) 
- 单测编写指引:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- 参考样例: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test

| Task status| Class | Type| Level of Difficulty | Note|
| :------ | :------ | :------: | :------: | :------: |
| &cross; | org.apache.linkis.message.builder.DefaultMessageJob | job | normal |  |
| &cross; | org.apache.linkis.message.builder.DefaultMessageJobBuilder | job | normal |  |
| &cross; | org.apache.linkis.message.builder.DefaultServiceMethodContext | Context | normal |  |
| &cross; | org.apache.linkis.message.builder.MessageJobListener | Listener | normal |  |
| &cross; | org.apache.linkis.message.builder.MessageJobTimeoutPolicy | Enum | easy |  |
| &cross; | org.apache.linkis.message.conf.MessageSchedulerConf | Conf | easy |  |
| &cross; | org.apache.linkis.message.context.MSContextInstance | Conf | easy |  |
| &cross; | org.apache.linkis.message.exception.* | Exception | easy |  |
| &cross; | org.apache.linkis.message.parser.DefaultImplicitParser | Parser | easy |  |
| &cross; | org.apache.linkis.message.publisher.AbstractMessagePublisher | Publisher | normal |  |
| &cross; | org.apache.linkis.message.registry.* | Registry | normal |  |
| &cross; | org.apache.linkis.message.scheduler.MessageExecutorExecutionManager | Executor | easy |  |
| &cross; | org.apache.linkis.message.scheduler.MethodExecuteWrapper | Executor | easy |  |
| &cross; | org.apache.linkis.message.scheduler.DefaultMessageScheduler | Scheduler | easy |  |
| &cross; | org.apache.linkis.message.scheduler.DefaultMessageExecutor | Executor | normal |  |
| &cross; | org.apache.linkis.message.scheduler.AbstractMessageExecutor | Executor | normal |  |
| &cross; | org.apache.linkis.message.utils.MessageUtils | utils | normal |  |
| &cross; | org.apache.linkis.rpc.MessageRPCSpringConfiguration | Rpc | normal |  |
| &cross; | org.apache.linkis.rpc.MessageRPCReceiveRestful | Rpc | normal |  |
| &cross; | org.apache.linkis.rpc.MessageRPCConsumer | Rpc | normal |  |
| &cross; | org.apache.linkis.rpc.MessageReceiverChooser | Receiver | normal |  |
| &cross; | org.apache.linkis.rpc.MessageReceiver | Receiver | normal |  |
| &cross; | org.apache.linkis.rpc.MessageErrorConstants | Constants | easy|  |
| &cross; | org.apache.linkis.rpc.MessageConverter | Converter | normal |  |

**Comment by QuintinTao** [comment]
Hi! May I do this？

**Comment by QuintinTao** [comment]
which brach should I use? I can't find org.apache.linkis.message.builder.MessageJobTimeoutPolicy in the dev-1.2.0

**Comment by peacewong** [comment]
> which brach should I use? I can't find org.apache.linkis.message.builder.MessageJobTimeoutPolicy in the dev-1.2.0

dev-1.2.0

**Comment by ruY9527** [comment]
Module has been migrated
