### ISSUE TITLE
Add junit5 test code for module [linkis-module]

### ISSUE THREAD

**Issue by husofskyzy** [apache/incubator-linkis#1658]
## Add junit5 test code for module [linkis-module]
- Module: linkis-module
- Location:linkis-commons/linkis-module
- Task status:&cross;(unfinished)/ &check;(finished) 
- Test code guide:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- Test code example: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test
-------
- 模块名: linkis-module
- 代码位置:linkis-commons/linkis-module
- 任务状态:&cross;(unfinished)/ &check;(finished) 
- 单测编写指引:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- 参考样例: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test

| Task status| Class | Type| Level of Difficulty | Note|
| :------ | :------ | :------: | :------: | :------: |
| &cross; | org.apache.linkis.server.utils.AopTargetUtils | utils | normal |  |
| &cross; | org.apache.linkis.DataWorkCloudApplication | App | normal |  |
| &cross; | org.apache.linkis.LinkisBaseServerApp | App | normal |  |
| &cross; | org.apache.linkis.server.conf.DataWorkCloudCustomExcludeFilter | Filter | normal |  |
| &cross; | org.apache.linkis.server.conf.ModuleConfiguration | Conf | easy |  |
| &cross; | org.apache.linkis.server.conf.ServerConfiguration | Conf | easy |  |
| &cross; | org.apache.linkis.server.Exception.* | Exception | easy |  |
| &cross; | org.apache.linkis.server.restful.SpringRestfulCatchAOP | Aop | normal |  |
| &cross; | org.apache.linkis.server.security.SecurityFilter | Filter | normal |  |
| &cross; | org.apache.linkis.server.security.SSOUtils | Utils | normal |  |
| &cross; | org.apache.linkis.server.socket.ServerSocket | Server | normal |  |
| &cross; | org.apache.linkis.server.socket.ControllerServer | Server | normal |  |
| &cross; | org.apache.linkis.server.socket.controller.ServerListenerEventBus | Controller | normal |  |
| &cross; | org.apache.linkis.server.socket.controller.ServerEventService | Controller | normal |  |
| &cross; | org.apache.linkis.server.socket.controller.ServerEvent | Controller | normal |  |
| &cross; | org.apache.linkis.server.utils.LinkisMainHelper | Utils | normal |  |
| &cross; | org.apache.linkis.Message | Message | normal |  |
| &cross; | org.apache.linkis.BDPJettyServerHelper | Helper | normal |  |
| &cross; | org.apache.linkis.package | package | normal |  |

**Comment by ruY9527** [comment]
Commit to dev-1.3.1 branch
