### ISSUE TITLE
Add junit5 test code for module [linkis-mybatis]

### ISSUE THREAD

**Issue by husofskyzy** [apache/incubator-linkis#1659]
## Add junit5 test code for module [linkis-mybatis]
- Module: linkis-mybatis
- Location:linkis-commons/linkis-mybatis
- Task status:&cross;(unfinished)/ &check;(finished) 
- Test code guide:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- Test code example: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test
-------
- 模块名: linkis-mybatis
- 代码位置:linkis-commons/linkis-mybatis
- 任务状态:&cross;(unfinished)/ &check;(finished) 
- 单测编写指引:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- 参考样例: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test

| Task status| Class | Type| Level of Difficulty | Note|
| :------ | :------ | :------: | :------: | :------: |
| &cross; | org.apache.linkis.mybatis.conf.DataSourceConfig | Conf | easy |  |
| &cross; | org.apache.linkis.mybatis.MybatisConfigurationFactory | Conf | easy |  |
| &cross; | org.apache.linkis.mybatis.MyBatisMapperScannerConfig | Conf | easy |  |
| &cross; | org.apache.linkis.mybatis.MybatisConfiguration | Conf | easy |  |

**Comment by zzs52** [comment]
can i try?

**Comment by husofskyzy** [comment]
> can i try?
yes,just follow the guide and do it.

**Comment by ruY9527** [comment]
Commit to dev-1.3.1 branch
