### ISSUE TITLE
txt, csv, xslx failed to export to hive

### ISSUE THREAD

**Issue by jinquanzhuang** [apache/incubator-linkis#1738]
![image](https://user-images.githubusercontent.com/7869972/158819462-6ac90a46-6eb8-45a3-89d2-34c9ea6d0992.png)
Failed with: java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods$.parse$default$3()

**Comment by casionone** [comment]
The spark engine version and the spark environment version do not match, this exception may occur
