### ISSUE TITLE
The management console sets python_IDE to python3, and the python version printed on the scriptis page is still python2

### ISSUE THREAD

**Issue by jinquanzhuang** [apache/incubator-linkis#1745]
![image](https://user-images.githubusercontent.com/101614307/158799159-96d4bf82-7dbe-4213-87ac-11808ab629ba.png)
![image](https://user-images.githubusercontent.com/101614307/159011201-9c422531-75eb-4bce-a65e-b4dbba7113b6.png)

**Comment by peacewong** [comment]
Please provide the startup log of ec and the version of linkis
