### ISSUE TITLE
Guided table building, the interface reports an error when choosing to import

### ISSUE THREAD

**Issue by jinquanzhuang** [apache/incubator-linkis#1746]
![image](https://user-images.githubusercontent.com/101614307/158916140-58808775-3cd5-4f11-a050-c4217acfbbe2.png)
![image](https://user-images.githubusercontent.com/101614307/158916214-c890f26a-07e4-4d6a-bfd8-d2c8f11f3271.png)

**Comment by peacewong** [comment]
Thank you, this seems to be a DSS-web issue, please submit this issue to dss https://github.com/WeBankFinTech/DataSphereStudio
