### ISSUE TITLE
[Bug] Linkis 1.0.3 is not compatible with Hive 1.1.0 

### ISSUE THREAD

**Issue by LEOPROGRAM** [apache/incubator-linkis#1747]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-engineConnplugin

### What happened + What you expected to happen

Linkis 1.0.3 is not compatible with Hive 1.1.0. When I compile Linkis, it prompts that class is missing; 
![e31bc2fdce2c9dfd20082e6eb9b41d8](https://user-images.githubusercontent.com/11906632/158920093-d740ac42-d60a-46ed-adea-35ea840b05b7.jpg)

在编译linkis的时候，如果修改了hive的版本，使用1.1.0版本编译linkis会报如下错误。

### Relevent platform

Windows 7 64

### Reproduction script

<artifactId>linkis-engineplugin-hive</artifactId>

    <properties>
        <hive.version>1.1.1</hive.version>
    </properties>

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Thanks, this compatibility is necessary by

**Comment by CCweixiao** [comment]
> Thanks, this compatibility is necessary by

平哥 这个地方咋修改合适，我都是直接把报错这两项删除啦！
How to modify this place properly, I just delete the two errors reported!

**Comment by utopianet** [comment]
现在我遇到了相同的问题，CDH版本是5.16.1 hive版本1.1.0
