### ISSUE TITLE
[Bug] config.sh get mutiple ip

### ISSUE THREAD

**Issue by iture123** [apache/incubator-linkis#1761]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

web

### What happened + What you expected to happen

When there are multiple network cards, there is a problem with the IP address it obtains.
 I suggest letting users choose one.
![截图_选择区域_20220320113643](https://user-images.githubusercontent.com/12154864/159147042-5624d4b5-c191-4b47-a7f0-c7d221b6142e.png)

### Relevent platform

deepin  20.4

### Reproduction script

ip addr | awk '/^[0-9]+: / {}; /inet.*global/ {print gensub(/(.*)\/(.*)/, "\\1", "g", $2)}'

### Anything else

Linkis Component can not select "assembly-combined-package" in "Issue: Bug report" page

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by legendtkl** [comment]
Hi, @iture123 , would you help submit a PR for this?

Thanks.
