### ISSUE TITLE
[Bug] JDBC engine execution 21304, ... ERROR: unrecognized configuration parameter "databases"

### ISSUE THREAD

**Issue by rarexixi** [apache/incubator-linkis#1822]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-engineConnplugin

### What happened + What you expected to happen

I want to connect to postgresql, I get a error when I select a table
**error:** 
21304, Task is Failed,errorMsg: PSQLException: ERROR: unrecognized configuration parameter "databases"

### Relevent platform

linkis-engineplugin-jdbc

### Reproduction script

execute "select 1" in Scripts

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rarexixi** [comment]
ConnectionManager.createDataSources
props.put("validationQuery", "show databases;");

**Comment by peacewong** [comment]
duplicate issue https://github.com/apache/incubator-linkis/issues/1609
