### ISSUE TITLE
[Feature] update commons-lang to commons-lang3

### ISSUE THREAD

**Issue by husofskyzy** [apache/incubator-linkis#1824]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### 1.1 The general commons-lang method can be directly upgraded to the commons-lang3 method  
The main modification is to convert some passed parameters from String to charSequences. Passing String parameters is feasible in most cases.

#### In the scala code, String[] to charSequences will merge String array parameters into a string by default, which requires special declaration  
val closeBrackets = Array("}", ")", "]")  
commons-lang parameter method StringUtils.endsWithAny(real, openBrackets)  
commons-lang3 parameter passing method StringUtils.endsWithAny(real, openBrackets: _*)  

### 1.4 When the ClassUtils.getClass(className) method under commons-lang is replaced by the commons-lang3 package, you need to add a forced conversion (Class<? extends LabelBuilderFactory>) ClassUtils.getClass(className);

-------

### 1.1 一般commons-lang方法可以直接升级为commons-lang3的方法
主要修改是将一些传参从String转为charSequences,在多数情况下传String参数都可行.

#### scala代码中String[]转charSequences会默认合并String数组参数成一个字符串,需要特殊声明
val closeBrackets = Array("}", ")", "]")
commons-lang传参方法 StringUtils.endsWithAny(real, openBrackets)
commons-lang3传参方法  StringUtils.endsWithAny(real, openBrackets: _*)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
This needs to be fixed
