### ISSUE TITLE
[Bug] JDBC engine start with multiple SLF4J bindings error

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis#1825]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-engineConnplugin

### What happened + What you expected to happen

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/data/bdp/linkis/engineconns/engineConnPublickDir/ba71093f-0d8a-4f72-8c60-927b8767e6a4/v000008/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/data/Install/LinkisInstall/linkis-dev-1.1.0.20220329105903/lib/linkis-commons/public-module/log4j-slf4j-impl-2.13.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
```
slf4j-log4j12 conflicts with log4j-slf4j-impl.
As a result, the log cannot be written to the log file normally
the dependence of slf4j-log4j12 should be excluded

### Relevent platform

Version:linkis-1.1.0 
Linux

### Reproduction script

```
sh bin/linkis-cli -submitUser hadoop   -engineType jdbc-4 -codeType jdbc  -code "show tables"
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by seedscoder** [comment]
I'll fix it if there's no one else

**Comment by peacewong** [comment]
> I'll fix it if there's no one else

Thanks, please submit to dev-1.1.2

**Comment by legendtkl** [comment]
Hi, @seedscoder , how is it going now  ?

Would you help submit a PR for this?

Thanks.
