### ISSUE TITLE
[Feature][1.1.2] upgrade log4j-1.2.17 due to security vulnerabilities 

### ISSUE THREAD

**Issue by peacewong** [apache/incubator-linkis#1826]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### What happened + What you expected to happen

upgrade log4j-1.2.17 due to security vulnerabilities,Recommended to upgrade to 2.17.1.
Find which modules use:
```
cd linkis-home
find -name log4j-1.2.17*
```

### Relevent platform

all

### Reproduction script

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by huapan123456** [comment]
can i do it?

**Comment by peacewong** [comment]
> can i do it?

yes

**Comment by legendtkl** [comment]
Hi, @huapan123456 , how is it going on about this?

Would you help submit a PR for it?

Thanks.

**Comment by huapan123456** [comment]
done
