### ISSUE TITLE
[Feature][1.1.2] upgrade protobuf-java due to security vulnerabilities

### ISSUE THREAD

**Issue by peacewong** [apache/incubator-linkis#1827]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### What happened + What you expected to happen

upgrade protobuf-java due to security vulnerabilities,Recommended to upgrade to  3.15.x
Find which modules use:
```
cd linkis-home
find -name protobuf-java*
```

### Relevent platform

all

### Reproduction script

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by huapan123456** [comment]
can i do it ?

**Comment by peacewong** [comment]
> can i do it ?

yes

**Comment by legendtkl** [comment]
Hi, @huapan123456 , how is it going ?

Would you help submit a PR for this issue?

Thanks.

**Comment by huapan123456** [comment]
I will submit a PR .

**Comment by huapan123456** [comment]
Done
