### ISSUE TITLE
[Feature][1.1.2] upgrade jackson-databind due to security vulnerabilities

### ISSUE THREAD

**Issue by peacewong** [apache/incubator-linkis#1828]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### What happened + What you expected to happen

upgrade jackson-databind due to security vulnerabilities,Recommended to upgrade to 2.13.2.1
Find which modules use:
```
cd linkis-home
find -name jackson-databind*
```

### Relevent platform

all

### Reproduction script

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by huapan123456** [comment]
can i do it ?

**Comment by peacewong** [comment]
> can i do it ?

yes

**Comment by legendtkl** [comment]
Hi, @huapan123456 , would you help submit a PR for this?

Thanks.

**Comment by huapan123456** [comment]
Someone had submit a PR for this.
