### ISSUE TITLE
[Feature] Linkis management console resource reset page, the search result list is arranged in the order of user name

### ISSUE THREAD

**Issue by peacewong** [apache/incubator-linkis#1833]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

The linkis management console resource reset page, the search result list is arranged in the order of the user name, and now the returned results are out of order. It is recommended to sort the results before returning them.
linkis管理台资源重置页面，搜索的结果列表按照用户名顺序排列，现在返回结果是乱序的，建议结果返回前做下排序
api:RMMonitorRest-->allUserResource
![image](https://user-images.githubusercontent.com/11496700/160780603-de62ee40-a940-46ce-aee9-eb4cf3f1e2f1.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by seedscoder** [comment]
I want to solve this issue

**Comment by peacewong** [comment]
> I want to solve this issue

ok

**Comment by peacewong** [comment]
> I want to solve this issue
Hello, what is the current progress of this task? In addition, I sent an email to your email seedscoder@gmail.com, please help to reply

**Comment by Alexkun** [comment]
done
