### ISSUE TITLE
[Feature] On the linkis management console resource reset page, make the search results are listed in the order of user names.

### ISSUE THREAD

**Issue by husofskyzy** [apache/incubator-linkis#1860]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Description

On the linkis management console resource reset page, make the search results are listed in the order of user names.    
![orderList](https://user-images.githubusercontent.com/29391030/161363833-2dfb6229-c759-4b81-a219-7950103d83f6.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
duplicate issue #1833
