### ISSUE TITLE
[Feature][WEB][1.1.2] Linkis management console resource display and reset page, resource display should display instance and Yarn instances

### ISSUE THREAD

**Issue by peacewong** [apache/incubator-linkis#1862]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

linkis管理台资源重置页面，资源显示应该显示instance和Yarn instances
Linkis management console resource display and reset page, resource display should display instance and Yarn instances
ecm manager:ecm管理页面
![image](https://user-images.githubusercontent.com/11496700/161252630-23bffada-6acf-4e33-b176-e41d4d7475ac.png)
resource reset:资源管理重置页面
![image](https://user-images.githubusercontent.com/11496700/161254289-585354e0-4443-479a-a0e5-d5d60353fa77.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by CCweixiao** [comment]
I try to fix it.
