### ISSUE TITLE
[Bug] [1.1.2]Administrator interface common users can access unauthorized access

### ISSUE THREAD

**Issue by peacewong** [apache/incubator-linkis#1867]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-public-enhancements

### What happened + What you expected to happen

The /api/rest_j/v1/configuration/createSecondCategory interface can override the authority to add engine types
/api/rest_j/v1/configuration/createSecondCategory接口可越权新增引擎类型

The /api/rest_j/v1/microservice/allInstance interface can query the list of microservices without authority
/api/rest_j/v1/microservice/allInstance接口可越权查询微服务清单

It is recommended to judge the administrator user, through the method:
`Configuration.isAdmin`

### Relevent platform

all

### Reproduction script

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by legendtkl** [comment]
I will fix this
