### ISSUE TITLE
[Bug][ResourceManager]Resource moreThan Judgment logic bug

### ISSUE THREAD

**Issue by wForget** [apache/incubator-linkis#187]
有多个属性的 Resource 类 moreThan 方法没有考虑个别属性相等，其他的大于的情况。
The moretan method of resource class with multiple attributes does not consider the case that individual attributes are equal and others are greater than.

  def moreThan(r: Resource): Boolean =
    memory > r.memory && cores > r.cores && instances > r.instances

**Comment by wushengyeyouya** [comment]
Thanks very much, we will fix it in next release.
