### ISSUE TITLE
[Bug][1.1.2] A NullPointerException could be thrown in class SyncSubmission.java of module  linkis-computation-governance

### ISSUE THREAD

**Issue by husofskyzy** [apache/incubator-linkis#1872]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-public-enhancements

### What happened + What you expected to happen
module: linkis-cli-core 
class: org.apache.linkis.cli.core.interactor.execution.SyncSubmission  
![企业微信截图_16488803646975](https://user-images.githubusercontent.com/29391030/161369843-3714d86d-c843-4a6b-b928-e5297a13084c.png)  

 A NullPointerException could be thrown

### Relevent platform

all

### Reproduction script

no

### Anything else

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by casionone** [comment]
- #1722
