### ISSUE TITLE
[Bug][1.1.2] judge condition duplicates

### ISSUE THREAD

**Issue by husofskyzy** [apache/incubator-linkis#1875]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### What happened + What you expected to happen

module: linkis-entrance  
class: org.apache.linkis.entrance.interceptor.impl.Explain  
![企业微信截图_16488814667477](https://user-images.githubusercontent.com/29391030/161370599-e4d7dd97-b98d-4ecf-a254-9a0bf4ef0665.png)  

judge condition duplicates

### Relevent platform

all

### Reproduction script

no

### Anything else

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by seedscoder** [comment]
Did anyone else start dealing with it? If not, I'll upgrade this component

**Comment by casionone** [comment]
> Did anyone else start dealing with it? If not, I'll upgrade this component

Looking forward to your participation. This task has been assigned to you.

**Comment by husofskyzy** [comment]
no problem, i will fix it.

**Comment by casionone** [comment]
has fix  commitid 551323b711fd5b00111c97fdb80d15a8e1a768d1
