### ISSUE TITLE
[Bug] [1.1.2] FileReader and BufferedReader are not closed in final clause

### ISSUE THREAD

**Issue by husofskyzy** [apache/incubator-linkis#1878]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### What happened + What you expected to happen

module: linkis-cs-client  
class: org.apache.linkis.cs.client.test.test_multiuser.TestChangeContext  
![企业微信截图_16488840244809](https://user-images.githubusercontent.com/29391030/161372095-e6772d05-b583-4c2a-81df-551acc7ca207.png)  

FileReader and BufferedReader are not closed in final clause

### Relevent platform

all

### Reproduction script

no

### Anything else

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wallezhang** [comment]
I want to fix this issue. Please assign to me.
