### ISSUE TITLE
[Bug] [1.1.2] change TestUDFTree class to junit test class and Use try-with-resources or close this "URLClassLoader" in a "finally" clause

### ISSUE THREAD

**Issue by husofskyzy** [apache/incubator-linkis#1883]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### What happened + What you expected to happen

module: linkis-udf-service
class: org.apache.linkis.udf.TestUDFTree
![企业微信截图_16488899547171](https://user-images.githubusercontent.com/29391030/161375812-c4a44d29-571f-40a7-86bd-9c0f8bfe77b3.png)  

change TestUDFTree class to junit test class and Use try-with-resources or close this "URLClassLoader" in a "finally" clause

### Relevent platform

all

### Reproduction script

no

### Anything else

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by legendtkl** [comment]
I will fix this

**Comment by husofskyzy** [comment]
OK，just do it.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月02日 22:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [apache/incubator-linkis] [Bug] [1.1.2] change TestUDFTree class to junit test class and Use try-with-resources or close this "URLClassLoader" in a "finally" clause (Issue #1883) |

I will fix this

**Comment by legendtkl** [comment]
Hi, @husofskyzy , I read the code, but can't get the point. And it also does not work.

Could you give some explains about this?

It's testing for loading class `org.apache.linkis.mask.udf.BdpAddressFirstEightMask` from the jar `E:\tm_client_1.6.jar` ? If so, would you upload the jar file here ? 

Thanks,
Kelu

**Comment by husofskyzy** [comment]
i do not have the package,you can make a package yourself,and use an example to test hive.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月03日 15:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [apache/incubator-linkis] [Bug] [1.1.2] change TestUDFTree class to junit test class and Use try-with-resources or close this "URLClassLoader" in a "finally" clause (Issue #1883) |

Hi, @husofskyzy , I read the code, but can't get the point. And it also does not work.

Could you give some explains about this?

It's testing for loading class org.apache.linkis.mask.udf.BdpAddressFirstEightMask from the jar E:\tm_client_1.6.jar ? If so, would you upload the jar file here ?

Thanks,
Kelu

**Comment by husofskyzy** [comment]
I don't have this package. You can write a class that inherits UDF and package it yourself

> Hi, @husofskyzy , I read the code, but can't get the point. And it also does not work.
> 
> Could you give some explains about this?
> 
> It's testing for loading class `org.apache.linkis.mask.udf.BdpAddressFirstEightMask` from the jar `E:\tm_client_1.6.jar` ? If so, would you help upload the jar file here ?
> 
> Thanks, Kelu

I don't have this package. You can write a class that inherits UDF and package it yourself
