### ISSUE TITLE
[Bug] [Web][1.1.1] dss/getBaseInfo http api with NoApplicationExistsException

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis#1888]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

web

### What happened + What you expected to happen

![企业微信截图_16488936642933](https://user-images.githubusercontent.com/7869972/161378107-b5b639b4-f3e7-447a-b576-35a4c2eabd72.png)

![企业微信截图_16488933793430](https://user-images.githubusercontent.com/7869972/161377945-62a0594a-9d2d-4600-9806-cf34e75ec8fc.png)

linkis does not depend on dss this interface seems unreasonable. 

And there is an abnormal icon in the top bar

### Relevent platform

none

### Reproduction script

refresh page

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
The management console needs to sort out the interfaces and remove the non-linkis-related interfaces
管理台需要梳理下接口，移除非linkis相关的接口
