### ISSUE TITLE
Add junit5 test code for module [linkis-scheduler]

### ISSUE THREAD

**Issue by husofskyzy** [apache/incubator-linkis#1914]
## Add junit5 test code for module [linkis-scheduler]
- Module: linkis-scheduler
- Location:linkis-commons/linkis-scheduler
- Task status:&cross;(unfinished)/ &check;(finished) 
- Test code guide:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- Test code example: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test
-------
- 模块名: linkis-scheduler
- 代码位置:linkis-commons/linkis-scheduler
- 任务状态:&cross;(unfinished)/ &check;(finished) 
- 单测编写指引:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- 参考样例: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test

| Task status| Class | Type| Level of Difficulty | Note|
| :------ | :------ | :------: | :------: | :------: |
| &cross; | org.apache.linkis.scheduler.conf.* | Conf | normal |  |
| &cross; | org.apache.linkis.scheduler.event.* | Event | normal |  |
| &cross; | org.apache.linkis.scheduler.exception.* | Exception | normal |  |
| &cross; | org.apache.linkis.scheduler.executer.* | Executer | normal |  |
| &cross; | org.apache.linkis.scheduler.future.* | Future | normal |  |
| &cross; | org.apache.linkis.scheduler.queue.fifoqueue.* | Queue | normal |  |
| &cross; | org.apache.linkis.scheduler.queue.parallelqueue.* | Queue | normal |  |
| &cross; | org.apache.linkis.scheduler.queue.* | Queue | normal|  |

**Comment by QuintinTao** [comment]
i want to try.

**Comment by QuintinTao** [comment]
> ## Add junit5 test code for module [linkis-scheduler]
> * Module: linkis-scheduler
> * Location:linkis-commons/linkis-scheduler
> * Task status:✗(unfinished)/ ✓(finished)
> * Test code guide:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
> * Test code example: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test
> 
> * 模块名: linkis-scheduler
> * 代码位置:linkis-commons/linkis-scheduler
> * 任务状态:✗(unfinished)/ ✓(finished)
> * 单测编写指引:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
> * 参考样例: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test
> 
> Task status	Class	Type	Level of Difficulty	Note
> ✗	org.apache.linkis.scheduler.conf.*	Conf	normal	
> ✗	org.apache.linkis.scheduler.event.*	Event	normal	
> ✗	org.apache.linkis.scheduler.exception.*	Exception	normal	
> ✗	org.apache.linkis.scheduler.executer.*	Executer	normal	
> ✗	org.apache.linkis.scheduler.future.*	Future	normal	
> ✗	org.apache.linkis.scheduler.queue.fifoqueue.*	Queue	normal	
> ✗	org.apache.linkis.scheduler.queue.parallelqueue.*	Queue	normal	
> ✗	org.apache.linkis.scheduler.queue.*	Queue	normal

I want to try it
