### ISSUE TITLE
Junit5 test completion of each module

### ISSUE THREAD

**Issue by husofskyzy** [apache/incubator-linkis#1918]
当前状态:✗(unfinished)/ ✓(finished)

| 模块名| issue | 当前状态| 负责人 | 进度 | 备注 |
| :------ | :------ | :------: | :------: | :------: | :------: |
| linkis-common                          | #1634 | &cross; | めぐみん | 50% | pr#1740 |
| linkis-hadoop-common                   | #1647 | &cross; |  |  |   |
| linkis-httpclient                      | #1648 | &cross; |  |  |   |
| linkis-message-scheduler               | #1657 | &cross; |  |  |   |
| linkis-module                          | #1658 | &cross; |  |  |   |
| linkis-mybatis                         | #1659 | &cross; |  |  |   |
| linkis-protocol                        | #1844 | &cross; |  |  |   |
| linkis-rpc                             | #1913 | &cross; |  |  |   |
| linkis-scheduler                       | #1914 | &cross; |  |  |   |
| linkis-storage                         | #1908 | &cross; |  |  |   |
| linkis-cli-core                        | #1915 | &cross; |  |  |   |
| linkis-cli-application                 | #1916 | &cross; |  |  |   |
| linkis-cli-common                      | #1917 | &cross; |  |  |   |
| linkis-computation-client              | # | &cross; |  |  |   |
| linkis-computation-governance-common   | # | &cross; |  |  |   |
| linkis-once-engineconn                 | # | &cross; |  |  |   |
| linkis-computation-engineconn          | # | &cross; |  |  |   |
| linkis-engineconn-common               | # | &cross; |  |  |   |
| linkis-engineconn-core                 | # | &cross; |  |  |   |
| accessible-executor                    | # | &cross; |  |  |   |
| callback-service                       | # | &cross; |  |  |   |
| executor-core                          | # | &cross; |  |  |   |
| linkis-engineconn-launch               | # | &cross; |  |  |   |
| linkis-engineconn-linux-launch         | # | &cross; |  |  |   |
| linkis-engineconn-manager-core         | # | &cross; |  |  |   |
| linkis-engineconn-manager-server       | # | &cross; |  |  |   |
| linkis-entrance                        | # | &cross; |  |  |   |
| linkis-entrance-client                 | # | &cross; |  |  |   |
| linkis-jdbc-driver                     | # | &cross; |  |  |   |
| label-common                           | # | &cross; |  |  |   |
| label-manager                          | # | &cross; |  |  |   |
| linkis-application-manager             | # | &cross; |  |  |   |
| linkis-manager-commons                 | # | &cross; |  |  |   |
| linkis-manager-client                  | # | &cross; |  |  |   |
| linkis-manager-persistence             | #1630 | &cross; |  |  |   |
| linkis-resource-manager                | # | &cross; |  |  |   |
| engineconn-plugins/flink               | # | &cross; |  |  |   |
| engineconn-plugins/hive                | # | &cross; |  |  |   |
| engineconn-plugins/io_file             | # | &cross; |  |  |   |
| engineconn-plugins/jdbc                | # | &cross; |  |  |   |
| engineconn-plugins/pipeline            | # | &cross; |  |  |   |
| engineconn-plugins/python              | # | &cross; |  |  |   |
| engineconn-plugins/shell               | # | &cross; |  |  |   |
| engineconn-plugins/spark               | # | &cross; |  |  |   |
| linkis-engineconn-plugin-cache         | # | &cross; |  |  |   |
| linkis-engineconn-plugin-core          | # | &cross; |  |  |   |
| linkis-engineconn-plugin-loader        | # | &cross; |  |  |   |
| linkis-engineconn-plugin-server        | # | &cross; |  |  |   |
| linkis-io-file-client                  | # | &cross; |  |  |   |
| linkis-code-orchestrator               | # | &cross; |  |  |   |
| linkis-computation-orchestrator        | # | &cross; |  |  |   |
| linkis-orchestrator-core               | # | &cross; |  |  |   |
| linkis-bml-client                      | # | &cross; |  |  |   |
| linkis-bml-common                      | # | &cross; |  |  |   |
| linkis-bml-engine-hook                 | # | &cross; |  |  |   |
| linkis-bml-server                      | # | &cross; |  |  |   |
| linkis-cs-cache                        | # | &cross; |  |  |   |
| linkis-cs-client                       | # | &cross; |  |  |   |
| linkis-cs-common                       | # | &cross; |  |  |   |
| linkis-cs-engine-support               | # | &cross; |  |  |   |
| linkis-cs-highavailable                | # | &cross; |  |  |   |
| linkis-cs-listener                     | # | &cross; |  |  |   |
| linkis-cs-persistence                  | # | &cross; |  |  |   |
| linkis-cs-search                       | # | &cross; |  |  |   |
| linkis-cs-server                       | # | &cross; |  |  |   |
| linkis-datasource-client               | # | &cross; |  |  |   |
| linkis-metadata                        | # | &cross; |  |  |   |
| linkis-datasource-manager/common       | # | &cross; |  |  |   |
| linkis-datasource-manager/server       | # | &cross; |  |  |   |
| linkis-metadata-manager/common         | # | &cross; |  |  |   |
| linkis-metadata-manager/server         | # | &cross; |  |  |   |
| service/mysql                          | # | &cross; |  |  |   |
| service/kafka                          | # | &cross; |  |  |   |
| service/hive                           | # | &cross; |  |  |   |
| service/elasticsearch                  | # | &cross; |  |  |   |
| linkis-configuration                   | # | &cross; |  |  |   |
| linkis-error-code-client               | # | &cross; |  |  |   |
| linkis-error-code-common               | # | &cross; |  |  |   |
| linkis-error-code-server               | # | &cross; |  |  |   |
| linkis-instance-label-client           | # | &cross; |  |  |   |
| linkis-instance-label-server           | # | &cross; |  |  |   |
| linkis-jobhistory                      | # | &cross; |  |  |   |
| linkis-storage-script-dev-client       | # | &cross; |  |  |   |
| linkis-storage-script-dev-server       | # | &cross; |  |  |   |
| linkis-udf-client                      | # | &cross; |  |  |   |
| linkis-udf-common                      | # | &cross; |  |  |   |
| linkis-udf-service                     | # | &cross; |  |  |   |
| linkis-variable                        | # | &cross; |  |  |   |
| linkis-eureka                          | # | &cross; |  |  |   |
| linkis-gateway-core                    | # | &cross; |  |  |   |
| linkis-gateway-httpclient-support      | # | &cross; |  |  |   |
| linkis-gateway-server-support          | # | &cross; |  |  |   |
| linkis-spring-cloud-gateway            | # | &cross; |  |  |   |

**Comment by casionone** [comment]
the new issue is #2985
