### ISSUE TITLE
[Bug] [linkis1.0.3]Linkis task could not be submitted by idle EC

### ISSUE THREAD

**Issue by lueric123** [apache/incubator-linkis#1926]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-engineConnManager

### What happened + What you expected to happen

Linkis task could not be submitted by idle EC
Have you ever seen

### Relevent platform

llinkis

### Reproduction script

Linkis task could not be submitted by idle EC

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Hello, the engine loaded by idle is locked by a service, and only the service can submit tasks. You need to be able to submit tasks directly. You need the unlock state. You need to acquire the lock first and then submit the task.
