### ISSUE TITLE
[Bug] Linkis StorageUtils throw ClassCastException

### ISSUE THREAD

**Issue by shenbinglife** [apache/incubator-linkis#1960]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-entrance

### What happened + What you expected to happen

![lQLPDhtTuv8JT0nNASPNBjuwbPv2A9k3MXYCWdtv0QAGAA_1595_291](https://user-images.githubusercontent.com/16119667/163094323-1b35d554-ab92-4b3d-b908-85df8dba3679.png)

### Relevent platform

DSS1.0.1 Linkis1.0.3

### Reproduction script

None

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Hi, can you describe in detail which operation occurs? and the full log

**Comment by shenbinglife** [comment]
fix with change StorageUtils classloader method
