### ISSUE TITLE
[Feature][Web] Detail optimization of some pages

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis#1967]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

![企业微信截图_16498440923968](https://user-images.githubusercontent.com/7869972/163159540-ed3b527c-d6f5-4823-b168-4e700d9e0725.png)

![企业微信截图_1649844761201](https://user-images.githubusercontent.com/7869972/163159574-bb542c87-35f4-4812-a70d-692b8749ed18.png)

![企业微信截图_16498448712569](https://user-images.githubusercontent.com/7869972/163159599-701d4a26-2372-489a-88c1-02750624de33.png)

![企业微信截图_16498457303754](https://user-images.githubusercontent.com/7869972/163159607-9bd7670b-cf28-4697-90e4-189c5b54742a.png)

https://linkis.apache.org/zh-CN/faq/main

![企业微信截图_16498457734092](https://user-images.githubusercontent.com/7869972/163160285-7db44930-60df-425e-9127-8c610cfe779a.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by CCweixiao** [comment]
can I do？

**Comment by casionone** [comment]
> can I do？

OK please note commit your pr to the dev-1.1.1 branch
