### ISSUE TITLE
[Bug] Modify the Spark version to 2.3.0 and compile with error

### ISSUE THREAD

**Issue by beidouyunyun** [apache/incubator-linkis#1991]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-engineConnplugin

### What happened + What you expected to happen

操作如下：
1.修改incubator-linkis-release-1.0.3/linkis-engineconn-plugins/engineconn-plugins/spark/pom.xml
<spark.version>2.3.0</spark.version>
2.编译linkis-engineconn-plugins

报错内容如下：
[ERROR] /opt/WedataSphere/incubator-linkis-release-1.0.3/linkis-engineconn-plugins/engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/executor/SparkPythonExecutor.scala:87: value authToken is not a member of py4j.GatewayServer.GatewayServerBuilder
[ERROR]     try builder.authToken(py4jToken) catch {
[ERROR]                 ^
[WARNING] /opt/WedataSphere/incubator-linkis-release-1.0.3/linkis-engineconn-plugins/engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/executor/SparkScalaExecutor.scala:96: a pure expression does nothing in statement position; you may be omitting necessary parentheses
[WARNING]                 null
[WARNING]                 ^
[WARNING] one warning found

### Relevent platform

Maven == 3.6.3
JDK == 1.8.0_301
Linux == Centos7.8

### Reproduction script

mvn clean install -Dmaven.test.skip=true

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by casionone** [comment]
Unfortunately there is a compatibility issue with spark versions.

The version of net.sf.py4j that spark-core_2.11:2.4.3 depends on is 0.10.7
The version of net.sf.py4j that spark-core_2.11:2.3.0 depends on is 0.10.6
The authToken method was introduced in the py4j.GatewayServer.GatewayServerBuilder version 0.10.7 of py4j.
Details can be viewed:
https://github.com/py4j/py4j/blob/0.10.6/py4j-java/src/main/java/py4j/GatewayServer.java
https://github.com/py4j/py4j/blob/0.10.7/py4j-java/src/main/java/py4j/GatewayServer.java
You can try to manually introduce the dependencies of the 0.10.7 version of py4j to solve this problem

----
是存在spark版本的兼容性问题。
spark-core_2.11:2.4.3版本依赖的net.sf.py4j版本是0.10.7
spark-core_2.11:2.3.0版本依赖的net.sf.py4j版本是0.10.6
py4j的版本0.10.7版本的py4j.GatewayServer.GatewayServerBuilder 才引入了authToken方法 。
详细可以查看：
https://github.com/py4j/py4j/blob/0.10.6/py4j-java/src/main/java/py4j/GatewayServer.java
https://github.com/py4j/py4j/blob/0.10.7/py4j-java/src/main/java/py4j/GatewayServer.java
可以尝试手动引入py4j的0.10.7 版本的依赖，来解决这个问题
