### ISSUE TITLE
[Bug] Issues with download page

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-linkis#2011]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

web

### What happened + What you expected to happen

The download page [1] contains the following text:

"For detailed specification requirements of download pages, see:" together with a link.

However that page is only intended for ASF developers when setting up a download page; it is not really appropriate for 3rd parties wishing to download ASF software.

[1] https://linkis.apache.org/download/main

### Relevent platform

N/A

### Reproduction script

N/A

### Anything else

This form is not really suitable for reporting website issues

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by casionone** [comment]
Thank you for your reminder and feedback. This content is indeed easy to cause misunderstandings. Can you help to revise and remove this description?

**Comment by sebbASF** [comment]
Just remove the sentence entirely.

**Comment by casionone** [comment]
This issue has been fixed and I will close this issue
