### ISSUE TITLE
[Bug] 使用spark2.4.8作为saprk引擎，执行报错

### ISSUE THREAD

**Issue by LEOPROGRAM** [apache/incubator-linkis#2029]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-engineConnplugin

### What happened + What you expected to happen

![1650871352(1)](https://user-images.githubusercontent.com/11906632/165039903-e7915039-c6f6-43ae-b46b-e22944512e6d.png)
执行spark引擎的时候报错，在创建的时候提示没有加载hive相关的类

### Relevent platform

centos 7.3 CDH6.3.2 spark 2.4.8

### Reproduction script

    if (jars.nonEmpty) conf.setJars(jars)
    if (execUri != null) conf.set("spark.executor.uri", execUri)
    if (System.getenv("SPARK_HOME") != null) conf.setSparkHome(System.getenv("SPARK_HOME"))
    conf.set("spark.scheduler.mode", "FAIR")
    info("test.spark.conf====> tostring: " + conf.toDebugString)

    val builder = SparkSession.builder.config(conf)
    builder.enableHiveSupport().getOrCreate()

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Hello, this needs to confirm whether there are hive related Jars in your local Spark

**Comment by LEOPROGRAM** [comment]
> Hello, this needs to confirm whether there are hive related Jars in your local Spark

Thanks. I'll try again.

**Comment by LEOPROGRAM** [comment]
> Hello, this needs to confirm whether there are hive related Jars in your local Spark
Is there？
![1650963527(1)](https://user-images.githubusercontent.com/11906632/165263209-1192fc17-8c98-4187-ae86-2c3840a52df6.png)

/opt/spark-2.4.8-bin-hadoop2.7/jars
