### ISSUE TITLE
[Bug] [Entrance]HDFSCacheLogWriter getOutPutStream NPE

### ISSUE THREAD

**Issue by peacewong** [apache/incubator-linkis#2040]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-entrance

### What happened + What you expected to happen

There is an NPE problem in HDFSCacheLogWriter getOutputStream, and it does not judge whether the fileSystem is Null
HDFSCacheLogWriter getOutputStream存在NPE问题，没有判断fileSystem是否为Null
```
def getOutputStream: OutputStream = {
    if (null == outputStream) OUT_LOCKER.synchronized {
      if (null == outputStream) {

        outputStream = fileSystem.write(new FsPath(logPath), false)
      }
    }
    outputStream
  }
```
You should make a short judgment when writeToFile is called, and give a Warn-level log
![Uploading image.png…]()

### Relevent platform

all

### Reproduction script

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Dlimeng** [comment]
I want to fix this issue. Please assign to me.

**Comment by peacewong** [comment]
> I want to fix this issue. Please assign to me.

ok
