### ISSUE TITLE
[Feature][Web] Detailed optimization suggestions for linkis web pages

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis#2050]
1 全局历史页面 

布局留白比较多 导致视觉不紧凑，有割裂感。表头/分页栏 感觉都应该固定 不需随滚动移动
![企业微信截图_16510649029055](https://user-images.githubusercontent.com/7869972/165525056-77d18007-61bb-429a-8158-29c3540a475c.png)

状态栏最长字段“申请资源中”
![image](https://user-images.githubusercontent.com/7869972/165528605-14277d03-725b-4d35-a229-df617c5b6f04.png)

![企业微信截图_16510623201950](https://user-images.githubusercontent.com/7869972/165527880-153445ad-0952-42fc-b602-1e59019cca95.png)

2 数据源管理页面 
搜索属性缺失标题 操作按钮风格没有与全局按钮格式统一 分页风格未统一
![企业微信截图_16510635739875](https://user-images.githubusercontent.com/7869972/165525075-fbe3374f-3689-4aa5-bd70-33d51f6ecea5.png)
![image](https://user-images.githubusercontent.com/7869972/165527786-49773210-f3a1-4d77-86fe-48c20a92e15f.png)

3 菜单栏 
支持二级菜单
![企业微信截图_16510634091002](https://user-images.githubusercontent.com/7869972/165525442-9d2bb723-7807-4907-88e8-cab0b62eaea1.png)

4 UDF管理
UDF管理&函数管理 新增弹框 滚动录入体验不是很好
![企业微信截图_16510630621443](https://user-images.githubusercontent.com/7869972/165525510-e9993261-ddf0-48a2-ae7f-d664f52e991e.png)

5 UDF管理 
UDF管理&函数管理 table风格与全局风格有差异，右侧留白 没填充满，分页栏需要固定，国际化修改
![企业微信截图_16510633437940](https://user-images.githubusercontent.com/7869972/165526031-c68c3ed6-8ec2-4961-9154-3572e2008d94.png)

![企业微信截图_16510629164178](https://user-images.githubusercontent.com/7869972/165525975-375d7ca4-3e54-4d0c-9693-eb330c10b7de.png)

6 全局变量 

![企业微信截图_16510627982456](https://user-images.githubusercontent.com/7869972/165526209-1ff43a0f-3b77-4cb0-bb8e-bea35ceef75a.png)

7 资源管理>切换管理员视图

![企业微信截图_16510626797006](https://user-images.githubusercontent.com/7869972/165526693-10a69be3-a706-4ef1-b8bf-c62784e8606a.png)

![企业微信截图_16510625727754](https://user-images.githubusercontent.com/7869972/165526430-0ea79535-c9aa-4240-a56d-f6b9cb4e3fc0.png)

![企业微信截图_16510623994936](https://user-images.githubusercontent.com/7869972/165526868-49e72922-2c60-48ab-9701-e28ed7b1c3a2.png)

8 参数配置 

![企业微信截图_1651677670596](https://user-images.githubusercontent.com/7869972/166857001-2e0706e1-0f18-4f41-acc7-8e190001b102.png)
![image](https://user-images.githubusercontent.com/7869972/166857012-b83e2072-2996-4f33-b485-2c0b7cc5de26.png)

9. 其他
表格table的表头 分割不同页面没有统一，建议修改为统一风格
表格table的表头/表的分页栏 不应该跟随滚动，应该固定 
表格列表数据填充后左右上下都有滚动时 视觉体验不是特别好，后续需要考虑如何优化

![企业微信截图_16510659785371](https://user-images.githubusercontent.com/7869972/165528526-ab9f277a-56f3-484e-a03a-9a52d141cbbe.png)

**Comment by Liveipool** [comment]
问题1已解决：另外状态栏也缩短了，最短为刚好能够显示最长的状态

![image](https://user-images.githubusercontent.com/14949531/168791712-dba982e0-89b4-4778-8821-c224c3ecb924.png)

**Comment by Liveipool** [comment]
问题2：所有表格内按钮风格已统一

![image](https://user-images.githubusercontent.com/14949531/168791912-2009c2d1-d4a5-4fbf-9c7f-2b1dc6182e5c.png)

<img width="657" alt="image" src="https://user-images.githubusercontent.com/14949531/168791989-e30beedd-2761-471b-a309-4577731ae80c.png">

**Comment by Liveipool** [comment]
问题3: 已设置成二级菜单

![image](https://user-images.githubusercontent.com/14949531/168792098-fb6162b6-926f-4813-9c37-f5d582704ac9.png)

**Comment by Liveipool** [comment]
问题4:我改了一遍，改成了两列的，但发现虽然不会竖向滚动了，但可能会有横向滚动，这样的话还不如竖向滚动，所以建议保持现在不动。

<img width="821" alt="image" src="https://user-images.githubusercontent.com/14949531/168792217-ff37e775-1714-43cc-a50c-50b287c1c194.png">

**Comment by Liveipool** [comment]
问题5:已修改

**Comment by Liveipool** [comment]
问题6:目前暂时不需要分页显示，在很多页面上是多余的，分页功能暂时不太需要

**Comment by Liveipool** [comment]
问题7: 已完成改动

![image](https://user-images.githubusercontent.com/14949531/168792857-62856ee8-bdaf-4699-8bb1-fa6a9b021ef1.png)

**Comment by Liveipool** [comment]
问题8:已修复

![image](https://user-images.githubusercontent.com/14949531/168792941-3543f837-eb40-4256-88c7-2e2e89452c40.png)

**Comment by Liveipool** [comment]
问题9：旧代码中，所有页面里，至少有4种不同的表格，所以现在很难统一，不同页面的列也有不同的情况。所以现在统一其实比较困难，可以看看哪些页面的表格有问题，然后来修复有问题的。主要是太多种表格了，不知道之前为什么会有这么多种表格，现在不太好统一。

**Comment by Liveipool** [comment]
问题9：旧代码中，所有页面里，至少有4种不同的表格，所以现在很难统一，不同页面的列也有不同的情况。所以现在统一其实比较困难，可以看看哪些页面的表格有问题，然后来修复有问题的。主要是太多种表格了，不知道之前为什么会有这么多种表格，现在不太好统一。
