### ISSUE TITLE
[Bug] Linkis1.1.0 JDBC engine initialization failed

### ISSUE THREAD

**Issue by MrFengqin** [apache/incubator-linkis#2103]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-engineConnManager

### What happened + What you expected to happen

JDBC engine initialization calls Kerberos authentication, resulting in service startup failure and error: server asks us to fall back to simple auth, but this client is configured to only allow secure connections
![784eedd5bf2b2a672c76a88e46a94ff](https://user-images.githubusercontent.com/7869972/168201291-63f6ecb7-93a8-444f-b88b-2faa48a14446.png)

### Relevent platform

linkis

### Reproduction script

ErrorExecuteResponse(21304, Task is Failed,errorMsg: IOException: Server asks us to fall back to SIMPLE auth, but this client is configured to only allow secure connections.,null)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by casionone** [comment]
@CCweixiao  Please help confirm this

**Comment by CCweixiao** [comment]
> @CCweixiao Please help confirm this

I will to fix it.
