### ISSUE TITLE
linkis-service-gateway [Bug] 

### ISSUE THREAD

**Issue by Dlimeng** [apache/incubator-linkis#2125]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-service-gateway

### What happened + What you expected to happen

With the same password, you can log in to other users. After successfully logging in, there are other errors, and the gateway does not clear the user information.

bug video demo
链接: https://pan.baidu.com/s/1gn45edz5ifQ3DWMZDCMsBg 提取码: 2b9d 
--来自百度网盘超级会员v8的分享

### Relevent platform

linkis 1.0.3 

### Reproduction script

无

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Hi, can you give me the steps to reproduce it? I understand if it is a front-end cookie cleaning problem
