### ISSUE TITLE
[Bug] Scripts of linkis-cli without execute permission

### ISSUE THREAD

**Issue by jinquanzhuang** [apache/incubator-linkis#2144]
Newly installed linkis, no execute permission
![image](https://user-images.githubusercontent.com/101614307/169485137-f0c5c1a9-c164-4787-920a-225ba11a5172.png)
linkis-cli should grant +x permissions,
There are settings permissions in src/main/assembly/assembly.xml, but it doesn't seem to work
```
    <fileSet>
      <directory>
        bin/
      </directory>
      <outputDirectory>bin</outputDirectory>
      <includes>
        <include>**/*</include>
      </includes>
      <fileMode>0755</fileMode>
      <lineEnding>unix</lineEnding>
    </fileSet>
```

**Comment by casionone** [comment]
@legendtkl  Help follow up on this issue

**Comment by legendtkl** [comment]
HI, @jinquanzhuang , is the distribution package built in your os ? 

What's the OS platform? Windows or Linux ?
