### ISSUE TITLE
[Feature] Support the identification of ${run_today_h}, ${run_today_h_std} hour parameters

### ISSUE THREAD

**Issue by 2g5a4n5l1e9638** [apache/incubator-linkis#2179]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

 Support the identification of ${run_today_h}, ${run_today_std} hour parameters
Including scripts and workflow nodes on DSS (SQL, pyspark, datachecker, visualisation, etc.)

支持识别${run_today_h}、${run_today_std}小时参数 
包含dss上的scriptis、工作流各类型节点（sql、pyspark、datachecker、visualis等）

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by CCweixiao** [comment]
I want to do it.

**Comment by duhanmin** [comment]
已有类似pr
https://github.com/apache/incubator-linkis/pull/1969

**Comment by peacewong** [comment]
> 已有类似pr #1969
Is it possible to add support for run_today_h and run_today_h_std

**Comment by peacewong** [comment]
I have submitted a PR
