### ISSUE TITLE
[Feature] provide a parameter setting in the management console parameter to limit my available resources

### ISSUE THREAD

**Issue by 2g5a4n5l1e9638** [apache/incubator-linkis#2180]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

For the queue resource limit of hive, can I provide a parameter setting in the management console parameter to limit my available resources

对于hive的队列资源限制，   是否可在管理台参数提供一个参数设置限制本人的可用资源。支持设置 map个数、reduce个数。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
I will implement this
