### ISSUE TITLE
[Feature] DataApiService support JDBC engine execution

### ISSUE THREAD

**Issue by utopianet** [apache/incubator-linkis#2189]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

Currently, dataApiService only supports spark SQL execution engine. It is recommended to add the JDBC execution engine feature to adapt to richer application scenarios.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Xiejinwei93** [comment]
Yes, queries through Spark are slow, so I also think the API recommends direct JDBC queries

**Comment by Xiejinwei93** [comment]
Yes, queries through Spark are slow, so I also think the API recommends direct JDBC queries
