### ISSUE TITLE
[Feature][1.1.3] How to use grayscale update

### ISSUE THREAD

**Issue by legendtkl** [apache/incubator-linkis#2193]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Description

Once we support services offline dynamically, we need to have a discuss about how to use it by users.

Now we start/stop Linkis in scripts, maybe we can provide a another `grayscale_update.sh` to users.

Or any other ideas about this?

cc @peacewong 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by legendtkl** [comment]
need a discussion.

**Comment by peacewong** [comment]
> grayscale_update.sh

Yes, it is best to provide a graceful stop shell script, enter the service name to start a graceful stop. Only the entrance service needs to wait for the end of the tasks before stopping. Other services can exit by waiting for a config time (eg: 1m) after going offline.
