### ISSUE TITLE
[Bug] script resultset download 404

### ISSUE THREAD

**Issue by utopianet** [apache/incubator-linkis#2207]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

web

### What happened + What you expected to happen

After script running JDBC engine, click result set download, and the page prompts 404

http://dssdev01:8089/undefined/#/sheet/add?simpleMode=true&showBottomBar=false&importConfig={%22dataSourceConfig%22:{%22dataSourceType%22:%22linkis%22,%22dataSourceOptions%22:{%22taskID%22:138}},%22config%22:{%22myConfig%22:{%22resultSetPath%22:[%22hdfs:///tmp/linkis/hadoop/linkis/20220602_095408/IDE/138/_0.dolphin%22]},%22importConfig%22:{%22mergeTables%22:true,%22limitRows%22:5000,%22pivotTable%22:false,%22tableHeaderRows%22:1}}}&noGoingBack=true

### Relevent platform

centos 7.4
apache-linkis-1.0.3
wedatasphere-DataSphereStudio-1.0.1

### Reproduction script

show tables

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
How does undinfined appear in the url?Looks like a DSS issue
