### ISSUE TITLE
[Feature] [1.2.0] Establish a constraint mechanism to ensure that the data source connection parameter configuration items in the data source service are consistent with the JDBC engine parameter configuration items

### ISSUE THREAD

**Issue by CCweixiao** [apache/incubator-linkis#2211]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

是否需要建立约束机制，来保证数据源服务中数据源连接参数配置项与JDBC引擎参数配置项保持一致
Whether a constraint mechanism needs to be established to ensure that the data source connection parameter configuration items in the data source service are consistent with the JDBC engine parameter configuration items

如：JDBC引擎参数配置如下：
For example, the JDBC engine parameter configuration is as follows:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/27730211/171660276-61395505-98e7-4cea-9c3c-f6e2208df197.png">

但是，在数据源服务中，我定义一个数据源的配置，获取到的数据源连接参数的配置项信息如下：
However, in the data source service, I define the configuration of a data source, and the configuration item information of the obtained data source connection parameters is as follows:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/27730211/171660670-92b39958-a09e-48f1-ac9e-84471f3eca53.png">

在多数据源支持中，引擎参数配置项的键，与数据源连接信息的键没有保持一致，就需要额外的一些操作，来进行数据转换，是否有必要建立一种约束，来规定数据源连接参数的键呢？
In multi-data source support, if the key of the engine parameter configuration item is not consistent with the key of the data source connection information, additional operations are required to perform data conversion, whether it is necessary to establish a constraint to specify the data source connection What about the parameter keys?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
It is necessary to define and standardize the data source

**Comment by CCweixiao** [comment]
转换数据源连接参数为JDBC引擎的数据库连接参数
Convert the data source connection parameters to the database connection parameters of the JDBC engine
