### ISSUE TITLE
[Feature] [1.2.0] Added trino engine type

### ISSUE THREAD

**Issue by peacewong** [apache/incubator-linkis#2217]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

Added trino engine type to support trino scripts and engine labels

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by duhanmin** [comment]
我来

**Comment by peacewong** [comment]
I will fix this
