### ISSUE TITLE
[Feature] The ECM kill engine needs to be able to complete the kill of the yarn appid

### ISSUE THREAD

**Issue by peacewong** [apache/incubator-linkis#2228]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

The ECM kill engine needs to be able to complete the kill of the yarn appid to prevent the Yarn task from being killed due to the ‘kill -9’ of the ec
ECM kill引擎需要能够完成yarn appid的kill，防止ec 被kill -9导致的Yarn任务没有被kill的情况

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by CCweixiao** [comment]
I want to try to solve it.
