### ISSUE TITLE
[Bug] About Linkis Integrate Prometheus 

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis#2281]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### What happened + What you expected to happen

Linkis Integrate prometheus docs https://github.com/saLeox/incubator-linkis-website/blob/3a9ca762b9114950abcee2b5f50e740e7fa8928e/docs/deployment/involve_prometheus_into_linkis.md

1.  the same problem as https://github.com/prometheus/prometheus/issues/3670 , miss the groups: line at the top
2.  I try to make some eureka instance to down, but the alertrule seems not work fine 
![企业微信截图_16552111417802](https://user-images.githubusercontent.com/7869972/173582660-90cdc514-3e6a-4015-b4bf-47bf8a7512ac.png)
![企业微信截图_16552111292427](https://user-images.githubusercontent.com/7869972/173582646-1d4a4968-d2a4-4667-a0b4-c72dccb87bff.png)
3. About rule of `LinkisNodeDown`
```
  expr: last_over_time(up{job="linkis", application=~"LINKIS.*", application!="LINKIS-CG-ENGINECONN"}[1m])== 0

```
 `application=~"LINKIS.*` or  `application=~"LINKIS-*`?

### Relevent platform

none

### Reproduction script

none

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by saLeox** [comment]
Thanks for reporting the problem:
First issue get fixed;
For the second issue, `application` should be same as `job_name: linkis`, which define in `prometheus.yml`
For the third issue, `"*."` means `*` in the prometheus SQL

**Comment by saLeox** [comment]
latest document:
https://github.com/saLeox/incubator-linkis-website/blob/d9adfd4829424ca799dac873461628daea689390/docs/deployment/involve_prometheus_into_linkis.md
