### ISSUE TITLE
[Improvement] Add port check in install.sh

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis#2293]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### What happened + What you expected to happen

The current linkis installation and deployment does not check the ports used. After installation and deployment, if there is a port conflict, the service will fail to start.
It is recommended to check whether the configured port is occupied before installation and deployment. If the check fails, the installation fails.

----
当前linkis的安装部署脚本`assembly-combined-package/bin/install.sh`  没有对使用的端口做检查，安装部署后，如果存在端口冲突，会导致服务启动失败。
建议在安装部署前 对配置的端口是否被占用的检查，如果检查不通过，安装失败 

以及在安装linkis 管理台时 ，安装脚本`web/install.sh` 同样也进行管理台配置端口可用性检查 

### Relevent platform

none

### Reproduction script

none

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ruY9527** [comment]
Please assign it to me
