### ISSUE TITLE
[Bug] [Linkis1.1.3]LINKIS-CG-ENGINEPLUGIN service failed to start

### ISSUE THREAD

**Issue by gjy1043** [apache/incubator-linkis#2303]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-engineConnplugin

### What happened + What you expected to happen

After linkis1.1.3 is successfully deployed, it fails to start the LINKIS-CG-ENGINEPLUGIN service using the command given in the operation document, and the error is as follows：

![17](https://user-images.githubusercontent.com/26829024/174289608-2f4f85f2-b492-4350-981e-1e24b0c0f230.png)

### Relevent platform

Linkis1.1.3

### Reproduction script

1、Deploy linkis1.1.3 according to the installation and deployment documentation；
2、Start the service as given below：
Congratulations! You have installed Linkis 1.1.3 successfully, please use sh /data/Install/LinkisInstallTest/1.1.3_0616/sbin/linkis-start-all.sh to start it!

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by luoluo2001108** [comment]
Hi  ，Did you resolve this problem？

**Comment by peacewong** [comment]
> Hi ，Did you resolve this problem？

This is a publicservice service startup problem, not a bug
