### ISSUE TITLE
[Bug] For hive on tez tasks, the task cannot be ended correctly when canceled

### ISSUE THREAD

**Issue by barry8023** [apache/incubator-linkis#2321]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-engineConnplugin

### What happened + What you expected to happen

1. Set the hive engine to hive on tez
2. Enter script to execute hql
3. Cancel the task when the task is in the task running phase and there are multiple containers running on yarn
4. Observe that the status of engineconn is busy, and print the task completion status on yarn in the stdout of local engineconn.

1.设置hive引擎为为hive on tez
2.进入script执行hql
3.当任务处在任务运行阶段并在yarn上有多个container正在运行时取消任务
4.观察engineconn的状态为busy，本地engineconn的stdout中循环打印yarn上的task完成状态

### Relevent platform

linkis 1.0.1

### Reproduction script

none

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by barry8023** [comment]
I want to fix this issues，you can assign it to me

**Comment by peacewong** [comment]
> I want to fix this issues，you can assign it to me

ok
