### ISSUE TITLE
Excuse me, executing Python script reports an error

### ISSUE THREAD

**Issue by wjn0918** [apache/incubator-linkis#234]
ERROR Request engine failed, possibly due to insufficient resources or background process error(请求引擎失败，可能是由于资源不足或后台进程错误)!

![QQ截图20191230104149](https://user-images.githubusercontent.com/43337754/71566241-ffc77200-2af0-11ea-8454-b398596bb125.png)

**Comment by peacewong** [comment]
You can see the log error of python-engineManager

**Comment by wjn0918** [comment]
thanks,
there is also a problem,
when i run python with  import module
`
error code(错误码): 20071, error message(错误信息): can not use os moudle.
`

**Comment by peacewong** [comment]
Yes, we restrict the use of dangerous syntax, including os, sys and other modules

**Comment by jiaorenyu** [comment]
@wjn0918 May I ask how you solve this problem?
