### ISSUE TITLE
[Bug]  admin user cannot load all tables below the db

### ISSUE THREAD

**Issue by hunter-cloud09** [apache/incubator-linkis#2346]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-orchestrator

### What happened + What you expected to happen

When I set up the admin user and use it to log in to dss, it should load all the tables under a certain library, but only the tables it owns can be loaded

### Relevent platform

linkis1.1.3

### Reproduction script

wds.linkis.metadata.hive.db.admin=hadoop

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by mafeifeinb** [comment]
I want to fix this issues，you can assign it to me
