### ISSUE TITLE
scala/reflect/internal/Trees

### ISSUE THREAD

**Issue by 391518331** [apache/incubator-linkis#2365]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### What happened + What you expected to happen

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.750 s
[INFO] Finished at: 2022-06-29T17:00:57+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (scala-compile-first) on project linkis-common: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile failed: A
 required class was missing while executing net.alchim31.maven:scala-maven-plugin:3.2.0:compile: scala/reflect/internal/Trees
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>net.alchim31.maven:scala-maven-plugin:3.2.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/D:/apache-maven-3.6.3/repo/net/alchim31/maven/scala-maven-plugin/3.2.0/scala-maven-plugin-3.2.0.jar
[ERROR] urls[1] = file:/D:/apache-maven-3.6.3/repo/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
[ERROR] urls[2] = file:/D:/apache-maven-3.6.3/repo/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar
[ERROR] urls[3] = file:/D:/apache-maven-3.6.3/repo/org/sonatype/sisu/sisu-inject-bean/2.3.0/sisu-inject-bean-2.3.0.jar
[ERROR] urls[4] = file:/D:/apache-maven-3.6.3/repo/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[5] = file:/D:/apache-maven-3.6.3/repo/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar
[ERROR] urls[6] = file:/D:/apache-maven-3.6.3/repo/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[7] = file:/D:/apache-maven-3.6.3/repo/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[8] = file:/D:/apache-maven-3.6.3/repo/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[9] = file:/D:/apache-maven-3.6.3/repo/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[10] = file:/D:/apache-maven-3.6.3/repo/org/apache/maven/shared/maven-dependency-tree/1.2/maven-dependency-tree-1.2.jar
[ERROR] urls[11] = file:/D:/apache-maven-3.6.3/repo/org/apache/commons/commons-exec/1.1/commons-exec-1.1.jar
[ERROR] urls[12] = file:/D:/apache-maven-3.6.3/repo/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar
[ERROR] urls[13] = file:/D:/apache-maven-3.6.3/repo/org/codehaus/plexus/plexus-archiver/2.1/plexus-archiver-2.1.jar
[ERROR] urls[14] = file:/D:/apache-maven-3.6.3/repo/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[15] = file:/D:/apache-maven-3.6.3/repo/org/codehaus/plexus/plexus-io/2.0.2/plexus-io-2.0.2.jar
[ERROR] urls[16] = file:/D:/apache-maven-3.6.3/repo/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.jar
[ERROR] urls[17] = file:/D:/apache-maven-3.6.3/repo/org/apache/maven/doxia/doxia-sink-api/1.1.2/doxia-sink-api-1.1.2.jar
[ERROR] urls[18] = file:/D:/apache-maven-3.6.3/repo/org/apache/maven/doxia/doxia-logging-api/1.1.2/doxia-logging-api-1.1.2.jar
[ERROR] urls[19] = file:/D:/apache-maven-3.6.3/repo/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.jar
[ERROR] urls[20] = file:/D:/apache-maven-3.6.3/repo/com/typesafe/zinc/zinc/0.3.5/zinc-0.3.5.jar
[ERROR] urls[21] = file:/D:/apache-maven-3.6.3/repo/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.jar
[ERROR] urls[22] = file:/D:/apache-maven-3.6.3/repo/com/typesafe/sbt/incremental-compiler/0.13.5/incremental-compiler-0.13.5.jar
[ERROR] urls[23] = file:/D:/apache-maven-3.6.3/repo/org/scala-lang/scala-compiler/2.10.3/scala-compiler-2.10.3.jar
[ERROR] urls[24] = file:/D:/apache-maven-3.6.3/repo/org/scala-lang/scala-reflect/2.10.3/scala-reflect-2.10.3.jar
[ERROR] urls[25] = file:/D:/apache-maven-3.6.3/repo/com/typesafe/sbt/sbt-interface/0.13.5/sbt-interface-0.13.5.jar
[ERROR] urls[26] = file:/D:/apache-maven-3.6.3/repo/com/typesafe/sbt/compiler-interface/0.13.5/compiler-interface-0.13.5-sources.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : scala.reflect.internal.Trees
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :linkis-common

### Relevent platform

maven 3.3.6 windows  scala2.11.12

### Reproduction script

mvn clean package

### Anything else

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by ruY9527** [comment]
hi, is it convenient to tell you the version of linkis?
