### ISSUE TITLE
Log framework is not unified

### ISSUE THREAD

**Issue by tinyRookie** [apache/incubator-linkis#24]
In Linkis' source code, I have found that your log framework is not unified, in most places, you use slf4j + log4j2,  but you use just log4j somewhere. That's not a good code style for inspecting errors
在Linkis的源码中，我发现你的日志框架并不统一，大部分地方你用的是slf4j + log4j2，但你有的地方只用了log4j。 这不是检查错误的好代码风格

**Comment by yangzhiyue** [comment]
Thanks. It is a very suggesstive issue. We will unify the log framework soon.

**Comment by peacewong** [comment]
1.0 has been unified into log4j2
