### ISSUE TITLE
[Bug] build failed when build with spark3.2.1

### ISSUE THREAD

**Issue by zengxiangqi1031** [apache/incubator-linkis#2408]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-engineConnplugin

### What happened + What you expected to happen

1. **the bug is**:  Linkis could not be built with spark3.2.1,but success with spark3.0.0
2. **expected behavior** : linkis can be built successfully with spark3.2+
3. **more information is available here**:
![is](https://user-images.githubusercontent.com/11873336/177148291-47621d60-9fa9-43d9-9137-a9e5fda116e0.png)
:

### Relevent platform

centos7.6

### Reproduction script

just modified incubator-linkis/linkis-engineconn-plugins/engineconn-plugins/spark/pom.xml : 

scala.binary.version ->  2.12.15
spark.version  -> 3.2.1

and then run ：mvn clean install

### Anything else

none

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ruY9527** [comment]
Hello, is it convenient to tell what version or branch is used by linkis?
You can enter linkis-engineplugin-spark and execute mvn clean install to see if there are specific detailed errors.

**Comment by jackxu2011** [comment]
see #2186

**Comment by zengxiangqi1031** [comment]
> Hello, is it convenient to tell what version or branch is used by linkis? You can enter linkis-engineplugin-spark and execute mvn clean install to see if there are specific detailed errors.

version is : 1.1.3 
for more detailed errors please see the screenshot below:
![is1](https://user-images.githubusercontent.com/11873336/177164106-6a24868a-0db0-4bf2-9166-ae6d8a4b3cb4.png)

**here is my solution:**
In linkis's  SparkSQLHistoryParser.scala , change c.child to c.plan,it could be built successfully , because **views.scala** in spark3.2.1  use plan instead of child.  
![is2](https://user-images.githubusercontent.com/11873336/177165145-87eadc8f-a64c-4377-ad45-c991a07c9738.png)

the solution still has problem:  it just compatiable with higher spark version,like spark3.2+

**Comment by zengxiangqi1031** [comment]
> see #2186

yeah, i have seen this , but i found no more difference in SparkSQLHistoryParser.scala. Would you like to tell me,thanks a lot.

**Comment by zengxiangqi1031** [comment]
> see #2186

yeah, i have seen this , but i found no more difference in SparkSQLHistoryParser.scala. Would you like to tell me,thanks a lot.

**Comment by jackxu2011** [comment]
change the c.child to c.plan, the spark3.2.1 rename the field's name from child to plan
