### ISSUE TITLE
Integrated cdh5.16.2 issues

### ISSUE THREAD

**Issue by wjn0918** [apache/incubator-linkis#244]
Error report when running spark
运行spark报错
```
Caused by: java.lang.ClassNotFoundException: org.apache.htrace.Trace
```

Cause of the problem:
In the classpath of spark of CDH, / opt / cloudera / parcels / CDH / jars / htrace-core-3.0.4.jar was introduced. In this version, htrace was still org.htrace. In 3.1.0, it was already contributed to Apache and changed to org.apache.htrace.
[reference address]（ https://blog.csdn.net/leehbing/article/details/78479758 )

问题原因：
CDH的Spark的classpath中引入的是/opt/cloudera/parcels/CDH/jars/htrace-core-3.0.4.jar，而这个版本的时候，htrace还是org.htrace，而3.1.0的时候已经贡献给Apache了，改叫org.apache.htrace了。
[参考地址](https://blog.csdn.net/leehbing/article/details/78479758)

**Comment by wjn0918** [comment]
need add this dependency in you pom file
`
        
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>3.0</version>
        </dependency>
`

**Comment by wjn0918** [comment]
hadoop-common compile fail
error
`
Exception in thread "main" java.lang.AssertionError: assertion failed: org.apache.avro.reflect.Stringable
`
you need add this dependency in your

**Comment by wjn0918** [comment]
- hadoop-common 模块编译报错
`
Exception in thread "main" java.lang.AssertionError: assertion failed: org.apache.avro.reflect.Stringable  
`
解决：
添加依赖

  

        <dependency>  
            <groupId>org.apache.avro</groupId>
            <artifactId>avro</artifactId>
            <version>1.8.2</version>
        </dependency>

**Comment by wjn0918** [comment]
* gateway-core 模块编译出错

[ERROR] bad symbolic reference to org.eclipse.jetty.servlet encountered in class file 'BDPJettyServerHelper.class'.
[ERROR] Cannot access term servlet in package org.eclipse.jetty. The current classpath may be
[ERROR] missing a definition for org.eclipse.jetty.servlet, or BDPJettyServerHelper.class may have been compiled against a version that's
[ERROR] incompatible with the one found on the current classpath.

解决:
添加依赖：


        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
            <version>${jetty.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-webapp</artifactId>
            <version>${jetty.version}</version>
        </dependency>

**Comment by wjn0918** [comment]
> ```
> Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project
> ```

编译条件参数

```
mvn clean install -Dmaven.test.skip=true
```

**Comment by abcfyk** [comment]
请问你安装的是哪一个安装包？wedatasphere-linkis-0.9.2-dist-xxx
是 spark2.4.x，spark2.0-2.2，还是CDH5.7.6-spark2.0-2.2？？？
