### ISSUE TITLE
[Bug] linkis-bml VersionServiceImplTest fail

### ISSUE THREAD

**Issue by jackxu2011** [apache/incubator-linkis#2456]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-public-enhancements

### What happened + What you expected to happen

test fail

### Relevent platform

1.2.0

### Reproduction script

mvn clean install

### Anything else

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by CCweixiao** [comment]
是否有修改默认物料前缀路径？
Is there a way to modify the default material prefix path?

**Comment by jackxu2011** [comment]
finished
