### ISSUE TITLE
[Bug] DSS1.0.1 python code comment is not work

### ISSUE THREAD

**Issue by thinkliving2020** [apache/incubator-linkis#2482]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

web

### What happened + What you expected to happen

python code comment is not work.

new a python script on scriptis
eg:
#import sys
print('hello')

run the python script code, happen this error :
operation failed(操作失败) the reason(原因）：PythonCodeCheckException:errCode:20070, desc:can not use sys module, ip:xa250, port:9104, serviceKind:linkis-cg-entrance

![图片](https://user-images.githubusercontent.com/74002146/179440117-2a993a97-a3f0-4201-8777-35510a43fc2b.png)

### Relevent platform

firefox Browser 

### Reproduction script

import sys (commented)
print('hello')

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
You can configure wds.linkis.entrance.skip.auth=true to turn off dangerous syntax checking
