### ISSUE TITLE
[Bug] can not use useless module of scripts(dss1.0.1 python)

### ISSUE THREAD

**Issue by thinkliving2020** [apache/incubator-linkis#2485]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-entrance

### What happened + What you expected to happen

python code:
import sys
print('hello')

error info: can not use sys module
useless module shoud not be error
![图片](https://user-images.githubusercontent.com/74002146/179440250-53cec4c3-ba0b-4c73-b25b-1a485530be4a.png)

### Relevent platform

firefox 

### Reproduction script

python code:
import sys
print('hello')

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
You can configure wds.linkis.entrance.skip.auth=true to turn off dangerous syntax checking
