### ISSUE TITLE
[Bug] Some modules have wrong parent pom definition

### ISSUE THREAD

**Issue by wallezhang** [apache/incubator-linkis#2494]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons, linkis-cg-entrance, linkis-cg-manager, linkis-cg-engineConnplugin, linkis-cg-engineConnManager, linkis-cg-client, linkis-extensions, linkis-orchestrator, linkis-service-gateway, linkis-service-discovery

### What happened + What you expected to happen

I found that some sub-modules directly depend on the root pom of linkis and not specific the relative path. So that maven command would throw some fatal problems, like `Non-resolvable parent POM for org.apache.linkis:linkis-cs-common:1.1.3: org.apache.linkis:linkis:pom:1.1.3 was not found`.

Expect behavior: sub-module depend on its parent module directly. Don't reference across modules.

### Relevent platform

All

### Reproduction script

Any maven command would reproduce this issue

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Thank you, this needs to be unified

**Comment by wallezhang** [comment]
I'll fix it ASAP.

**Comment by wallezhang** [comment]
According to the discussion in #2497 . This issue will be closed.
