### ISSUE TITLE
[Bug] execute hql java.lang.NullPointerException

### ISSUE THREAD

**Issue by jindiao123** [apache/incubator-linkis#2500]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons, linkis-cg-entrance

### What happened + What you expected to happen

问题：在执行sql时，可以正常查询出hive表数据，在执行hql发生如下异常
![image](https://user-images.githubusercontent.com/48720305/179878648-69f67233-a09e-4c97-8614-570f39368eb6.png)

异常日志1：
[linkis-cg-engineconnmanager.log](https://github.com/apache/incubator-linkis/files/9145788/linkis-cg-engineconnmanager.log)
异常日志2：
[linkis-cg-linkismanager.log](https://github.com/apache/incubator-linkis/files/9145800/linkis-cg-linkismanager.log)
异常日志3：
[linkis-ps-publicservice.log](https://github.com/apache/incubator-linkis/files/9145815/linkis-ps-publicservice.log)

## 描述：
环境中`HADOOP_CONF_DIR`均已经配置并可以加载，但执行hql一直报`必须的环境变量 HADOOP_CONF_DIR 不存在`
![image](https://user-images.githubusercontent.com/48720305/179878737-dafb333a-a136-4c1b-a700-fff4bf03a4b6.png)

### Relevent platform

centos7.9、apache-linkis-1.1.1，hive1.2.1

### Reproduction script

select * from orders limit 100

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
There are prints in ecm and front-end logs that the HADOOP_CONF_DIR environment variable is not configured, you can configure export HADOOP_CONF_DIR=yourPath under the used bashrc
ecm和前端日志中有打印是HADOOP_CONF_DIR环境变量没有配置，你可以在用的bashrc下面配置下export HADOOP_CONF_DIR=yourPath
