### ISSUE TITLE
[Bug] Ambari2.7.5+hdp3.1.5 failed to start hive

### ISSUE THREAD

**Issue by ruY9527** [apache/incubator-linkis#2594]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-engineConnplugin

### What happened + What you expected to happen

env: Ambari2.7.5 + hdp3.1.5
       hadoop3.1.1，hive3.1.1，spark2, linkis1.1.2 + dss1.1.0
ERROR Job with execId-IDE_hadoop_hive_0 + subJobId : 39  execute failed,21304, Task is Failed,errorMsg: errCode: 12003 ,desc: 172-18-11-224:9101_2 Failed  to async get EngineNode AMErrorException: errCode: 30002 ,desc: ServiceInstance(linkis-cg-engineconn, 172-18-11-224:44466) ticketID:4998c507-014c-45c3-97d4-32809e1b843e 初始化引擎失败,原因: ServiceInstance(linkis-cg-engineconn, 172-18-11-224:44466): log dir: /appcom/tmp/hadoop/20220804/hive/4998c507-014c-45c3-97d4-32809e1b843e/logs,SessionNotRunning: TezSession has already shutdown.
 Application application_1659518236192_0031 failed 2 times due to AM Container for appattempt_1659518236192_0031_000002 exited with  exitCode: 1[](url)
log  link
[hdp_logs20220804.zip](https://github.com/apache/incubator-linkis/files/9258345/hdp_logs20220804.zip)

### Relevent platform

Version

### Reproduction script

show databases;
selec

### Anything else

can refer to the link  https://github.com/apache/incubator-linkis/pull/541#
清风 from wechat group 4

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by MrFengqin** [comment]
打包hive引擎时版本号需要跟环境上的hive版本一致启动失败可以使用

**Comment by MrFengqin** [comment]
1. 打包hive引擎时版本号需要跟环境上的hive版本一致；
2. 启动失败出现上面的问题使用yarn logs -applicationId application_1659518236192_0031查看yarnlog 日志；
3. 出现[ERROR] [main] |app.DAGAppMaster|: Error starting DAGAppMaster
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1358)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1339)
	at org.apache.tez.common.TezUtilsInternal.addUserSpecifiedTezConfiguration(TezUtilsInternal.java:94)
	at org.apache.tez.dag.app.DAGAppMaster.main(DAGAppMaster.java:2432)错误，
检查guava版本，guava版本没问题检查hive-exec.jar包，这是hive引擎包里的hive-exec.jar版本与环境上hive-exec版本不一致导致的，可以将环境上hive lib下相对应的jar包copy到hive引擎中解决这个问题

**Comment by MrFengqin** [comment]
1. 打包hive引擎时的版本号需要跟环境上的hive版本一致；
2. 启动失败 使用yarn logs -applicationId application_1659518236192_0031查看yarnlog日志；
3. 出现[ERROR] [main] |app.DAGAppMaster|: Error started DAGAppMaster
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
at org .apache.hadoop.conf.Configuration.set(Configuration.java:1358)
在 org.apache.hadoop.conf.Configuration.set(Configuration.java:1339)
在 org.apache.tez.common.TezUtilsInternal.addUserSpecifiedTezConfiguration(TezUtilsInternal .java:94)
at org.apache.tez.dag.app.DAGAppMaster.main(DAGAppMaster.java:2432) 错误
检查guava版本，guava版本没有问题检查hive-exec.jar包，这是hive引擎包里的hive-exec.jar版本与环境上hive-exec.jar 版本不一致出现的问题，可以将环境上hive/lib下相对应的jar包copy到 hive 引擎中解决这个问题

**Comment by MrFengqin** [comment]
1. 打包hive引擎时的版本号需要跟环境上的hive版本一致；
2. 启动失败，出现上述问题使用yarn logs -applicationId application_1659518236192_0031查看yarnlog日志；
3. 出现[ERROR] [main] |app.DAGAppMaster|: Error started DAGAppMaster
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
at org .apache.hadoop.conf.Configuration.set(Configuration.java:1358)
在 org.apache.hadoop.conf.Configuration.set(Configuration.java:1339)
在 org.apache.tez.common.TezUtilsInternal.addUserSpecifiedTezConfiguration(TezUtilsInternal .java:94)
at org.apache.tez.dag.app.DAGAppMaster.main(DAGAppMaster.java:2432) 错误
检查guava版本，guava版本没有问题检查hive-exec.jar包，这是hive引擎包里的hive-exec.jar版本与环境上hive-exec.jar版本不一致出现的问题，可以将环境上hive/lib下相对应的jar包copy到hive引擎中解决这个问题

**Comment by MrFengqin** [comment]
1. 打包hive引擎时的版本号需要跟环境上的hive版本一致；
2. 启动失败，出现上述问题使用yarn logs -applicationId application_1659518236192_0031查看yarnlog日志；
3. 出现[ERROR] [main] |app.DAGAppMaster|: Error started DAGAppMaster
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
at org .apache.hadoop.conf.Configuration.set(Configuration.java:1358)
在 org.apache.hadoop.conf.Configuration.set(Configuration.java:1339)
在 org.apache.tez.common.TezUtilsInternal.addUserSpecifiedTezConfiguration(TezUtilsInternal .java:94)
at org.apache.tez.dag.app.DAGAppMaster.main(DAGAppMaster.java:2432) 错误
检查guava版本，guava版本没有问题检查hive-exec.jar包，这是hive引擎包里的hive-exec.jar版本与环境上hive-exec.jar版本不一致出现的问题，可以将环境上hive/lib下相对应的jar包copy到hive引擎中解决这个问题
