### ISSUE TITLE
部署完Schedulis调度插件之后，页面访问静态资源404

### ISSUE THREAD

**Issue by wkzhu1** [apache/incubator-linkis#2609]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-extensions

### What happened + What you expected to happen

部署完Schedulis调度插件之后，页面访问静态资源404。
![错误现象](https://user-images.githubusercontent.com/42127625/183034267-aef2708e-1446-41d4-90bc-d51a313c5c96.jpg)
[配置文件&日志文件.zip](https://github.com/apache/incubator-linkis/files/9266771/default.zip)

### Relevent platform

谷歌浏览器

### Reproduction script

无

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by casionone** [comment]
静态资源接口都获取失败？ 后端接口请求正常？ 
感觉是不是有配置访问路径前缀？如:azkaban.default.servlet.path?

**Comment by ruY9527** [comment]
hi,in schedulis_0.7.0_web , change to absolute path, Restart the web service.such as:
web.resource.dir=/home/hadoop/application/schedulis/apps/schedulis_0.7.0_web/web/
-------------------------------------
将web.resource.dir修改为绝对路径,上面配置供参考,路径修改为自己真实情况路径.重启下web服务

**Comment by wkzhu1** [comment]
> ## 你好，在 schedulis_0.7.0_web 中，改成绝对路径，重启web服务。如：
> web.resource.dir=/home/hadoop/application/schedulis/apps/schedulis_0.7.0_web/web/
> 将web.resource.dir修改为绝对路径，配置供供，路径为自己的真实情况参考路径。重新启动下web服务

感谢，问题已得到解决
