### ISSUE TITLE
Problem with Linkis Quick Deployment

### ISSUE THREAD

**Issue by lorenzograziano** [apache/incubator-linkis#264]
Hi, I am following the Getting Started of Linkis.
All the prerequisites are satisfied. Build and installation of the package didn't give me any problems.
During the starting of the services

>     sh  ./bin/start-all.sh

I am getting this error message
>ERROR your linkis-metadata microservice is not start successful !!! ERROR logs as follows :
>...
>Caused by: java.lang.RuntimeException: Create hadoop configuration failed.

You can see the complete error message from the following screenshot.

嗨，我正在关注Linkis的入门。
满足所有前提条件。软件包的构建和安装没有给我带来任何问题。
在服务启动期间
>sh./bin/start-all.sh
我收到这个错误信息
>错误：linkis元数据微服务启动不成功！！！错误日志如下：
>...
>原因：java.lang.RuntimeException:创建hadoop配置失败。
您可以从下面的屏幕截图中看到完整的错误消息。

![image](https://user-images.githubusercontent.com/7315359/72335904-0264c280-36c0-11ea-8c9a-382558c4fc2a.png)

My current settings are the following:
- OS: Ubuntu 18.04
- Mysql 5.5.28
- Hadoop 2.7.2
- Hive 1.2.1

我当前的设置如下：
-操作系统：Ubuntu 18.04
-MySQL5.5.28版本
-Hadoop 2.7.2版
-Hive1.2.1

Moreover I can use hdfs, mysql and hive without any problems.
Thank you
此外，我可以使用hdfs，mysql和hive没有任何问题。
非常感谢。

**Comment by peacewong** [comment]
We will be compatible with more operating systems in subsequent versions

**Comment by lorenzograziano** [comment]
Thank you for the answer.
Where can I find the supported OS list?

**Comment by peacewong** [comment]
Supports most Unix systems
