### ISSUE TITLE
[Question] Not exists EngineConn(不存在的引擎).When I am executing the task of the sqoop node, an "not exists engineconn" error occurs

### ISSUE THREAD

**Issue by qieelann** [apache/incubator-linkis#2676]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Environment name and version:
    - hive-2.3.3
    - spark-2.4.3
    - jdk 1.8.0_312
    - hadoop 2.7.2
    - linkis 1.1.1
    - dss 1.1.0
    - exchangis 1.1.0
    

### Describe your questions

当我在执行sqoop节点的任务，将数据从MySQL导入hive时，dss web页面显示任务失败，linkis的报错信息如下(linkis-cg-linkismanager.log)：
When I am executing the task of the sqoop node and importing data from Mysql to hive, the DSS web page displays that the task failed. The error message of linkis is as follows:
```
2022-08-10 16:35:25.289 [INFO ] [qtp196218979-26                         ] o.a.l.s.u.ModuleUserUtils (64) [getProxyUserEntity] - user root proxy to null operation getEngineConn
2022-08-10 16:35:25.294 [ERROR] [qtp196218979-26                         ] o.a.l.s.r.SpringRestfulCatchAOP (71) [apply] - error code(错误码): 210003, error message(错误信息): Not exists EngineConn(不存在的引擎). org.apache.linkis.manager.am.exception.AMErrorException: errCode: 210003 ,desc: Not exists EngineConn(不存在的引擎) ,ip: slave4 ,port: 9101 ,serviceKind: linkis-cg-linkismanager
	at org.apache.linkis.manager.am.service.engine.DefaultEngineCreateService.getEngineNode(DefaultEngineCreateService.scala:133) ~[linkis-application-manager-1.1.1.jar:1.1.1]
	at org.apache.linkis.manager.am.restful.EngineRestfulApi.getEngineConn(EngineRestfulApi.java:139) ~[linkis-application-manager-1.1.1.jar:1.1.1]
	at org.apache.linkis.manager.am.restful.EngineRestfulApi$$FastClassBySpringCGLIB$$355728e5.invoke(<generated>) ~[linkis-application-manager-1.1.1.jar:1.1.1]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.15.RELEASE.jar:5.2.15.RELEASE]
```
**整理好的完整的linkis的日志如下：**
**The sorted and complete linkis logs are as follows:**
[sqoop_errors_logs2.zip](https://github.com/apache/incubator-linkis/files/9298587/sqoop_errors_logs2.zip)

我已经将sqoop引擎放到对应目录了：
![b39648c73e8833b23f7374ca6a35875](https://user-images.githubusercontent.com/104083632/183863373-f7e0c369-7df8-4af9-a9fe-deb3c58f5598.jpg)
 engin conn表中也有该数据：
![4e10bbff50b83aee2933a03958e8cf4](https://user-images.githubusercontent.com/104083632/183863474-44c9f730-f399-4db8-9db3-bba41b7a2859.jpg)

eg:
**/appcom/tmp/root/20220810/sqoop/c7569054-d863-4bdd-aaea-b69181e6df31/logs 如下：**
[appcom_sqoop_logs.zip](https://github.com/apache/incubator-linkis/files/9298594/appcom_sqoop_logs.zip)
这个日志里面提示`Unable to start embedded jetty server`

### Eureka service list

![image](https://user-images.githubusercontent.com/104083632/183863640-c4bfa740-14fd-4c77-bfe6-d8770ee1a26f.png)

### Some logs info or acctch file

The log file has been submitted in the text box of `Describe Your Questions` 
日志文件已提交在 `Describe your questions` 文本框

**Comment by casionone** [comment]
/appcom/tmp/root/20220810/sqoop/c7569054-d863-4bdd-aaea-b69181e6df31/logs 
can you upload this log files   
![image](https://user-images.githubusercontent.com/7869972/183958239-621ab722-3cd3-4f6a-b5cd-feae41907d76.png)

may be you can get sqoop engine resource  through  https://linkis.apache.org/zh-CN/blog/2022/04/15/how-to-download-engineconn-plugin

**Comment by qieelann** [comment]
> /appcom/tmp/root/20220810/sqoop/c7569054-d863-4bdd-aaea-b69181e6df31/logs can you upload this log files ![image](https://user-images.githubusercontent.com/7869972/183958239-621ab722-3cd3-4f6a-b5cd-feae41907d76.png)
> 
> may be you can get sqoop engine resource through https://linkis.apache.org/zh-CN/blog/2022/04/15/how-to-download-engineconn-plugin

@casionone  thans for you reply!
/appcom/tmp/root/20220810/sqoop/c7569054-d863-4bdd-aaea-b69181e6df31/logs
this log file has been uploaded, look:
![image](https://user-images.githubusercontent.com/104083632/184306597-859e52a8-2748-4c21-a154-770735e1d22b.png)

I use the Exchangeis installation package and SQOOP engine package provided in Exchangeis Release, here: 
![image](https://user-images.githubusercontent.com/104083632/184307552-f3cd1737-39c9-4cc6-bc72-f9249e3daf06.png)

I will try the Sqoop Engine Resource under the Linkis 1.1.1 branch.

**Comment by casionone** [comment]
> /appcom/tmp/root/20220810/sqoop/c7569054-d863-4bdd-aaea-b69181e6df31/logs
> this log file has been uploaded,
I download and unzip 
but not found   /appcom/tmp/root/20220810/sqoop/c7569054-d863-4bdd-aaea-b69181e6df31/logs

**Comment by qieelann** [comment]
> > /appcom/tmp/root/20220810/sqoop/c7569054-d863-4bdd-aaea-b69181e6df31/logs
> > this log file has been uploaded,
> > I download and unzip
> > but not found   /appcom/tmp/root/20220810/sqoop/c7569054-d863-4bdd-aaea-b69181e6df31/logs

@casionone 

![image](https://user-images.githubusercontent.com/104083632/184782509-677574a3-d90a-4163-bd7b-5f035d70ba03.png)
sorry, I should make it clear。The  above compressed file  already contains the detailed file of the corresponding log。
But I sorted out a more complete log below， please check it.
[appcom_tmp_root_20220810_sqoop_logs.tar.gz](https://github.com/apache/incubator-linkis/files/9347478/appcom_tmp_root_20220810_sqoop_logs.tar.gz)
