### ISSUE TITLE
[linkis-bml-client]Scala code format alarm clear

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis#2703]
scala code format alarm clearing task
Adjust the code format and clear the warn alarm in the idea

The scala code formatting rules configuration file is located in `scalastyle-config.xml`
You can check for format exceptions by running the command `mvn scalastyle:check` under the module

Module `linkis-public-enhancements/linkis-bml/linkis-bml-client`

-----

scala 代码格式告警清除任务 
调整代码格式，清除idea中的warn告警

scala 代码格式规则配置文件位于  `scalastyle-config.xml`
你可以通过模块下 运行命令`mvn scalastyle:check ` 检查格式异常

模块 `linkis-public-enhancements/linkis-bml/linkis-bml-client`

![企业微信截图_1660216077725](https://user-images.githubusercontent.com/7869972/184121660-798f1879-2f53-42f3-ba77-3de2908d48b0.png)

**Comment by ruY9527** [comment]
Hi! Can I work on this issue?
