### ISSUE TITLE
[ linkis-hadoop-common]Scala code format alarm clear

### ISSUE THREAD

**Issue by binbinCheng** [apache/incubator-linkis#2780]
Scala code format alarm clear[linkis-hadoop-common]
---
scala code format alarm clearing task
Adjust the code format and clear the warn alarm in the idea

The scala code formatting rules configuration file is located in scalastyle-config.xml
You can check for format exceptions by running the command mvn scalastyle:check under the module

Module linkis-commons/linkis-hadoop-common

--- 

scala 代码格式告警清除任务
调整代码格式，清除idea中的warn告警

scala 代码格式规则配置文件位于 scalastyle-config.xml
你可以通过模块下 运行命令mvn scalastyle:check 检查格式异常

模块 linkis-commons/linkis-hadoop-common

![image](https://user-images.githubusercontent.com/106590848/184779339-64f53cb1-32e4-4f7a-882f-781cdc8fe22f.png)

 | class | path| 
| ------------- |------------- |
 | HDFSUtils| org.apache.linkis.hadoop.common.utils.HDFSUtils|

**Comment by ruY9527** [comment]
see <parameter name="maxLineLength"><![CDATA[200]]></parameter> in scalastyle-config.xml
Adjust 100 to 200, it doesn't prompt
