### ISSUE TITLE
[Question] When logging in to Scriptis, the root directory does not exist

### ISSUE THREAD

**Issue by Andywli** [apache/incubator-linkis#2798]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....1

### Describe your questions

[工作空间]登录Scriptis时报根目录不存在，存在工作空间和HDFS两个跟目录:错误信息: 在登录进入后，前端弹出如下信息(用户本地目录不存在，请联系添加)

[Workspace] When logging in to Scriptis, the root directory does not exist, but there are two directories: workspace and HDFS: Error message: After logging in, the following message pops up on the front end (the user's local directory does not exist, please contact to add)

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/incubator-linkis/files/9219529/yarn-error.log)

**Comment by Andywli** [comment]
解决方案:
	a. 确认linkis-ps-publicservice的conf目录下linkis.properties参数：wds.linkis.filesystem.root.path=file:///tmp/linkis/ 是不是file://开头。
	b. 确认/tmp/linkis目录下是不是有用户目录，这里的用户是指前端登录用户，比如hadoop用户登录，那么要建立：/tmp/linkis/hadoop目录，如果目录存在确认目录权限登录用户可以操作，如果还是不行可以参考publicservice的报错，错误会说明权限还是路径问题

solution:
a. Confirm that the linkis.properties parameter in the conf directory of linkis-ps-publicservice: wds.linkis.filesystem.root.path=file:///tmp/linkis/ starts with file://.
b. Confirm whether there is a user directory in the /tmp/linkis directory. The user here refers to the front-end login user. For example, if the hadoop user logs in, then create the /tmp/linkis/hadoop directory. If the directory exists, confirm the directory permission. The login user can Operation, if it still doesn't work, you can refer to the error report of publicservice, the error will indicate permission or path problem

**Comment by jackxu2011** [comment]
1.2.0 有一个自动创建工作空间目录的参数， linkis.workspace.filesystem.auto.create， 默认是关闭的。可以打开
