### ISSUE TITLE
[executor-core]Scala code format alarm clear

### ISSUE THREAD

**Issue by binbinCheng** [apache/incubator-linkis#2815]
Scala code format alarm clear[executor-core]
---
scala code format alarm clearing task
Adjust the code format and clear the warn alarm in the idea

The scala code formatting rules configuration file is located in scalastyle-config.xml
You can check for format exceptions by running the command mvn scalastyle:check under the module

Module  linkis-computation-governance/linkis-engineconn/linkis-engineconn-executor/executor-core

--- 

scala 代码格式告警清除任务
调整代码格式，清除idea中的warn告警

scala 代码格式规则配置文件位于 scalastyle-config.xml
你可以通过模块下 运行命令mvn scalastyle:check 检查格式异常

模块  linkis-computation-governance/linkis-engineconn/linkis-engineconn-executor/executor-core

![image](https://user-images.githubusercontent.com/106590848/184851266-f885d51d-15c0-4c0e-9e47-f97e113ff4fb.png)

 | class | path| 
| ------------- |------------- |
 | ManagerService| org.apache.linkis.engineconn.executor.service.ManagerService| 
| ExecutorListenerBusContext| org.apache.linkis.engineconn.executor.listener.ExecutorListenerBusContext|
| EngineConnAsyncListenerBus| org.apache.linkis.engineconn.executor.listener.EngineConnAsyncListenerBus|

**Comment by ruY9527** [comment]
Can I finish it? Branch at dev-1.3.0
