### ISSUE TITLE
[linkis-engineconn-plugin-core]Scala code format alarm clear 

### ISSUE THREAD

**Issue by binbinCheng** [apache/incubator-linkis#2816]
Scala code format alarm clear[linkis-engineconn-plugin-core]
---
scala code format alarm clearing task
Adjust the code format and clear the warn alarm in the idea

The scala code formatting rules configuration file is located in scalastyle-config.xml
You can check for format exceptions by running the command mvn scalastyle:check under the module

Module linkis-computation-governance/linkis-engineconn/linkis-engineconn-plugin-core

--- 

scala 代码格式告警清除任务
调整代码格式，清除idea中的warn告警

scala 代码格式规则配置文件位于 scalastyle-config.xml
你可以通过模块下 运行命令mvn scalastyle:check 检查格式异常

模块 linkis-computation-governance/linkis-engineconn/linkis-engineconn-plugin-core

![image](https://user-images.githubusercontent.com/106590848/184851894-201111e2-0967-4e71-ae70-5fbd9670dc5c.png)

 | class | path| 
| ------------- |------------- |
 | AbstractEngineResourceFactory| org.apache.linkis.manager.engineplugin.common.resource.AbstractEngineResourceFactory| 
| EngineConnPluginInfo| org.apache.linkis.manager.engineplugin.common.loader.entity.EngineConnPluginInfo|
|JavaProcessEngineConnLaunchBuilder|org.apache.linkis.manager.engineplugin.common.launch.process.JavaProcessEngineConnLaunchBuilder|
| EngineConnPluginErrorCode|org.apache.linkis.manager.engineplugin.common.exception.EngineConnPluginErrorCode|
| EnvConfiguration| org.apache.linkis.manager.engineplugin.common.conf.EnvConfiguration|

**Comment by ruY9527** [comment]
Can I finish it? Branch at dev-1.3.0
