### ISSUE TITLE
[hive]Scala code format alarm clear

### ISSUE THREAD

**Issue by binbinCheng** [apache/incubator-linkis#2835]
Scala code format alarm clear[hive]
---
scala code format alarm clearing task
Adjust the code format and clear the warn alarm in the idea

The scala code formatting rules configuration file is located in scalastyle-config.xml
You can check for format exceptions by running the command mvn scalastyle:check under the module

Module linkis-engineconn-plugins/hive

--- 

scala 代码格式告警清除任务
调整代码格式，清除idea中的warn告警

scala 代码格式规则配置文件位于 scalastyle-config.xml
你可以通过模块下 运行命令mvn scalastyle:check 检查格式异常

模块 linkis-engineconn-plugins/hive

![image](https://user-images.githubusercontent.com/106590848/185058836-16f57089-7165-4fb7-a5ee-ac0c0f3a0be5.png)

 | class | path| 
| ------------- |------------- |
| HiveProgressHelper|org.apache.linkis.engineplugin.hive.progress.HiveProgressHelper| 
| HiveAddMetaTableNameHook|org.apache.linkis.engineplugin.hive.hook.HiveAddMetaTableNameHook|
| HiveEngineConnFactory| org.apache.linkis.engineplugin.hive.creation.HiveEngineConnFactory|

**Comment by huangxiaopingRD** [comment]
I want to fix this issues, thans

**Comment by casionone** [comment]
> I want to fix this issues, thanks

Ok very welcome
Can you add your wechat friends? My wechat account:`casinoxia`
