### ISSUE TITLE
[linkis-metadata]Scala code format alarm clear

### ISSUE THREAD

**Issue by binbinCheng** [apache/incubator-linkis#2862]
Scala code format alarm clear[linkis-metadata]
---
scala code format alarm clearing task
Adjust the code format and clear the warn alarm in the idea

The scala code formatting rules configuration file is located in scalastyle-config.xml
You can check for format exceptions by running the command mvn scalastyle:check under the module

Module linkis-public-enhancements/linkis-datasource/linkis-metadata

--- 

scala 代码格式告警清除任务
调整代码格式，清除idea中的warn告警

scala 代码格式规则配置文件位于 scalastyle-config.xml
你可以通过模块下 运行命令mvn scalastyle:check 检查格式异常

模块 linkis-public-enhancements/linkis-datasource/linkis-metadata

![image](https://user-images.githubusercontent.com/106590848/185283577-ed7adfca-4372-4019-82c8-07290b95f25d.png)

 | class | path| 
| ------------- |------------- |
| ScalaDDLCreator|org.apache.linkis.metadata.ddl.ScalaDDLCreator| 
| ImportDDLCreator|org.apache.linkis.metadata.ddl.ImportDDLCreator|

**Comment by ruY9527** [comment]
I want to handle this issue
