### ISSUE TITLE
 Linkis  support  Flink computing engine

### ISSUE THREAD

**Issue by hanfeio** [apache/incubator-linkis#29]
description:Linkis support for Flink Feature，This includes FlinkSQL(StreamSQL and Batch SQL) and scala support.Hope to build on Flink1.9 as a release iteration.
描述：Linkis 对 Flink Feature 的支持，包括 FlinkSQL（StreamSQL 和 Batch SQL）和 scala 支持。希望在 Flink1.9 上构建作为发布迭代。

**Comment by wushengyeyouya** [comment]
This is a great issue, we are currently considering implementation and invite you to join us.

**Comment by runc** [comment]
support flink will be help linkis better!!! hope to come soon

**Comment by oceanhaiyang** [comment]
接入其他计算引擎的文档

https://github.com/WeBankFinTech/Linkis/blob/master/docs/zh_CN/ch3/Linkis%E5%A6%82%E4%BD%95%E6%8E%A5%E5%85%A5%E6%96%B0%E7%9A%84%E5%BA%95%E5%B1%82%E8%AE%A1%E7%AE%97%E5%AD%98%E5%82%A8%E5%BC%95%E6%93%8E.md

**Comment by orisonchan** [comment]
Hello team everyone, I think maybe Linkis can support Flink 1.10 Release.

**Comment by JohnTao** [comment]
Hello team everyone, I think maybe Linkis can support Flink 1.13 Release.

**Comment by peacewong** [comment]
Flink has been supported since Linkis 1.0
