### ISSUE TITLE
linkis初始化引擎-权限问题

### ISSUE THREAD

**Issue by biandou1313** [apache/incubator-linkis#2900]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-orchestrator

### Steps to reproduce

前置：我们采用hadoop账号作为唯一账号
1、centos7： hadoop对应uid:1001
2、容器内：hadoop对应uid 1002
执行hive sql时，初始化引擎失败

772d70c5-fdb7-4a02-95f3-b88c90728ccf:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
681d4a67-5975-4893-8773-f557f6017c69:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
d63a8dbc-5b3d-4e22-91dd-d92764f07a69:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
9fdd39b3-cb05-4823-9ffa-ee56b0bb4119:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
9c079096-3bf6-4d20-8f13-ede7763eaa45:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
ea6043db-1f41-49e0-b07f-788f1712cc62:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
5822e535-ba0f-4fa6-910d-22e275a1fda2:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
60b156d0-7aba-4966-bea0-5b67e582cb6f:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
334ec38d-5fc4-492f-934c-44f02b711c8d:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
2b04a956-d00e-41cf-ad4a-564e65d5a485:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
97bb02b9-9095-442c-a4e0-fbd24e469390:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
dd9fbca1-706e-4915-afa4-e086d4c6b499:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
a6f8689d-652f-407b-84cd-cb0755e60073:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
aaabbf87-1d44-41f7-98e5-de772ebb15ba:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
30deb495-ac89-45d6-96c5-16a53668e784:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
be4e3e29-1617-4906-9844-12dc9bc66cf0:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
e14343b6-1883-4b91-8e4b-c7f4fd05b5a6:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
7ea583c6-2dcf-40a6-a6fc-049b38cf6d4c:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
45ec8aea-8dad-4f35-a7fa-712c38ad926f:sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set

### Expected behavior

解决思路：
chmod 0440 /etc/sudo.conf
chmod 0440 /etc/sudoers
chown root:root /etc/sudo.conf
chown root:root /etc/sudoers
chown root:root /usr/libexec/sudo/sudoers.so
chown root:root /usr/bin/sudo
问题：
执行以上命令赋权，执行一次之后，没问题，再执行一次 就出现问题

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by utopianet** [comment]
建议尝试容器内配置hadoop免密sudo权限。参考链接：
It is recommended to try to configure Hadoop secret free sudo permission in the container. Reference link:
https://linkis.apache.org/zh-CN/docs/1.2.0/deployment/quick-deploy/
