### ISSUE TITLE
[Question] There is no publish as data API button in scripts. There are buttons when I replace various compile front-end versions, but there are other errors

### ISSUE THREAD

**Issue by qieelann** [apache/incubator-linkis#2949]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

**Environment name and version:**
- hive-2.3.3
- spark-2.4.3
- jdk 1.8.0_312
- hadoop 2.7.2
- linkis 1.1.1
- dss 1.1.0
- exchangis 1.1.0

**Describe your questions:**
我用的是dss-linkis一键安装包，当我打开scriptis的文件时，编辑框上没有“发布为数据API”按钮。
I use the DSS-linkis one click installation package，When I open the scriptis file, there is no "publish as data API" button on the edit box.
like this:
![223e540f42423e470dbcd05d8515b79](https://user-images.githubusercontent.com/104083632/186092964-2d1a6318-104a-4575-abc4-ebdd68a34ce1.jpg)
![readme](https://user-images.githubusercontent.com/104083632/186092376-77c14de2-6a4e-4238-9cab-78171f7d46c4.png)

我已经在数据库中给了登录用户所有的角色，在权限管理中给了所有的权限。
I have given all the roles of the login user in the database and all the permissions in the permission management.
like this:
![image](https://user-images.githubusercontent.com/104083632/186093480-1b7381ea-fc3a-4785-a0e9-06a75fac80be.png)

所以我重新编译了dss master分支的前端文件，也编译了dss 1.1.0分支按pr修改的前端文件，结果均是 按钮出现了，但是双击工作流中的sqoop节点和qualitis节点 出现了后台接口异常错误。
So I recompiled the front-end file of the DSS master branch ，also compiled the front-end file modified by PR of the DSS 1.1.0 branch, As a result, the buttons appear, but the background interface exception error occurs when you double-click the sqoop node and the quality node in the workflow.
like this:
![更换前端编译文件dist后双击sqoop节点接口异常截图](https://user-images.githubusercontent.com/104083632/186094216-aa615243-08ac-4adb-a1ef-65d03fc8a9ef.png)

pr link:
https://github.com/WeBankFinTech/DataSphereStudio/commit/1dc9d99648e9f78b2dfb4776df4b9f46ef530c8a

Logs and related files are in the logs box behind, I have sorted it out.

### Describe your questions

Look your environment text box , I wrote there.

### Eureka service list

eureka list :
![image](https://user-images.githubusercontent.com/104083632/186095184-19deb1ba-6c18-478c-ba4e-5bc2815cb494.png)

### Some logs info or acctch file

相关日志文件在这里：
The relevant log files are here：

[scriptis无发布为数据api按钮，替换各种编译前端版本按钮有了，但是有其它错误.zip](https://github.com/apache/incubator-linkis/files/9400221/scriptis.api.zip)

**Comment by casionone** [comment]
@
zqburde @ruY9527 Help with this question

**Comment by ruY9527** [comment]
Hello, it's convenient to check the corresponding error through F12 when clicking the corresponding sqoop and quality components
Pass at the same time http://ip:port/api/rest_j/v1/dss/workflow/getAppConnNodeUrl Check whether the jump path is correct
The logs of the exchangis and quality components have been checked for errors
----------------------------------------------------------
你好,方便点击对应的sqoop和qualitis组件的时候,通过f12,查看下对应的错误
同时通过 http://ip:port/api/rest_j/v1/dss/workflow/getAppConnNodeUrl 查看跳转的路径是否正确
已经检查exchangis和qualitis组件的log是否有错误

**Comment by qieelann** [comment]
@ruY9527 您好，我在nginx中复制了一份conf文件，修改了端口和前端文件路径，等于现在有两份指向不同前端端口和dist目录的前端文件，然后启动dss, 有发布服务按钮但是sqoop节点双击报错的dss前端端口是8086， 没有发布服务按钮，且为dss_linkis一键安装包自己生成的那份dss前端端口是8085。
两者双击sqoop节点的浏览器F12如下：进入sqoop节点显示后台接口异常的那份前端文件出现400错误。
![image](https://user-images.githubusercontent.com/104083632/186850414-b6a7c0fc-0509-49e5-b6a7-8b7074f1d0dc.png)
![image](https://user-images.githubusercontent.com/104083632/186850704-fb1ce1be-a557-4565-9f2e-6ce04f2e4c3b.png)

分别跳转您说的那个路径结果如下：
![image](https://user-images.githubusercontent.com/104083632/186851039-b6d2636a-fc27-453c-a869-bbd2f0faafa0.png)

在此测试期间tail -F exchangis log  并无错误日志。

**Comment by qieelann** [comment]
@ruY9527 
在此测试期间产生的tail -F exchangis log只有几条，如下：
![image](https://user-images.githubusercontent.com/104083632/186852176-a31361f3-7849-4eea-a1d5-d7eae9275a93.png)
