### ISSUE TITLE
Add junit5 test code for module [engineconn-plugins/python]

### ISSUE THREAD

**Issue by ruY9527** [apache/incubator-linkis#3044]
### Add junit5 test code for module [engineconn-plugins/python]
- Module: linkis-engineplugin-python
- Location:linkis-engineconn-plugins/linkis-engineplugin-python
- Task status:✗(unfinished)/ ✓(finished)
- Test code guide:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- Test code example: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test
--
- 模块名: linkis-engineplugin-python
- 代码位置:linkis-engineconn-plugins/linkis-engineplugin-python
- 任务状态:✗(unfinished)/ ✓(finished)
- 单测编写指引:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- 参考样例: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test

| Task status| Class | Type| Level of Difficulty | Note |
| :------ | :------ | :------: | :------: | :------: |
|   ✗         |org.apache.linkis.manager.engineplugin.python.exception| Exception | normal |  |
|   ✗         |org.apache.linkis.manager.engineplugin.python.executor.PythonEngineConnExecutor| Executor| normal |  |
|   ✗         |org.apache.linkis.manager.engineplugin.python.executor.PythonSession| Session| normal |  |
|   ✗         |org.apache.linkis.manager.engineplugin.python.factory.PythonEngineConnFactory| Factory| normal |  |
|   ✗         |org.apache.linkis.manager.engineplugin.python.hook.PythonVersionEngineHook| Hook| normal |  |
|   ✗         |org.apache.linkis.manager.engineplugin.python.utils.*| utils| normal |  |

**Comment by QuintinTao** [comment]
I want to try it

**Comment by QuintinTao** [comment]
#2924 #2904 
I finished test cases for python.

**Comment by ruY9527** [comment]
see https://github.com/apache/incubator-linkis/pull/2924 https://github.com/apache/incubator-linkis/pull/2904
