### ISSUE TITLE
Add junit5 test code for module [engineconn-plugins/shell]

### ISSUE THREAD

**Issue by ruY9527** [apache/incubator-linkis#3046]
### Add junit5 test code for module [engineconn-plugins/shell]
- Module: linkis-engineplugin-shell
- Location:linkis-engineconn-plugins/linkis-engineplugin-shell
- Task status:✗(unfinished)/ ✓(finished)
- Test code guide:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- Test code example: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test
--
- 模块名: linkis-engineplugin-shell
- 代码位置:linkis-engineconn-plugins/linkis-engineplugin-shell
- 任务状态:✗(unfinished)/ ✓(finished)
- 单测编写指引:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- 参考样例: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test

| Task status| Class | Type| Level of Difficulty | Note |
| :------ | :------ | :------: | :------: | :------: |
|   ✗         |org.apache.linkis.manager.engineplugin.shell.common.ShellEngineConnPluginConst| Const | normal |  |
|   ✗         |org.apache.linkis.manager.engineplugin.shell.exception.NoCorrectUserException| Exception | normal |  |
|   ✗         |org.apache.linkis.manager.engineplugin.shell.executor.ErrorStreamReaderThread| Thread | normal |  |
|   ✗         |org.apache.linkis.manager.engineplugin.shell.executor.ShellEngineConnExecutor| Executor | normal |  |
|   ✗         |org.apache.linkis.manager.engineplugin.shell.executor.YarnAppIdExtractor| Executor | normal |  |
|   ✗         |org.apache.linkis.manager.engineplugin.shell.executor.YarnAppIdExtractor| Executor | normal |  |

**Comment by QuintinTao** [comment]
I want to try this.

**Comment by QuintinTao** [comment]
[https://github.com/apache/incubator-linkis/pull/2654](url)
[https://github.com/apache/incubator-linkis/pull/2620](url)
I finished test cases for shell engine.

**Comment by QuintinTao** [comment]
#2620 #2654 
I finished test cases for shell engine.

**Comment by ruY9527** [comment]
see https://github.com/apache/incubator-linkis/pull/2620 https://github.com/apache/incubator-linkis/pull/2654
