### ISSUE TITLE
Failed  to async get EngineNode AMErrorException: errCode: 30002 ,desc: ServiceInstance(linkis-cg-engineconn, emr-header-3.cluster-254539:21633) ticketID:7b2b80ad-25b3-47bc-90c1-ff95d8bf8f91 初始化引擎失败

### ISSUE THREAD

**Issue by 2018yinjian** [apache/incubator-linkis#3068]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.1
- Environment name and version:
    - 阿里E-Mapreduce
    - hadoop-3.2.1
    - hive-3.1.2
    - spark-2.4.7
    - scala-2.11.12
    - jdk-1.8.0_252
    - linkis-1.1.1

### Describe your questions

ERROR Job with execId-LINKISCLI_root_hive_0 + subJobId : 123  execute failed,21304, Task is Failed,errorMsg: errCode: 12003 ,desc: emr-header-3.cluster-254539:9101_24 Failed  to async get EngineNode AMErrorException: errCode: 30002 ,desc: ServiceInstance(linkis-cg-engineconn, emr-header-3.cluster-254539:35433) ticketID:47887b78-a106-4988-b8a3-e401ca3cf4a8 初始化引擎失败,原因: ServiceInstance(linkis-cg-engineconn, emr-header-3.cluster-254539:35433): log dir: /appcom/tmp/root/20220826/hive/47887b78-a106-4988-b8a3-e401ca3cf4a8/logs,NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V ,ip: emr-header-3.cluster-254539 ,port: 9101 ,serviceKind: linkis-cg-linkismanager ,ip: emr-header-3.cluster-254539 ,port: 9104 ,serviceKind: linkis-cg-entrance

根据提示信息，排查的guava依赖包版本如下：
/appcom/Install/AzkabanInstall/schedulis_0.7.0_web/lib/guava-28.1-jre.jar
/appcom/Install/AzkabanInstall/schedulis_0.7.0_exec/lib/guava-28.1-jre.jar
/appcom/Install/AzkabanInstall/schedulis_0.7.0_exec/plugins/jobtypes/linkis/lib/guava-30.0-jre.jar
/appcom/tmp/engineConnPublickDir/7d0abc88-59c5-415e-9f03-0dd3df63f869/v000002/lib/guava-19.0.jar
/opt/DataSphere/dss/lib/dss-orchestrator/dss-workflow-server/guava-20.0.jar
/opt/DataSphere/dss/lib/dss-orchestrator/dss-flow-execution-server/guava-30.0-jre.jar
/opt/DataSphere/dss/lib/dss-apps/dss-scriptis-server/guava-30.0-jre.jar
/opt/DataSphere/dss/lib/dss-apps/dss-apiservice-server/guava-30.0-jre.jar
/opt/DataSphere/dss/lib/dss-framework/dss-framework-project-server/guava-30.0-jre.jar
/opt/DataSphere/dss/lib/dss-framework/dss-framework-orchestrator-server/guava-20.0.jar
/opt/DataSphere/dss/lib/dss-commons/guava-30.0-jre.jar
/opt/DataSphere/dss/dss-appconns/datachecker/lib/guava-30.0-jre.jar
/opt/DataSphere/dss/dss-appconns/eventchecker/lib/guava-20.0.jar
/opt/DataSphere/dss/dss-appconns/sendemail/lib/guava-30.0-jre.jar
/opt/DataSphere/dss/dss-appconns/dolphinscheduler/lib/guava-28.2-android.jar
/opt/DataSphere/dss/dss-appconns/schedulis/lib/guava-30.0-jre.jar
/opt/DataSphere/linkis/lib/linkis-spring-cloud-services/linkis-mg-gateway/guava-30.0-jre.jar
/opt/DataSphere/linkis/lib/linkis-commons/public-module/guava-30.0-jre.jar
/opt/DataSphere/linkis/lib/linkis-engineconn-plugins/spark/dist/v2.4.7/lib/guava-19.0.jar
/opt/apps/ecm/service/hive/3.1.2-hadoop3.1-1.1.2/package/apache-hive-3.1.2-hadoop3.1-1.1.2-bin/lib/guava-19.0.jar
/opt/apps/ecm/service/kafka/2.12-2.4.1-1.0.0/package/kafka_2.12-2.4.1-1.0.0/ext-libs/guava-20.0.jar
/opt/apps/ecm/service/kafka/2.12-2.4.1-1.0.0/package/kafka_2.12-2.4.1-1.0.0/libs/guava-20.0.jar
/opt/apps/ecm/service/knox/1.1.0-4.4.2/package/knox-1.1.0-4.4.2/dep/guava-11.0.2.jar
/opt/apps/ecm/service/hbase/2.3.4-1.0.0/package/hbase-2.3.4-1.0.0/lib/guava-27.0-jre.jar
/opt/apps/ecm/service/livy/0.7.1-hadoop3-1.0.0/package/livy-0.7.1-hadoop3-1.0.0-incubating-bin/jars/guava-11.0.2.jar
/opt/apps/ecm/service/impala/3.4.0-1.0.4/package/impala-3.4.0-1.0.4/lib/guava-14.0.1.jar
/opt/apps/ecm/service/pig/0.14.0/package/pig-0.14.0/lib/guava-11.0.jar
/opt/apps/ecm/service/hadoop/3.2.1-1.1.0/package/hadoop-3.2.1-1.1.0/share/hadoop/common/lib/guava-19.0.jar
/opt/apps/ecm/service/hadoop/3.2.1-1.1.0/package/hadoop-3.2.1-1.1.0/share/hadoop/hdfs/lib/guava-19.0.jar
hive-exec的jar包版本如下：
/etc/ecm/hive-conf-3.1.2-hadoop3.1-1.1.2/hive-exec-log4j.properties
/appcom/tmp/engineConnPublickDir/c93125da-87e1-4d2f-a012-17fec03143b0/v000002/lib/hive-exec-3.1.2.jar
/appcom/tmp/engineConnPublickDir/c93125da-87e1-4d2f-a012-17fec03143b0/v000001/lib/hive-exec-3.1.2.jar
/opt/DataSphere/linkis/lib/linkis-public-enhancements/linkis-ps-metadatamanager/service/hive/hive-exec-3.1.2.jar
/opt/DataSphere/linkis/lib/linkis-engineconn-plugins/hive/dist/v3.1.2/lib/hive-exec-3.1.2.jar
/opt/tempLib/hive-exec-3.1.2.jar
/opt/tempLib/hive-exec-2.3.3.jar
/opt/apps/ecm/service/ranger/2.1.0-1.0.3/package/ranger-2.1.0-1.0.3/ranger-2.1.0-1.0.3-admin/ews/webapp/WEB-INF/classes/ranger-plugins/hive/hive-exec-3.1.2.jar
/opt/apps/ecm/service/hive/3.1.2-hadoop3.1-1.1.2/package/apache-hive-3.1.2-hadoop3.1-1.1.2-bin/lib/hive-exec-3.1.2.jar
/opt/apps/ecm/service/hive/3.1.2-hadoop3.1-1.1.2/package/apache-hive-3.1.2-hadoop3.1-1.1.2-bin/conf/hive-exec-log4j2.properties.template
/opt/apps/ecm/service/impala/3.4.0-1.0.4/package/impala-3.4.0-1.0.4/lib/hive-exec-2.1.1-cdh6.x-SNAPSHOT.jar
/opt/apps/ecm/service/storm/1.2.2-1.0.1/package/apache-storm-1.2.2-1.0.1/external/storm-autocreds/hive-exec-0.14.0.jar
/opt/apps/ecm/service/oozie/5.1.0-hadoop3.1-1.0.0/package/oozie-5.1.0-hadoop3.1-1.0.0/share/lib/hive/hive-exec-2.3.1.jar
/opt/apps/ecm/service/oozie/5.1.0-hadoop3.1-1.0.0/package/oozie-5.1.0-hadoop3.1-1.0.0/share/lib/git/hive-exec-2.3.1-core.jar
/opt/apps/ecm/service/oozie/5.1.0-hadoop3.1-1.0.0/package/oozie-5.1.0-hadoop3.1-1.0.0/lib/hive-exec-2.3.1-core.jar
/opt/apps/ecm/service/oozie/5.1.0-hadoop3.1-1.0.0/package/oozie-5.1.0-hadoop3.1-1.0.0/embedded-oozie-server/webapp/WEB-INF/lib/hive-exec-2.3.1-core.jar
/opt/apps/ecm/service/pig/0.14.0/package/pig-0.14.0/lib/hive-exec-0.14.0-core.jar
/opt/apps/ecm/service/spark/2.4.7-hadoop3.2-1.1.1/package/spark-2.4.7-hadoop3.2-1.1.1/jars/hive-exec-2.3.5-core.jar
/opt/webank/linkis/lib/linkis-public-enhancements/linkis-ps-metadatamanager/service/hive/hive-exec-2.3.3.jar
/opt/webank/linkis/lib/linkis-engineconn-plugins/hive/dist/v2.1.1/lib/hive-exec-2.1.1.jar
/var/lib/ecm-agent/cache/ecm/service/HIVE/3.1.2.301.7/package/files/conf/hive-exec-log4j.properties

请问应该怎么解决该jar包冲突？

### Eureka service list

![image](https://user-images.githubusercontent.com/52166229/186870692-032bb6fe-a44e-40e3-b240-7e6f9baeea53.png)

### Some logs info or acctch file

linkis-cli.log:
2022-08-26 15:49:13.049 ERROR Job with execId-LINKISCLI_root_hive_0 + subJobId : 123  execute failed,21304, Task is Failed,errorMsg: errCode: 12003 ,desc: emr-header-3.cluster-254539:9101_24 Failed  to async get EngineNode AMErrorException: errCode: 30002 ,desc: ServiceInstance(linkis-cg-engineconn, emr-header-3.cluster-254539:35433) ticketID:47887b78-a106-4988-b8a3-e401ca3cf4a8 初始化引擎失败,原因: ServiceInstance(linkis-cg-engineconn, emr-header-3.cluster-254539:35433): log dir: /appcom/tmp/root/20220826/hive/47887b78-a106-4988-b8a3-e401ca3cf4a8/logs,NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V ,ip: emr-header-3.cluster-254539 ,port: 9101 ,serviceKind: linkis-cg-linkismanager ,ip: emr-header-3.cluster-254539 ,port: 9104 ,serviceKind: linkis-cg-entrance

2022-08-26 15:49:13.049 INFO job is completed.
2022-08-26 15:49:13.049 INFO Task creation time(任务创建时间): 2022-08-26 15:49:03, Task scheduling time(任务调度时间): 2022-08-26 15:49:03, Task start time(任务开始时间): 2022-08-26 15:49:03, Mission end time(任务结束时间): 2022-08-26 15:49:13
2022-08-26 15:49:13.049 INFO Your mission(您的任务) 123 The total time spent is(总耗时时间为): 10.6 秒
2022-08-26 15:49:13.049 INFO Sorry. Your job completed with a status Failed. You can view logs for the reason.

````
log file:
 <!-- 拖拽上传后，会自动生成如下示例格式的附件url -->
[linkis-cli_log.log](https://github.com/apache/incubator-linkis/files/9431877/linkis-cli_log.log)
[stdout.txt](https://github.com/apache/incubator-linkis/files/9431878/stdout.txt)

**Comment by ruY9527** [comment]
hi, 我看你 /hive/dist/v2.1.1/lib/hive-exec-2.1.1.jar 和 hive-3.1.2 版本有出入， 参考下 https://github.com/apache/incubator-linkis/issues/3118 是否能帮助你？

**Comment by 2018yinjian** [comment]
可以了 谢谢
