### ISSUE TITLE
执行pyspark没反应，无法提交任务

### ISSUE THREAD

**Issue by 2018yinjian** [apache/incubator-linkis#3080]
Duplicate of #
Duplicate of #

**Comment by ruY9527** [comment]
Hello, is it convenient to look at the stderr log file of the engine?
--
你好,方便看下engine的stderr日志文件吗?
是否有TimeoutException 或者 其他错误提示？

**Comment by 2018yinjian** [comment]
> ## Hello, is it convenient to look at the stderr log file of the engine?
> 你好,方便看下engine的stderr日志文件吗? 是否有TimeoutException 或者 其他错误提示？
[stdout.txt](https://github.com/apache/incubator-linkis/files/9474391/stdout.txt)
[linkis-cg-linkismanager.log](https://github.com/apache/incubator-linkis/files/9474392/linkis-cg-linkismanager.log)
[linkis-cg-linkismanager.log](https://github.com/apache/incubator-linkis/files/9474393/linkis-cg-linkismanager.log)
[linkis-cg-engineconnmanager.log](https://github.com/apache/incubator-linkis/files/9474394/linkis-cg-engineconnmanager.log)

[linkis-cg-entrance.log](https://github.com/apache/incubator-linkis/files/9474395/linkis-cg-entrance.log)


[linkis-ps-cs.log](https://github.com/apache/incubator-linkis/files/9474396/linkis-ps-cs.log)
