### ISSUE TITLE
Add junit5 test code for module [linkis-instance-label-server]

### ISSUE THREAD

**Issue by ruY9527** [apache/incubator-linkis#3099]
Add junit5 test code for module [linkis-instance-label-server]
- Module: linkis-instance-label-server
- Location:linkis-public-enhancements/linkis-instance-label-server
- Task status:✗(unfinished)/ ✓(finished)
- Test code guide:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- Test code example: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test

--- 
- 模块名: linkis-instance-label-server
- 代码位置:linkis-public-enhancements/linkis-instance-label-server
- 任务状态:✗(unfinished)/ ✓(finished)
- 单测编写指引:https://linkis.apache.org/zh-CN/community/how-to-write-unit-test-code/
- 参考样例: https://github.com/apache/incubator-linkis/tree/master/linkis-public-enhancements/linkis-publicservice/linkis-jobhistory/src/test

| Task status| Class | Type| Level of Difficulty | Note |
| :------ | :------ | :------: | :------: | :------: |
|   ✗         |org.apache.linkis.instance.label.async.GenericAsyncConsumerQueue| Queue | normal |  |
|   ✗         |org.apache.linkis.instance.label.cache.InsLabelCacheConfiguration| Queue | normal |  |
|   ✗         |org.apache.linkis.instance.label.conf.InsLabelConf| conf | normal |  |
|   ✗         |org.apache.linkis.instance.label.dao.*| dao | normal |  |
|   ✗         |org.apache.linkis.instance.label.exception.InstanceErrorException| exception | normal |  |
|   ✗         |org.apache.linkis.instance.label.restful.InstanceRestful| api | normal |  |
|   ✗         |org.apache.linkis.instance.label.service.*| service | normal |  |
|   ✗         |org.apache.linkis.instance.label.utils.EntityParser| parser | normal |  |
|   ✗         |org.apache.linkis.instance.label.service.conf.InstanceConfigration| conf | normal |  |

**Comment by binbinCheng** [comment]
I do

**Comment by ruY9527** [comment]
done
