### ISSUE TITLE
[Question] Initializing SparkContext Fail ,when excution spark-sql

### ISSUE THREAD

**Issue by denghaibin92** [apache/incubator-linkis#3117]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.1
- Environment name and version:

    - hadoop-3.2.4
    - hive-3.1.2
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121

### Describe your questions

Q1.  
step1: ./linkis-cli -submitUser  hadoop  -engineType spark-3.2.1 -codeType sql  -code "show tables"
step2: task fail,  Error initializing SparkContext. java.lang.IllegalStateException: null

### Some logs info or acctch file

ERROR org.apache.spark.internal.Logging 94 logError - Error initializing SparkContext. java.lang.IllegalStateException: null
	at org.apache.hadoop.thirdparty.com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[hadoop-client-runtime-3.3.1.jar:1.1.1]

**Comment by denghaibin92** [comment]
log

**Comment by denghaibin92** [comment]
[spark-log.zip](https://github.com/apache/incubator-linkis/files/9439195/spark-log.zip)
<img width="711" alt="企业微信截图_20220828133732" src="https://user-images.githubusercontent.com/86011086/187060620-c1c1ed2b-7b24-4d39-95d9-be945cda7c20.png">

**Comment by ruY9527** [comment]
hi, 我看你的 https://github.com/apache/incubator-linkis/issues/3118 中已经处理了，是hive-exec版本的原因，是否检查下 spark的jars下相关的hive包,是否导致 guava 冲突?

**Comment by denghaibin92** [comment]
重新用guava 27版本编译linkis，问题还是存在

**Comment by yyh2954360585** [comment]
Hello, have you finished this question
