### ISSUE TITLE
问题帮助-linkis-cg-engineplugin启动失败

### ISSUE THREAD

**Issue by cipay0325** [apache/incubator-linkis#3148]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.3
- Environment name and version:
    - cdh-6.30 
    - hive-2.1.1
    - spark-2.4.0
    - scala-2.12.13
    - jdk 1.8.0_181
 

### Describe your questions

Q1.  问题帮助-linkis-cg-engineplugin启动失败

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)
![ee9c677931d887152c4bf39aeffec0e](https://user-images.githubusercontent.com/37971707/187581661-a103358f-808e-4e24-8c7c-24c873c091aa.jpg)
![e48a91eae2d7f0801d1e47edd8e247f](https://user-images.githubusercontent.com/37971707/187581688-24b62b13-bc50-4dd5-9495-299d3f69d31c.jpg)
![a87479689ad3f212e03c9f54fb32644](https://user-images.githubusercontent.com/37971707/187581604-022b88f3-756e-4579-86bc-80295609525c.jpg)
![03d7deadf33ae7aa3d939e991ba90e9](https://user-images.githubusercontent.com/37971707/187581767-5046f595-d177-4db2-adad-c04e84438278.jpg)
![image](https://user-images.githubusercontent.com/37971707/187582117-6593ba46-a4e1-45d1-83b0-5b106d23988f.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里--> 
[linkis-cg-engineplugin.log](https://github.com/apache/incubator-linkis/files/9457923/linkis-cg-engineplugin.log)

**Comment by jacktao007** [comment]
![image](https://user-images.githubusercontent.com/1073365/188401047-00124af6-dc9d-4b8b-9a18-b5909bf7cda9.png)
The path is faulty.

please modify engineconn.home  path
