### ISSUE TITLE
[Question] 修改appconn的路径后显示errCode: 10900

### ISSUE THREAD

**Issue by cipay0325** [apache/incubator-linkis#3152]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.3
- Environment name and version:
    - cdh-6.3.0 
    - hive-2.1.1
    - spark-2.4.0
    - scala-2.12.13
    - jdk 1.8.0_181

### Describe your questions

Q1.  ...
errCode: 10900 ,desc: The user is not logged in, please log in first, you can set a retry, message: {"method":"/api/rest_j/v1/bml/upload","status":-1,"message":"Token Authentication Failed, token: BML-AUTH，tokenUser: root, reason: errCode: 15201 ,desc: Token is not valid or stale! ,ip: hadoop-test-10-10-6-100 ,port: 9177 ,serviceKind: linkis-mg-gateway","data":{}} ,ip: hadoop-test-10-10-6-100 ,port: 9103 ,serviceKind: linkis-cg-engineplugin

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)
![image](https://user-images.githubusercontent.com/37971707/187605315-5ff176f2-8dc3-4354-993f-12261a68cb52.png)
![image](https://user-images.githubusercontent.com/37971707/187605387-699057db-d78a-4d2a-a247-c9723b5855f4.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/incubator-linkis/files/9219529/yarn-error.log)
[linkis-cg-engineplugin(1).log](https://github.com/apache/incubator-linkis/files/9458968/linkis-cg-engineplugin.1.log)

**Comment by peacewong** [comment]
Confirm whether there is corresponding data in the linkis_mg_gateway_auth_token table
