### ISSUE TITLE
[Question] Hive Internal Error: java.lang.ClassNotFoundException(org.apache.atlas.hive.hook.HiveHook

### ISSUE THREAD

**Issue by Yiutto** [apache/incubator-linkis#3159]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.3
- Environment name and version:
    - cdh-5.12.1

    - hive-1.1.0_cdh5.12.1
    - spark-2.3.0.cloudera4

    - jdk 1.8.0_121
    - ....

### Describe your questions

Q1.  FAILED: Hive Internal Error: java.lang.ClassNotFoundException(org.apache.atlas.hive.hook.HiveHook)
![image](https://user-images.githubusercontent.com/12077317/187627471-0ce0be9a-bfc6-4b1d-8334-f27a145bdd1a.png)

**Comment by peacewong** [comment]
You need to copy the atlas related jar package to hive ec lib, eg.
```
sudo ln -s  /opt/aux_path/* /home/linkis/LinkisInstall/lib/linkis-engineconn-plugins/hive/dist/v1.1.0_cdh5.12.1/lib 
```
