### ISSUE TITLE
[Question]  Guide on using dockerized hadoop cluster of local hadoop cluster. 

### ISSUE THREAD

**Issue by behradiy** [apache/incubator-linkis#3247]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.3
- Environment name and version:
    - CentOS 7
    - Hadoop: [big data Europe docker hadoop](https://github.com/big-data-europe/docker-hadoop) - Version: 3.1.1

### Describe your questions

First of all, I need to say Linkis is fascinating. 

I needed to deploy Hadoop with docker due to a lack of resources.
After deploying the Hadoop, I followed the [Quick Deployment doc](https://linkis.apache.org/docs/latest/deployment/quick-deploy) you guys provided. In the very first lines of this document, A Hadoop user is required. 
I'm wondering if it's possible to somehow use the containers instead of this Hadoop user. If it is possible, I would appreciate it if you guys can help me with how to do it. 

### Some logs info or acctch file

here is how dockerized Hadoop is managed :

- Namenode: http://<dockerhadoop_IP_address>:9870/dfshealth.html#tab-overview
- History server: http://<dockerhadoop_IP_address>:8188/applicationhistory
- Datanode: http://<dockerhadoop_IP_address>:9864/
- Nodemanager: http://<dockerhadoop_IP_address>:8042/node
- Resource manager: http://<dockerhadoop_IP_address>:8088/

**Comment by jacktao007** [comment]
By default, Linkis uses the Hadoop user. You can use other users and modify them in the configuration file:linkis-dist/deploy-config/linkis-env.sh->deployUser=hadoop

**Comment by behradiy** [comment]
fair enough, but
does this Hadoop user need access to the Hadoop cluster I'm running on docker?

> By default, Linkis uses the Hadoop user. You can use other users and modify them in the configuration file:linkis-dist/deploy-config/linkis-env.sh->deployUser=hadoop

**Comment by hunter-cloud09** [comment]
In the absence of integrated ldap, this hadoop user is only used as the installation user of linkis, and has nothing to do with your Hadoop cluster.

**Comment by behradiy** [comment]
> In the absence of integrated ldap, this hadoop user is only used as the installation user of linkis, and has nothing to do with your Hadoop cluster.

Thanks a Lot!
