### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by dark9281** [apache/incubator-linkis#3258]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.1
- Environment name and version:（单机环境）
    - hdp-2.7.2
    - hive-2.3.3
    - spark-2.4.8
    - scala-2.11.12
    - jdk 1.8.0_251

### Describe your questions

Q1.  在Scriptis板块执行sql失败，建表也报错，报错如下：

2022-09-06 14:59:49.059 ERROR Job with execId-IDE_hadoop_spark_4 + subJobId : 6  execute failed,21304, Task is Failed,errorMsg: errCode: 12003 ,desc: banan:9101_5 Failed  to async get EngineNode AMErrorException: errCode: 30001 ,desc: Failed to create engineResource ,ip: banan ,port: 9101 ,serviceKind: linkis-cg-linkismanager ,ip: banan ,port: 9104 ,serviceKind: linkis-cg-entrance 

### Eureka service list

![image](https://user-images.githubusercontent.com/112930389/188571996-94d0f120-a146-445e-af26-cd929e4a6bd8.png)

### Some logs info or acctch file

log file:
dss linkis日志如下：
 
[dss_logs.zip](https://github.com/apache/incubator-linkis/files/9494280/dss_logs.zip)
[linkis_logs.zip](https://github.com/apache/incubator-linkis/files/9494281/linkis_logs.zip)

**Comment by utopianet** [comment]
linkis-cg-engineplugin.log
desc='No plugin found spark-2.4.8, please check your configuration'
请查阅官方插件安装文档进行安装。
https://linkis.apache.org/zh-CN/docs/1.1.1/deployment/engine-conn-plugin-installation

**Comment by dark9281** [comment]
报错现象还是一样：
![image](https://user-images.githubusercontent.com/112930389/188621699-f539a566-9fb0-4074-96f5-c6527986e60a.png)
日志如下：
[linkis_logs.zip](https://github.com/apache/incubator-linkis/files/9496171/linkis_logs.zip)

**Comment by casionone** [comment]
> 报错现象还是一样： ![image](https://user-images.githubusercontent.com/112930389/188621699-f539a566-9fb0-4074-96f5-c6527986e60a.png) 日志如下： [linkis_logs.zip](https://github.com/apache/incubator-linkis/files/9496171/linkis_logs.zip)
It is best to paste the key log text when uploading the screenshot.

Whether the linkis-cg-engineplugin service starts normally, you need to pay attention to its exception linkis-cg-engineplugin.log
