### ISSUE TITLE
Support Hadoop 3.X

### ISSUE THREAD

**Issue by Adamyuanyuan** [apache/incubator-linkis#329]
**Is your feature request related to a problem? Please describe.**
More and more companies are using Hadoop 3, we need to support Hadoop 3;

**Describe the solution you'd like**
1. Support Spark 3.X to better adapt Hadoop 3.X;
2. Support scala 2.12 to better adapt Spark 3.X;
3. Refactoring some conflicting dependencies, such as HttpClient, Dispatch and so on;
4. Other components that are better suited to the version of Hadoop 3.X,such as Hive 3.X and so on;
5. Provide tools to hadoop 3.X / spark 3.X / hive2.x or hive 3.x user to change version;
**Describe alternatives you've considered**
no
**Additional context**

您的功能请求是否与问题有关？请描述一下。
越来越多的公司在使用hadoop3，我们需要支持hadoop3；
描述您想要的解决方案
 1. 支持Spark 3.X以更好地适应Hadoop 3.X；
 2. 支持scala 2.12以更好地适应Spark 3.X；
 3. 重构一些相互冲突的依赖关系，如HttpClient、Dispatch等；
 4. 其他更适合hadoop3.X版本的组件，比如hive3.X等等；
 5. 为hadoop3.X/spark3.X/hive2.X或hive3.X用户提供更改版本的工具；
 描述你考虑过的备选方案
 附加上下文

**Comment by lordk911** [comment]
wish it

**Comment by peacewong** [comment]
Linkis 1.0 already supports hadoop3, just modify the corresponding version to compile
