### ISSUE TITLE
元数据库无法连接

### ISSUE THREAD

**Issue by cipay0325** [apache/incubator-linkis#3325]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.1
- Environment name and version:
    - cdh-6.3.0
    - hive-2.1.1
    - spark-2.4.0
    - scala-2.11.12
    - jdk 1.8.0_202
    - ....

### Describe your questions

Q1.  ...
无法获取到元数据库信息/无法连接元数据库

### Eureka service list

![image](https://user-images.githubusercontent.com/37971707/189822693-3ef10e6c-f43f-4843-8d0e-55718821aaf4.png)

![image](https://user-images.githubusercontent.com/37971707/189822585-4c228fea-bbc4-4fe5-8daf-6d3427b7030c.png)
dss-scriptis-server.log：
![image](https://user-images.githubusercontent.com/37971707/189822785-3ebdf6b3-df11-47ec-8517-cde9afa56489.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->
linkis-ps-publicservice.log：
2022-09-13 14:18:45.281 [ERROR] [Druid-ConnectionPool-Create-1389724841  ] c.a.d.p.DruidDataSource (2781) [run] - create connection SQLException, url: "jdbc:mysql://10.100.131.6:3306/hive?userUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC", errorCode 0, state null java.sql.SQLException: connect error, url "jdbc:mysql://10.100.131.6:3306/hive?userUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC", driverClass com.mysql.jdbc.Driver
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1714) ~[druid-1.1.22.jar:1.1.22]
        at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2779) ~[druid-1.1.22.jar:1.1.22]
````
log file:
dss_log:dss日志信息
[dss-workflow-server.log](https://github.com/apache/incubator-linkis/files/9553998/dss-workflow-server.log)
[dss-apiservice-server.log](https://github.com/apache/incubator-linkis/files/9554006/dss-apiservice-server.log)
[dss-flow-execution-server.log](https://github.com/apache/incubator-linkis/files/9554007/dss-flow-execution-server.log)
[dss-framework-orchestrator-server.log](https://github.com/apache/incubator-linkis/files/9554008/dss-framework-orchestrator-server.log)
[dss-framework-project-server.log](https://github.com/apache/incubator-linkis/files/9554009/dss-framework-project-server.log)
[dss-guide-server.log](https://github.com/apache/incubator-linkis/files/9554010/dss-guide-server.log)
[dss-scriptis-server.log](https://github.com/apache/incubator-linkis/files/9554011/dss-scriptis-server.log)

linkis_logs：linkis日志信息

[linkis-cg-engineconnmanager.log](https://github.com/apache/incubator-linkis/files/9554040/linkis-cg-engineconnmanager.log)
[linkis-cg-engineplugin(5).log](https://github.com/apache/incubator-linkis/files/9554041/linkis-cg-engineplugin.5.log)
[linkis-cg-entrance.log](https://github.com/apache/incubator-linkis/files/9554042/linkis-cg-entrance.log)
[linkis-cg-linkismanager(1).log](https://github.com/apache/incubator-linkis/files/9554043/linkis-cg-linkismanager.1.log)
[linkis-mg-eureka.log](https://github.com/apache/incubator-linkis/files/9554044/linkis-mg-eureka.log)
[linkis-mg-gateway.log](https://github.com/apache/incubator-linkis/files/9554045/linkis-mg-gateway.log)
[linkis-ps-cs.log](https://github.com/apache/incubator-linkis/files/9554046/linkis-ps-cs.log)
[linkis-ps-data-source-manager.log](https://github.com/apache/incubator-linkis/files/9554047/linkis-ps-data-source-manager.log)
[linkis-ps-metadatamanager.log](https://github.com/apache/incubator-linkis/files/9554048/linkis-ps-metadatamanager.log)
[linkis-ps-publicservice(1).log](https://github.com/apache/incubator-linkis/files/9554049/linkis-ps-publicservice.1.log)

**Comment by casionone** [comment]
Please confirm whether there is a mysql driver jar package  
https://linkis.apache.org/zh-CN/docs/1.3.0/deployment/quick-deploy#32-%E6%B7%BB%E5%8A%A0mysql%E9%A9%B1%E5%8A%A8%E5%8C%85

**Comment by cipay0325** [comment]
文档指向的两个位置都已经有驱动包，而且换了很多版本的驱动包都试过了，依旧无法连接到hive的元数据库













在 2022-09-14 00:20:53，"Casion" ***@***.***> 写道：

Please confirm whether there is a mysql driver jar package
https://linkis.apache.org/zh-CN/docs/1.3.0/deployment/quick-deploy#32-%E6%B7%BB%E5%8A%A0mysql%E9%A9%B1%E5%8A%A8%E5%8C%85

**Comment by cipay0325** [comment]
在 2022-09-14 00:20:53，"Casion" ***@***.***> 写道：

Please confirm whether there is a mysql driver jar package
https://linkis.apache.org/zh-CN/docs/1.3.0/deployment/quick-deploy#32-%E6%B7%BB%E5%8A%A0mysql%E9%A9%B1%E5%8A%A8%E5%8C%85
