### ISSUE TITLE
[Bug] jdbc can not copy lib jars on workspace

### ISSUE THREAD

**Issue by liaotian1005** [apache/incubator-linkis#3354]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-engineconnn-plugin

### Steps to reproduce

![image](https://user-images.githubusercontent.com/36446084/190034284-46c49bca-e0ec-4f36-85bd-51fbfe6a977c.png)
 jdbc can not copy lib jars on workspace
2022-09-14 08:48:49.048 ERROR Job with execId-IDE_hdpu_jdbc_2 + subJobId : 117  execute failed,21304, Task is Failed,errorMsg: errCode: 12003 ,desc: pnode3:9101_31 Failed  to async get EngineNode AMErrorException: errCode: 30002 ,desc: ServiceInstance(linkis-cg-engineconn, pnode3:19057) ticketID:8be5e15d-daa6-4891-8319-50e6fdd99032 初始化引擎失败,原因: Failed to start EngineConn, reason: ECMErrorException: errCode: 11102 ,desc: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
错误: 找不到或无法加载主类 org.apache.linkis.engineconn.launch.EngineConnServer
 ,ip: pnode3 ,port: 9102 ,serviceKind: linkis-cg-engineconnmanager
 You can go to this path(/home/hdpu/apps/linkis/appcom/hdpu/20220914/jdbc/8be5e15d-daa6-4891-8319-50e6fdd99032/logs) to find the reason or ask the administrator for help ,ip: pnode3 ,port: 9101 ,serviceKind: linkis-cg-linkismanager ,ip: pnode3 ,port: 9104 ,serviceKind: linkis-cg-entrance
![image](https://user-images.githubusercontent.com/36446084/190034401-2bf80dd4-423f-46c4-8d86-a6d17294d812.png)

### Expected behavior

use jdbc 

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
This should be caused by the fact that the user who started the engine does not have permission to the lib directory of the engine, and the main class cannot be found because the corresponding module is not loaded.
这个应该是启动引擎的用户对引擎的lib目录没有权限导致，没有加载对应的模块导致找不到主类。建议不适用/home目录安装
