### ISSUE TITLE
JDBC link submitted by SDK using linkis invalid

### ISSUE THREAD

**Issue by jhszy6** [apache/incubator-linkis#339]
Map<String, Object> params = new HashMap<>();
		params.put("jdbc.url", "jdbc:mysql://xxxxx:3306/test");
		params.put("jdbc.username", "root");
		params.put("jdbc.password", "pass$123");

SDK方式提交了jdbc.url，后面如果修改，无法通过客户端修改JDBCurl，连的还是原来的库.
The jdbc.url is submitted in SDK mode. If it is modified later, the JDBC URL cannot be modified through the client, and the original library is still connected.

**Comment by jhszy6** [comment]
jdbc链接是通过jdbcurl的ip进行唯一KEY识别的，当链接mysql时，如果jdbcurl中库修改了，linkis会默认根据前面的ip链接上一个库，不会更换数据库

**Comment by peacewong** [comment]
Thanks
