### ISSUE TITLE
linkis-gateway有共享session问题(linkis-gateway has a shared session problem)

### ISSUE THREAD

**Issue by brianzhangrong** [apache/incubator-linkis#343]
**Is your feature request related to a problem? Please describe.**
gateway部署多个节点导致enginemanager创建engine失败，失败原因是enginemanager recevieAndReply 方法内request.user为空， 抛异常了

**Describe the solution you'd like**
把user_id放在cookie或者引入redis，mysql

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/39478871/79289816-efe76880-7efc-11ea-807a-0085cd0449a3.png)

**Comment by peacewong** [comment]
Yes, now Gateway does not do session sharing, if you are interested, you can do it together
