### ISSUE TITLE
[Bug] basedata ui api call error

### ISSUE THREAD

**Issue by jackxu2011** [apache/incubator-linkis#3436]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-web

### Steps to reproduce

NoApplicationExistsException: errCode: 10050 ,desc: Application basedata_manager is not exists any instances. ,ip: ldp01.c1.linkcld.com ,port: 9001 ,serviceKind: linkis-mg-gateway

### Expected behavior

get the data from db

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Anything else

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jackxu2011** [comment]
finished

**Comment by SpiderPalace** [comment]
请问，怎么解决的

**Comment by SpiderPalace** [comment]
how to deal？

**Comment by jackxu2011** [comment]
The bug has been resolved by #3437
