### ISSUE TITLE
[Feature][datasource-manager-server] New interface for Qualitis

### ISSUE THREAD

**Issue by chenmutime** [apache/incubator-linkis#3439]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

Qualitis侧为保证数据的安全性，将权限控制细分到了数据维度，其中就涉及到对数据源管理模块的改动。
由于Qualitis侧本身并不保存数据源信息，但又要确保本次功能升级不会对Linkis侧代码造成过度侵入。因而在Qualitis侧建立了一张映射表，保存Linkis侧的数据源ID，以及本次功能涉及到的新增字段。
Qualitis侧在执行查询时，会首先查询映射表，获得数据源ID集合，然后拿这个ID集合去请求Llinkis，拿到数据源信息列表。

### Description

Linkis侧新增一个查询数据源列表的接口，其入参为数据源ID列表，且为必填选择。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by figodeng** [comment]
通过linkis添加的数据源，在qualitis找不到。不确定这个现象是否正常
linkis数据源：api/rest_j/v1/data-source-manager/info
qualitis查找linkis数据源：api/rest_j/v1/datasource/dbs

不确定是不是目前qualitis接入hive的database无法包含linkis的数据源，有两个疑问

1. 在linkis创建数据源的时候，是否会再hive中创建db
2. 是否会通过create external table的方式在hive穿件对应的table，否则通过接口api/rest_j/v1/datasource/tables?database=default如何查到对应的表
