### ISSUE TITLE
[Question] Hive can't find data sources were created by linkis

### ISSUE THREAD

**Issue by figodeng** [apache/incubator-linkis#3447]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - hdp-3.2.4
    - hive-3.1.2
    - spark-3.1.3
    - jdk 1.8.0_342
    - ....

### Describe your questions

- add data source in linkis
![image](https://user-images.githubusercontent.com/7880649/190850440-98eed90d-b854-4021-9e22-c1f0823c0872.png)

- response from api '{ApiGateway}/api/rest_j/v1/datasource/dbs'
![image](https://user-images.githubusercontent.com/7880649/190850813-f695da36-7f2e-4d02-921f-98ba8c0a9f02.png)

we can't get the  data sources were created by linkis

### Eureka service list

![image](https://user-images.githubusercontent.com/7880649/190850357-33b97d43-1503-49b7-935b-34b8810452b3.png)

### Some logs info or acctch file

no error logs

**Comment by casionone** [comment]
如果需要使用数据源中配置的数据源，请使用元数据查询接口 详细可参考https://linkis.apache.org/zh-CN/docs/latest/api/http/linkis-ps-publicservice-api/metadataquery-api#gettables 

{ApiGateway}/api/rest_j/v1/datasource/dbs   接口是之前的老接口， 查询的连接信息来自与  https://linkis.apache.org/zh-CN/docs/latest/deployment/quick-deploy#22-%E9%85%8D%E7%BD%AE%E6%95%B0%E6%8D%AE%E5%BA%93%E4%BF%A1%E6%81%AF

-----


If you need to use the data source configured in the data source, please refer to the metadata query interface for details https://linkis.apache.org/zh-CN/docs/latest/api/http/linkis-ps-publicservice-api/metadataquery-api#gettables  
{ApiGateway}/api/rest_ The j/v1/datasource/dbs interface is the old interface before. The connection information queried comes from https://linkis.apache.org/zh-CN/docs/latest/deployment/quick-deploy#22 -%E9%85%8D%E7%BD%AE%E6%95%B0%E6%8D%AE%E5%BA%93%E4%BF%A1%E6%81%AF
