### ISSUE TITLE
[Question] rest提交任务文档太少

### ISSUE THREAD

**Issue by liaotian1005** [apache/incubator-linkis#3460]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Describe your questions

Q1.  ...
能否在rest提交任务文档中补充各种引擎的详细参数提交文档，现在的文档让我什么都看不出来，瞎子摸灯

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/incubator-linkis/files/9219529/yarn-error.log)
能否在rest提交任务文档中补充各种引擎的详细参数提交文档，现在的文档让我什么都看不出来，瞎子摸灯

**Comment by liaotian1005** [comment]
比如说租户如何设置，jdbc,spark以及其他参数放在那些位置，文档中一个都没提及

**Comment by casionone** [comment]
> 比如说租户如何设置，jdbc,spark以及其他参数放在那些位置，文档中一个都没提及

抱歉，您提到这部分文档确实不够清晰，我们已计划对这部分文档进行补充，但这需要时间。 如果你比较着急的话，可以加我微信 进行沟通。
--- 
Sorry, you mentioned that this part of the document is not clear enough. We have planned to supplement this part of the document, but it will take time. If you are in a hurry, you can add WeChat:casionxia to communicate with me.
