### ISSUE TITLE
workflow&&linkis查看节点日志对比结果(must click workflow again to return to the edit page)

### ISSUE THREAD

**Issue by zhanghaicheng1** [apache/incubator-linkis#350]
![image](https://user-images.githubusercontent.com/46189785/79838274-511fa800-83e5-11ea-8bca-2be75d0b2faf.png)
1、问题描述：工作流HQL节执行过后不管成功与否，点击历史->查看按钮，就是回不了编辑界面，必须要到linkis里面将相关日志文件关闭，才能进入工作流节点的编辑界面；
2、问题分析思路：无
3、问题解决方案：无

**Comment by Alexkun** [comment]
沙箱环境测试，点查看按钮后，点击工作流编辑tab就回去了，不需要关闭日志文件才能编辑工作流节点。你用的版本是哪个

**Comment by zhanghaicheng1** [comment]
linkis里面点击查看日志不是直接打开一个***.history的文件吗？直接关闭就回到编辑页面了。workflow还得再点击一次工作流才能回到编辑页面
