### ISSUE TITLE
Login module to add verification code function

### ISSUE THREAD

**Issue by Adamyuanyuan** [apache/incubator-linkis#351]
**Is your feature request related to a problem? Please describe.**
The company's security requirements, the login page needs to add verification code function, otherwise the website exposed public network, easy to be broken by hackers

**Describe the solution you'd like**
The verification code function is designed as optional, the platform can choose whether to add verification code

**Comment by det101** [comment]
公司有这样的安全需求，也能给开发者提供一个可选验证方案

**Comment by det101** [comment]
后续将开发这个功能，登陆的时候增加验证码过滤器，如果没有验证码会提示输入验证码，前端登陆页面会根据后端的返回显示验证码内容，提示用户输入；本功能支持配置，默认为关闭，不影响现有流程，开发者自行选择是否开启。

**Comment by Adamyuanyuan** [comment]
> 后续将开发这个功能，登陆的时候增加验证码过滤器，如果没有验证码会提示输入验证码，前端登陆页面会根据后端的返回显示验证码内容，提示用户输入；本功能支持配置，默认为关闭，不影响现有流程，开发者自行选择是否开启。

麻烦龙哥开发了~
