### ISSUE TITLE
[Bug] hive 查询问题

### ISSUE THREAD

**Issue by chenliangwei3004** [apache/incubator-linkis#3516]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-web

### Steps to reproduce

ERROR Job with execId-IDE_root_hive_6 + subJobId : 38  execute failed,21304, Task is Failed,errorMsg: ask Engine failed + errCode: 12003 ,desc: hadoop-alone:9101_573 Failed  to async get EngineNode LinkisRetryException: errCode: 30002 ,desc:  The em of labels{userCreator=root-IDE, codeType=hql, engineType=hive-2.3.3} not found ,ip: hadoop-alone ,port: 9101 ,serviceKind: linkis-cg-linkismanager ,ip: hadoop-alone ,port: 9104 ,serviceKind: linkis-cg-entrance 

### Expected behavior

ERROR Job with execId-IDE_root_hive_6 + subJobId : 38  execute failed,21304, Task is Failed,errorMsg: ask Engine failed + errCode: 12003 ,desc: hadoop-alone:9101_573 Failed  to async get EngineNode LinkisRetryException: errCode: 30002 ,desc:  The em of labels{userCreator=root-IDE, codeType=hql, engineType=hive-2.3.3} not found ,ip: hadoop-alone ,port: 9101 ,serviceKind: linkis-cg-linkismanager ,ip: hadoop-alone ,port: 9104 ,serviceKind: linkis-cg-entrance 

### Your environment

ERROR Job with execId-IDE_root_hive_6 + subJobId : 38  execute failed,21304, Task is Failed,errorMsg: ask Engine failed + errCode: 12003 ,desc: hadoop-alone:9101_573 Failed  to async get EngineNode LinkisRetryException: errCode: 30002 ,desc:  The em of labels{userCreator=root-IDE, codeType=hql, engineType=hive-2.3.3} not found ,ip: hadoop-alone ,port: 9101 ,serviceKind: linkis-cg-linkismanager ,ip: hadoop-alone ,port: 9104 ,serviceKind: linkis-cg-entrance 

### Anything else

ERROR Job with execId-IDE_root_hive_6 + subJobId : 38  execute failed,21304, Task is Failed,errorMsg: ask Engine failed + errCode: 12003 ,desc: hadoop-alone:9101_573 Failed  to async get EngineNode LinkisRetryException: errCode: 30002 ,desc:  The em of labels{userCreator=root-IDE, codeType=hql, engineType=hive-2.3.3} not found ,ip: hadoop-alone ,port: 9101 ,serviceKind: linkis-cg-linkismanager ,ip: hadoop-alone ,port: 9104 ,serviceKind: linkis-cg-entrance 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
It seems that there is a problem with the start of the linkis-cg-engineconnmanager service. Just restart the service.
