### ISSUE TITLE
[Bug] JDBC EC connection cache key logic suggested optimization

### ISSUE THREAD

**Issue by kongslove** [apache/incubator-linkis#3521]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-engineconnn-plugin

### Steps to reproduce

创建相同类型的jdbc链接，使用不同用户提交任务时会默认用第一个账号创建的链接

![7883718ab4f146f3d5e884f70de92da](https://user-images.githubusercontent.com/42604208/191908631-a842ee77-cf78-4dca-a24e-e041f1f41396.png)

### Expected behavior

缓存的datasource的key粒度降低 ,使用url+username作为key

### Your environment

- Linkis version used: 1.1.1
- Environment name and version:
    - cdh-6.3.2
    - hive-2.1.1
    - spark-2.4.8
    - scala-2.11.8
    - jdk 1.8.0_121
    - ....

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
I agree with your point of view very much. Are you willing to submit PR for optimization?
