### ISSUE TITLE
[Question]  linkis1.1.3 编译 mvn clean install -DskipTests 出错 linkis-engineconn-plugins/engineconn-plugins/flink/src/main/java/org/apache/linkis/engineconnplugin/flink/client/result/BatchResult.java:30: error: cannot find symbol 

### ISSUE THREAD

**Issue by dhymade** [apache/incubator-linkis#3548]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.3
- Environment name and version:
    - hdp-3.2.4
    - hive-3.1.3
    - spark-3.0.3
    - scala-2.12.10
    - jdk 1.8.0_201
    - flink 1.12.7

### Describe your questions

Q1.  linkis1.1.3 编译 mvn clean install -DskipTests 出错是什么原因？ 怎么解决
linkis-engineconn-plugins/engineconn-plugins/flink/src/main/java/org/apache/linkis/engineconnplugin/flink/client/result/BatchResult.java:30: error: cannot find symbol
具体报错如下：

[INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ linkis-engineconn-plugin-flink ---
[WARNING] Zinc server is not available at port 3030 - reverting to normal incremental compile
[INFO] Using incremental compilation
[INFO] Compiling 28 Scala sources and 57 Java sources to /usr/local/software/DSS_src/incubator-linkis-release-1.1.3/linkis-engineconn-plugins/engineconn-plugins/flink/target/classes...
[WARNING] /usr/local/software/DSS_src/incubator-linkis-release-1.1.3/linkis-engineconn-plugins/engineconn-plugins/flink/src/main/scala/org/apache/linkis/engineconnplugin/flink/executor/FlinkCodeOnceExecutor.scala:117: non-variable type argument org.apache.hadoop.yarn.api.records.ApplicationId in type pattern org.apache.flink.client.deployment.ClusterClientJobClientAdapter[org.apache.hadoop.yarn.api.records.ApplicationId] is unchecked since it is eliminated by erasure
[WARNING]         case adaptor: ClusterClientJobClientAdapter[ApplicationId] =>
[WARNING]                       ^
[WARNING] /usr/local/software/DSS_src/incubator-linkis-release-1.1.3/linkis-engineconn-plugins/engineconn-plugins/flink/src/main/scala/org/apache/linkis/engineconnplugin/flink/executor/FlinkCodeOnceExecutor.scala:145: non-variable type argument org.apache.hadoop.yarn.api.records.ApplicationId in type pattern org.apache.flink.client.program.ClusterClientProvider[org.apache.hadoop.yarn.api.records.ApplicationId] is unchecked since it is eliminated by erasure
[WARNING]       case provider: ClusterClientProvider[ApplicationId] => provider.getClusterClient
[WARNING]                      ^
[WARNING] /usr/local/software/DSS_src/incubator-linkis-release-1.1.3/linkis-engineconn-plugins/engineconn-plugins/flink/src/main/scala/org/apache/linkis/engineconnplugin/flink/executor/FlinkOnceExecutor.scala:40: abstract type pattern T is unchecked since it is eliminated by erasure
[WARNING]       case adapter: T => clusterDescriptor = adapter
[WARNING]                     ^
[WARNING] there were three deprecation warnings
[WARNING] there were 7 deprecation warnings (since 2.12.0)
[WARNING] there were 10 deprecation warnings in total; re-run with -deprecation for details
[WARNING] 6 warnings found
[ERROR] /usr/local/software/DSS_src/incubator-linkis-release-1.1.3/linkis-engineconn-plugins/engineconn-plugins/flink/src/main/java/org/apache/linkis/engineconnplugin/flink/client/result/BatchResult.java:30: error: cannot find symbol
[ERROR] import org.apache.flink.table.client.gateway.local.CollectBatchTableSink;
[ERROR]                                                   ^
[ERROR]   symbol:   class CollectBatchTableSink
[ERROR]   location: package org.apache.flink.table.client.gateway.local
[ERROR] /usr/local/software/DSS_src/incubator-linkis-release-1.1.3/linkis-engineconn-plugins/engineconn-plugins/flink/src/main/java/org/apache/linkis/engineconnplugin/flink/client/result/BatchResult.java:50: error: cannot find symbol
[ERROR]     private final CollectBatchTableSink tableSink;
[ERROR]                   ^
[ERROR]   symbol:   class CollectBatchTableSink
[ERROR]   location: class BatchResult<C>
[ERROR]   where C is a type-variable:
[ERROR]     C extends Object declared in class BatchResult
[ERROR] /usr/local/software/DSS_src/incubator-linkis-release-1.1.3/linkis-engineconn-plugins/engineconn-plugins/flink/src/main/java/org/apache/linkis/engineconnplugin/flink/client/result/ChangelogResult.java:34: error: cannot find symbol
[ERROR] import org.apache.flink.table.client.gateway.local.CollectStreamTableSink;
[ERROR]                                                   ^
[ERROR]   symbol:   class CollectStreamTableSink
[ERROR]   location: package org.apache.flink.table.client.gateway.local
[ERROR] /usr/local/software/DSS_src/incubator-linkis-release-1.1.3/linkis-engineconn-plugins/engineconn-plugins/flink/src/main/java/org/apache/linkis/engineconnplugin/flink/client/result/ChangelogResult.java:55: error: cannot find symbol
[ERROR]     private final CollectStreamTableSink collectTableSink;
[ERROR]                   ^
[ERROR]   symbol:   class CollectStreamTableSink
[ERROR]   location: class ChangelogResult
[ERROR] 4 errors
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Linkis Project Parent POM 1.1.3:
[INFO] 
[INFO] Linkis Project Parent POM .......................... SUCCESS [  2.927 s]
[INFO] linkis-common ...................................... SUCCESS [ 35.261 s]
[INFO] linkis-hadoop-common ............................... SUCCESS [  8.351 s]
[INFO] linkis-httpclient .................................. SUCCESS [  7.863 s]
[INFO] linkis-protocol .................................... SUCCESS [  9.461 s]
[INFO] linkis-scheduler ................................... SUCCESS [ 13.191 s]
[INFO] linkis-module ...................................... SUCCESS [ 13.767 s]
[INFO] linkis-mybatis ..................................... SUCCESS [  4.759 s]
[INFO] linkis-rpc ......................................... SUCCESS [ 18.822 s]
[INFO] linkis-storage ..................................... SUCCESS [ 14.813 s]
[INFO] linkis-commons ..................................... SUCCESS [  0.062 s]
[INFO] linkis-eureka ...................................... SUCCESS [  6.745 s]
[INFO] linkis-label-common ................................ SUCCESS [  9.024 s]
[INFO] linkis-service-gateway ............................. SUCCESS [  0.065 s]
[INFO] linkis-gateway-authentication ...................... SUCCESS [  8.812 s]
[INFO] linkis-gateway-core ................................ SUCCESS [  9.224 s]
[INFO] linkis-gateway-httpclient-support .................. SUCCESS [  9.437 s]
[INFO] linkis-spring-cloud-gateway ........................ SUCCESS [ 11.011 s]
[INFO] linkis-cs-common ................................... SUCCESS [  2.833 s]
[INFO] linkis-instance-label-server ....................... SUCCESS [  8.067 s]
[INFO] linkis-gateway-server-support ...................... SUCCESS [ 17.500 s]
[INFO] linkis-spring-cloud-services ....................... SUCCESS [  0.044 s]
[INFO] linkis-computation-governance-common ............... SUCCESS [ 17.558 s]
[INFO] linkis-manager-common .............................. SUCCESS [ 17.297 s]
[INFO] linkis-orchestrator ................................ SUCCESS [  0.055 s]
[INFO] linkis-orchestrator-core ........................... SUCCESS [ 23.308 s]
[INFO] linkis-code-orchestrator ........................... SUCCESS [  6.977 s]
[INFO] linkis-orchestrator-ecm-plugin ..................... SUCCESS [ 12.332 s]
[INFO] linkis-computation-orchestrator .................... SUCCESS [ 17.151 s]
[INFO] linkis-bml-common .................................. SUCCESS [  8.110 s]
[INFO] linkis-bmlserver ................................... SUCCESS [ 11.180 s]
[INFO] linkis-bml-client .................................. SUCCESS [ 15.448 s]
[INFO] linkis-udf-common .................................. SUCCESS [  8.736 s]
[INFO] linkis-udf-client .................................. SUCCESS [  7.065 s]
[INFO] linkis-engineconn-common ........................... SUCCESS [  7.679 s]
[INFO] linkis-executor-core ............................... SUCCESS [  8.856 s]
[INFO] linkis-engineconn-plugin-core ...................... SUCCESS [ 13.409 s]
[INFO] linkis-engineconn-core ............................. SUCCESS [ 12.093 s]
[INFO] linkis-accessible-executor ......................... SUCCESS [ 17.114 s]
[INFO] linkis-resource-executor ........................... SUCCESS [  0.168 s]
[INFO] linkis-callback-service ............................ SUCCESS [  8.160 s]
[INFO] linkis-cs-listener ................................. SUCCESS [  2.409 s]
[INFO] linkis-cs-client ................................... SUCCESS [ 17.442 s]
[INFO] linkis-computation-engineconn ...................... SUCCESS [ 29.145 s]
[INFO] linkis-bml-engine-hook ............................. SUCCESS [ 10.583 s]
[INFO] linkis-bml ......................................... SUCCESS [  0.185 s]
[INFO] linkis-cs-persistence .............................. SUCCESS [ 20.594 s]
[INFO] linkis-cs-cache .................................... SUCCESS [  2.776 s]
[INFO] linkis-instance-label-client ....................... SUCCESS [  7.837 s]
[INFO] linkis-cs-highavailable ............................ SUCCESS [ 18.878 s]
[INFO] linkis-cs-search ................................... SUCCESS [  6.253 s]
[INFO] linkis-cs-server ................................... SUCCESS [ 15.190 s]
[INFO] linkis-context-service ............................. SUCCESS [  0.138 s]
[INFO] linkis-metadata .................................... SUCCESS [ 22.538 s]
[INFO] linkis-datasource-manager-common ................... SUCCESS [01:22 min]
[INFO] linkis-metadata-manager-common ..................... SUCCESS [ 15.649 s]
[INFO] linkis-datasource-manager-server ................... SUCCESS [02:35 min]
[INFO] linkis-metadata-manager-service-es ................. SUCCESS [ 14.706 s]
[INFO] linkis-metadata-manager-service-hive ............... SUCCESS [ 23.986 s]
[INFO] linkis-metadata-manager-service-kafka .............. SUCCESS [  8.954 s]
[INFO] linkis-metadata-manager-service-mysql .............. SUCCESS [  4.850 s]
[INFO] linkis-metadata-manager-server ..................... SUCCESS [ 23.500 s]
[INFO] linkis-datasource-client ........................... SUCCESS [ 34.983 s]
[INFO] linkis-datasource .................................. SUCCESS [  0.048 s]
[INFO] linkis-ps-common-lock .............................. SUCCESS [  9.874 s]
[INFO] linkis-udf-service ................................. SUCCESS [ 20.323 s]
[INFO] linkis-jobhistory .................................. SUCCESS [ 28.236 s]
[INFO] linkis-configuration ............................... SUCCESS [ 29.053 s]
[INFO] linkis-variable .................................... SUCCESS [ 18.165 s]
[INFO] linkis-storage-script-dev-client ................... SUCCESS [ 11.341 s]
[INFO] linkis-io_file-client .............................. SUCCESS [ 21.849 s]
[INFO] linkis-storage-script-dev-server ................... SUCCESS [ 22.440 s]
[INFO] linkis-error-code-common ........................... SUCCESS [  8.012 s]
[INFO] linkis-error-code-client ........................... SUCCESS [ 18.598 s]
[INFO] linkis-error-code-server ........................... SUCCESS [  3.167 s]
[INFO] linkis-error-code .................................. SUCCESS [  0.076 s]
[INFO] linkis-publicservice ............................... SUCCESS [  0.256 s]
[INFO] linkis-public-enhancements ......................... SUCCESS [  0.710 s]
[INFO] linkis-once-engineconn ............................. SUCCESS [ 22.218 s]
[INFO] linkis-engineconn .................................. SUCCESS [  0.080 s]
[INFO] linkis-engineconn-manager-core ..................... SUCCESS [ 36.607 s]
[INFO] linkis-engineconn-linux-launch ..................... SUCCESS [ 11.989 s]
[INFO] linkis-engineconn-manager-server ................... SUCCESS [ 41.958 s]
[INFO] linkis-engineconn-manager .......................... SUCCESS [  0.064 s]
[INFO] linkis-manager-persistence ......................... SUCCESS [ 12.543 s]
[INFO] linkis-label-manager ............................... SUCCESS [ 30.924 s]
[INFO] linkis-manager-service-common ...................... SUCCESS [  8.315 s]
[INFO] linkis-resource-manager ............................ SUCCESS [ 28.722 s]
[INFO] linkis-application-manager ......................... SUCCESS [ 40.369 s]
[INFO] linkis-manager ..................................... SUCCESS [  0.087 s]
[INFO] linkis-entrance .................................... SUCCESS [ 51.998 s]
[INFO] linkis-computation-client .......................... SUCCESS [ 50.340 s]
[INFO] linkis-cli ......................................... SUCCESS [  0.126 s]
[INFO] linkis-cli-common .................................. SUCCESS [  4.256 s]
[INFO] linkis-cli-core .................................... SUCCESS [  2.128 s]
[INFO] linkis-cli-application ............................. SUCCESS [  3.389 s]
[INFO] linkis-computation-governance ...................... SUCCESS [  0.057 s]
[INFO] linkis-engineconn-plugin-cache ..................... SUCCESS [  4.317 s]
[INFO] linkis-engineconn-plugin-loader .................... SUCCESS [ 14.060 s]
[INFO] linkis-engineconn-plugin-server .................... SUCCESS [ 34.096 s]
[INFO] linkis-engineplugin-hive ........................... SUCCESS [ 53.937 s]
[INFO] linkis-engineplugin-spark .......................... SUCCESS [01:47 min]
[INFO] linkis-engineplugin-python ......................... SUCCESS [ 32.536 s]
[INFO] linkis-engineplugin-openlookeng .................... SUCCESS [ 27.033 s]
[INFO] linkis-engineplugin-io_file ........................ SUCCESS [ 25.835 s]
[INFO] linkis-engineplugin-shell .......................... SUCCESS [ 28.556 s]
[INFO] linkis-engineplugin-pipeline ....................... SUCCESS [ 28.592 s]
[INFO] linkis-engineplugin-jdbc ........................... SUCCESS [01:20 min]
[INFO] linkis-engineconn-plugins .......................... SUCCESS [  1.152 s]
[INFO] linkis-engineconn-plugin-flink ..................... FAILURE [01:35 min]
[INFO] linkis-engineplugin-sqoop .......................... SKIPPED
[INFO] linkis-extensions .................................. SKIPPED
[INFO] public-module-combined ............................. SKIPPED
[INFO] linkis-package ..................................... SKIPPED
[INFO] linkis-install-package ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33:37 min
[INFO] Finished at: 2022-09-27T19:08:49-07:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "custom-compiler" could not be activated because it does not exist.
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project linkis-engineconn-plugin-flink: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed.: CompileFailed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :linkis-engineconn-plugin-flink
[root@localhost incubator-linkis-release-1.1.3]# java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
[root@localhost incubator-linkis-release-1.1.3]# 

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/incubator-linkis/files/9219529/yarn-error.log)

**Comment by peacewong** [comment]
This seems to be caused by the upgrade of the flink version. It is recommended to use flink 1.12.2 for compilation.
