### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by YiminPan** [apache/incubator-linkis#3566]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.2.0
- Environment name and version:
    - hive-2.3.3
    - spark-2.4.3
    - scala-2.11.12
    - jdk 1.8.0_291
    

### Describe your questions

Q1.  安装linkis 1.2.0成功以后，配置Qualitis 0.9.2， 想接入linkis 1.2.0 ，但是根据接入文档说明，如下截图
![image](https://user-images.githubusercontent.com/5094639/193179098-e02617a6-6212-4bcd-ac5b-5d27ed76a3f2.png)
在$LINKIS_HOME目录下找不到子目录linkis-gateway以及文件 token.properties。
请问在哪里能找到linkis-gateway和 token.properties？

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/incubator-linkis/files/9219529/yarn-error.log)
[linkis-mg-gateway.log](https://github.com/apache/incubator-linkis/files/9680272/linkis-mg-gateway.log)

**Comment by peacewong** [comment]
Please refer to：https://linkis.apache.org/zh-CN/docs/1.1.0/upgrade/upgrade-guide/#41-token-%E9%85%8D%E7%BD%AE
