### ISSUE TITLE
[Bug] adjust metadata query service

### ISSUE THREAD

**Issue by aiceflower** [apache/incubator-linkis#3571]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons, linkis-public-enhancements

### Steps to reproduce

![image](https://user-images.githubusercontent.com/22620332/193211316-7a720e44-9023-420a-84bd-65afcbbe9bc8.png)

### Expected behavior

update wds.linkis.server.mdm.service.lib.dir

### Your environment

linkis-13.0

### Anything else

None

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by aiceflower** [comment]
Why can't we just use distribution.xml here?
![image](https://user-images.githubusercontent.com/22620332/194701939-d333c9ef-c39c-4d9a-8f3a-1becbf73a176.png)

This should be the current directory or the parent directory?
![image](https://user-images.githubusercontent.com/22620332/194702290-f330c052-3043-46e7-8f73-79280469f851.png)

**Comment by jackxu2011** [comment]
> Why can't we just use distribution.xml here? ![image](https://user-images.githubusercontent.com/22620332/194701939-d333c9ef-c39c-4d9a-8f3a-1becbf73a176.png)
> 
> This should be the current directory or the parent directory? ![image](https://user-images.githubusercontent.com/22620332/194702290-f330c052-3043-46e7-8f73-79280469f851.png)

1. the distribution.xml's location is ${basedir}/src/main/assembly/distribution.xml,  the ${basedir} can ignore

2. the linkis-datasource in the same level with distributin.xml

**Comment by aiceflower** [comment]
We can add distribution.xml to the outermost layer, we don't have to add so many directories

**Comment by jackxu2011** [comment]
usually the location src/main/assembly/ is a conventional path for distribution.xml
