### ISSUE TITLE
[Bug] 日志权限问题

### ISSUE THREAD

**Issue by Yiutto** [apache/incubator-linkis#3606]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-engineconnn-plugin

### Steps to reproduce

![图片](https://user-images.githubusercontent.com/12077317/194795749-61dc2754-18f7-4a8c-baca-499b5c9e8427.png)

隔天执行，非hadoop安装用户执行linkis会报权限问题，不可能每次执行生成新的日志文件夹就去赋予777权限。本身看每次生成的文件夹都是hadoop用户生成的，组用户也是没有写权限的

### Expected behavior

希望其他非hadoop用户执行不会报权限问题，最起码生成的日志文件夹 组用户要有写权限

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Need to give write permission to the corresponding directory
