### ISSUE TITLE
[Feature] Consistently invoke bash with /usr/bin/env bash in scripts to make code more portable

### ISSUE THREAD

**Issue by huangxiaopingRD** [apache/incubator-linkis#3607]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jackxu2011** [comment]
This change will have security problems?  if  someone put a executable called bash in PATH

**Comment by huangxiaopingRD** [comment]
> This change will have security problems?  if  someone put a executable called bash in PATH

Yes, there may be security issues. It's a tradeoff, a choice between portability (availability) and security
