### ISSUE TITLE
List of optimizations/issue  for docker 

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis#3663]
List of docker issues
- The mysql service initialization script may be executed multiple times, resulting in repeated data insertion, which needs to be optimized (primary key optimization + initial process optimization) #issue
- install-charts.sh can still start after the image fails to load # Loading Linkis image ... ERROR: image: "linkis:dev" not present locally
- Whether the ldh environment is mounted to the host directory, and ecm is shared. Related tasks depend on material packages such as spark-submit (can it be solved in a unified way in ec containerization?)
- UnknownhostException problem in ldh spark on yarn task, you need to specify the parameter spark.driver.host=linkis-demo-cg-engineconnmanager-headless.linkis.svc.cluster.local or modify the hosts configuration of the ldh container, which is temporarily passed Modify the host implementation of the ldh container `prepare-for-spark.sh`

- Whether the ldh username and password problem needs to be adjusted to configuration or random. Whether the test mode `Values.linkis.featureGates.testMode` is turned off
- `install-linkis-to-kubernetes.sh` script log optimization, adding some action log information

other 
- ldh support for other non-default engines
- Whether the image packaging considers all engine materials to be added, and whether there is a size limit, the tar material release considers the download speed and svn restrictions, and there are only four engine plug-ins by default
- Environment and configuration issues for additional dependencies (spark/hive home and conf)

----

容器化问题列表 
- mysql服务 初始化脚本 可能会被执行多次，导致重复插入了数据， 需要优化(主键优化+初始流程优化) #issue
- install-charts.sh  load 镜像失败后依旧可以启动 # Loading Linkis image ... ERROR: image: "linkis:dev" not present locally
- ldh 环境是否挂载到宿主机目录，ecm进行共享 相关任务依赖spark-submit等物料包（可以在ec容器化是统一处理解决?） 
- ldh spark on yarn任务unknownhostException 问题，需要在执行时指定参数 spark.driver.host=linkis-demo-cg-engineconnmanager-headless.linkis.svc.cluster.local或则修改ldh容器的hosts配置 ，目前临时通过 修改ldh容器的host实现 `prepare-for-spark.sh` 

- ldh 用户名密码问题 是否需要调整为配置或则随机 测试模式`Values.linkis.featureGates.testMode`是否关闭  
- `install-linkis-to-kubernetes.sh `脚本日志优化，补充部分动作日志信息

其他 
- ldh 其他非默认引擎的支持
- 镜像打包是否考虑所有引擎物料都加入，考虑是否有大小限制，tar的物料发布考虑下载速度和svn限制，默认只有四个引擎插件 
- 额外依赖的环境和配置问题(spark/hive home and  conf)

**Comment by jacktao007** [comment]
improved
