### ISSUE TITLE
[Question] linkis1.1.1 is support sqoop engin?

### ISSUE THREAD

**Issue by ichenfeiyang** [apache/incubator-linkis#3734]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.1
- dss 1.1.0
- exchangeis 1.0.0

### Describe your questions

Q1.  ...
我在安装使用exchangeis的时候（dss1.1.0+linkis1.1.1）   文档这里必须要安装sqoop引擎（且这个文档不存在）    我在linkis看安装sqoop引擎的文档又说linkis版本>=1.1.2才支持,这里感觉有点矛盾啊，我想核实一下，我们现在是dss1.1.0+linkis1.1.1，如果我要执行exchangeid的任务   那我是否需要安装sqoop引擎到Linkis1.1.1，该版本能否支持？

When installing and using Exchangeis (dss1.1.0+linkis1.1.1), the sqoop engine must be installed in the document (and this document does not exist). I saw the document for installing the sqoop engine in Linkis and said that the linkis version>=1.1.2 is supported. I feel a bit contradictory here. I want to verify that we are now dss1.1.0+linkis1.1.1. If I want to perform the task of exchangeid, do I need to install the sqoop engine to Linkis1.1.1, Can this version support?

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

when i excute exchangeis task; linis is error:
![image](https://user-images.githubusercontent.com/18556472/198463234-d176e1fd-32e5-4b32-8dd3-23b66bd8d594.png)

**Comment by casionone** [comment]
dss 1.1.0  can be supported  linkis >= 1.1.0 
if you wan to use exchangeis 
you can install with  dss 1.1.0 + linkis>=1.1.2 + exchangis 1.0.0
