### ISSUE TITLE
[Question] 通过DSS界面登陆Qualits需要输入用户名和口令，无法免密登陆，请问如何配置才能实现

### ISSUE THREAD

**Issue by 906460** [apache/incubator-linkis#3806]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.1
- DataSphere Studio:1.1.0
- Environment name and version:
    - cdh-5.14.2
    - hdp-2.7.2
    - hive-2.3.3
    - spark-2.4.3
    - scala-2.11.12
    - jdk 1.8.0_201

### Describe your questions

Q1.  可以分别正常登陆datasphere studio(dss)、qualitis。但是在dss界面集成qualitis之后，点击界面菜单上的’qualitis‘链接，则要求输入qualitis的用户名和密码，请见下图。在这个集成界面截图，再次手动输入qualitis的用户和口令也可以正常登陆。请问如何可以做到dss免密登陆qualitis。
  具体配置步骤参照了:
  1.《接入工作流指南》（https://github.com/WeBankFinTech/Qualitis/blob/master/docs/zh_CN/ch1/%E6%8E%A5%E5%85%A5%E5%B7%A5%E4%BD%9C%E6%B5%81%E6%8C%87%E5%8D%97.md）
  2. git上其他用户提的issue《dss访问qualitis和schedulis组件能够实现免密登录》(https://github.com/WeBankFinTech/DataSphereStudio/issues/954)

![image](https://user-images.githubusercontent.com/39142791/201029022-682a745e-92fe-4411-a07c-75bd60658d84.png)

### Eureka service list

![image](https://user-images.githubusercontent.com/39142791/201029290-72750892-29c3-483a-bb30-d6540bc8e804.png)

### Some logs info or acctch file

下面是在dss界面点击’qualits‘链接时的抓包截图：
![image](https://user-images.githubusercontent.com/39142791/201031925-ac858551-d276-4352-97a2-abb14286809a.png)

**Comment by peacewong** [comment]
please use english
