### ISSUE TITLE
Linkis0.12.0 community communication(Linkis0.12.0版本社区交流)

### ISSUE THREAD

**Issue by liangqilang** [apache/incubator-linkis#391]
### Linkis0.12.0 community communication
Linkis 0.12.0 is an important version led by Boss ZhiPing with the help of webank.
This version mainly provides the following features：

- Impala engine support
- Flink engine support
- Fix multiple bugs

**Comment by liangqilang** [comment]
Linkis 0.12.0 is an important version led by Boss ZhiPing.

This version mainly provides the following features：
Impala engine support
Flink engine support
Fix multiple bugs

**Comment by liangqilang** [comment]
Linkis0.12.0版本社区交流
Linkis0.12.0版本是由Boss直聘数星中台团队主导完成的一个重要版本。
该版本主要提供以下特性：
支持 Impala 引擎
支持 Flink 引擎
修复多个bug

**Comment by adonis2014** [comment]
什么时候完成呢？

**Comment by wushengyeyouya** [comment]
> 什么时候完成呢？

Currently planned for the end of July, actual completion depends on development progress.

**Comment by Sevncz** [comment]
这个版本现在有相关的时间安排没

**Comment by wushengyeyouya** [comment]
> 这个版本现在有相关的时间安排没

This version is planned to publish in next month.

**Comment by taoyonggang** [comment]
期待中，很有意义的项目。有k8s支持么？
