### ISSUE TITLE
[Bug][pyspark]There is a problem with the pyspark engine getting the spark version of CDH（pyspark 引擎获取 cdh 的 spark 版本有问题）

### ISSUE THREAD

**Issue by wForget** [apache/incubator-linkis#454]
**Describe the bug**
There is a problem with the pyspark engine getting the spark version of CDH（pyspark 引擎获取 cdh 的 spark 版本有问题）

**To Reproduce**
no

**Expected behavior**
no

**Additional context**
no

**Comment by SHAOLBJ** [comment]
带来后果和影响是什么啊？我这边在cdh的spark集群执行pyspark作业，报initialize python executor failed, please ask administrator for help! java.util.concurrent.TimeoutException: null

**Comment by liuzhimindluter** [comment]
我有相同的问题，在和平大佬的帮助下顺利定位到问题并修复；
我的环境是cdh 5.15， spark2.3.0 on yarn
linkis 0.9.3 on cdh ，pyspark无法顺利运行
日志观察：
/anaconda/bin/python  /tmp/737737377373737.py   42940  230cloudera3  /opt/cloudera/parcels/SPARK2-2.3.0.cloudera3-.1.cdh5.13.0.458009xxxxzip:/xx/xx/pysparkzip:/xx/xx/spark-core.2.11.2.3.0.cloudera3.jar

观察发现，生成的临时文件 /tmp/737737377373737.py   要求第二个参数是int型,但是实际传参是230cloudera3

sparkVersion =SparkVersion(int(sys.argv[2]))

解决办法：
修改/Linkis-cdh/ujes/definedEngines/spark/engine/src/main/resource/python/mix_pyspark.py
#sparkVersion = SparkVersion(int(sys.argv[2]))
sparkVersion = SparkVersion(int(230))

重新编译该模块

**Comment by liuzhimindluter** [comment]
> **Describe the bug**
> There is a problem with the pyspark engine getting the spark version of CDH（pyspark 引擎获取 cdh 的 spark 版本有问题）
> 
> **To Reproduce**
> no
> 
> **Expected behavior**
> no
> 
> **Additional context**
> no

我有相同的问题，在和平大佬的帮助下顺利定位到问题并修复；
我的环境是cdh 5.15， spark2.3.0 on yarn
linkis 0.9.3 on cdh ，pyspark无法顺利运行
日志观察：
/anaconda/bin/python /tmp/737737377373737.py 42940 230cloudera3 /opt/cloudera/parcels/SPARK2-2.3.0.cloudera3-.1.cdh5.13.0.458009xxxxzip:/xx/xx/pysparkzip:/xx/xx/spark-core.2.11.2.3.0.cloudera3.jar

观察发现，生成的临时文件 /tmp/737737377373737.py 要求第二个参数是int型,但是实际传参是230cloudera3

sparkVersion =SparkVersion(int(sys.argv[2]))

解决办法：
修改/Linkis-cdh/ujes/definedEngines/spark/engine/src/main/resource/python/mix_pyspark.py
#sparkVersion = SparkVersion(int(sys.argv[2]))
sparkVersion = SparkVersion(int(230))

重新编译该模块
