### ISSUE TITLE
环境变量设置无效(The environment variable setting is invalid)

### ISSUE THREAD

**Issue by fatsheng** [apache/incubator-linkis#456]
**Describe the bug**
通过filesystem/saveScript接口保存参数params: {variable: {}, configuration: {runtime: {datasource: "c3384a76-e21b-45b3-ab13-0209981f8513"}}}后无法通过filesystem/openFile取回参数

产生原因如下：
Linkis/storage/storage/src/main/scala/com/webank/wedatasphere/linkis/storage/script/VariableParser.getMap(VariableParser.scala:75)判断逻辑有误
```
if(vars.size() >0)params += CONFIGURATION -> confs
```

**To Reproduce**
通过filesystem/saveScript接口保存参数params: {variable: {}, configuration: {runtime: {datasource: "c3384a76-e21b-45b3-ab13-0209981f8513"}}}

**Expected behavior**
通过filesystem/openFile取回参数params: {variable: {}, configuration: {runtime: {datasource: "c3384a76-e21b-45b3-ab13-0209981f8513"}}}

**Screenshots**
无

**Desktop (please complete the following information):**
无

**Smartphone (please complete the following information):**
 无

**Additional context**
无

**Comment by peacewong** [comment]
Yes, this is a bug, you can submit a PR to the branch dev-0.11.0
