### ISSUE TITLE
[bug]jdbc entrance cached  a different jdbc engine

### ISSUE THREAD

**Issue by brianzhangrong** [apache/incubator-linkis#484]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/39478871/89001878-14414680-d32e-11ea-91fd-e4980deb2ba1.png)

**Comment by brianzhangrong** [comment]
use  JDBCEngineExecutor.get(url + ":" + userName + ":" + password) as function return

**Comment by wForget** [comment]
JDBCEngineExecutor may not require caching, please see 
issue: [Jdbc executor cache problem](https://github.com/WeBankFinTech/Linkis/issues/344)] 
fix : [remove JDBCEngineExecutor  cache](https://github.com/WeBankFinTech/Linkis/pull/462/commits/7182407c4838c49c679bd88b096d41572c69a3f3)
