### ISSUE TITLE
jackson-core version conflict in linkis-ujes-shell-enginemanager 

### ISSUE THREAD

**Issue by Zosimer** [apache/incubator-linkis#492]
There is a jackson-core-2.4.3.jar under linkis moudle/lib, and there is also a jackson-core-2.10.0.jar package under linkis-ujes-shell-enginemanager/lib. The two versions are inconsistent, resulting in com. fasterxml.jackson.core not found

在linkis moudle/lib下有一个jackson-core-2.4.3.jar，同时在linkis-ujes-shell-enginemanager/lib也有一个jackson-core-2.10.0.jar包，两个版本不一致，导致com.fasterxml.jackson.core找不到

**Comment by zosimer** [comment]
把linkis moudle/lib下所有的jar文件拷贝到linkis-ujes-shell-enginemanager/lib下，删除jackson-core-2.4.3.jar，重启服务，问题解决
