### ISSUE TITLE
When Visualis use Kylin Data to show pie chart, it cannot filter data and with colors. 

### ISSUE THREAD

**Issue by Vinsmoke66** [apache/incubator-linkis#493]
**Describe the bug**
When Visualis use Kylin Data to show pie chart, it cannot filter data and with colors. 
When 

Kylin Version:2.6.6
Linkis Version:0.9.4
DSS Version:0.9.0

**Expected behavior**
It can filter data and show with colors.

**Screenshots**
![image](https://user-images.githubusercontent.com/21305459/91381787-c64f2e00-e85a-11ea-93ef-da2cc29dedd5.png)
![image](https://user-images.githubusercontent.com/21305459/91381809-d6670d80-e85a-11ea-8a70-5ed365c8d3f8.png)
![image](https://user-images.githubusercontent.com/21305459/91381889-02828e80-e85b-11ea-889a-afb0f8f89aac.png)
![image](https://user-images.githubusercontent.com/21305459/91381907-11694100-e85b-11ea-90d9-5252c1788275.png)
`2020-08-27 11:45:30.174 ERROR [qtp416370147-4504] edp.davinci.service.impl.ViewServiceImpl 621 convertFilters - convertFilters error . filterStrs = [{"name":"ORDER_NUM","type":"filter","value":500,"operator":">"}], source = {name=kylin_taxi, description=xxx, id=32, type=jdbc, projectId=25}, filters = [{sqlType=null, children=null, name="ORDER_NUM", type=filter, value=500, operator=>}] , whereClauses = [] 
2020-08-27 11:45:30.176 ERROR [qtp416370147-4504] edp.davinci.core.config.RestExceptionHandler 63 serverExceptionHandler - null`

**Comment by wushengyeyouya** [comment]
Do you use Kylin dataSource in Visualis?

**Comment by Vinsmoke66** [comment]
> Do you use Kylin dataSource in Visualis?

Yes.
