### ISSUE TITLE
It takes 10 minutes to apply resource every time  in Linkis 0.9.4 version

### ISSUE THREAD

**Issue by suqingyang** [apache/incubator-linkis#494]
**Describe the bug**
It takes 10 minutes to apply resource every time  in Linkis 0.9.4 version
![image](https://user-images.githubusercontent.com/68212111/91824409-4c111600-ec6d-11ea-86f4-73f2af3061c5.png)
**To Reproduce**
1. when executing hive or jdbc
2. entrance log as below
![image](https://user-images.githubusercontent.com/68212111/91825170-78796200-ec6e-11ea-9127-52383b6ff84b.png)

3. hive-enginemanager log as below 
![image](https://user-images.githubusercontent.com/68212111/91826437-276a6d80-ec70-11ea-94fe-9933f83d869e.png)

**Comment by wushengyeyouya** [comment]
See 13 in https://github.com/WeBankFinTech/Linkis/wiki/%E9%83%A8%E7%BD%B2%E5%92%8C%E7%BC%96%E8%AF%91%E9%97%AE%E9%A2%98%E6%80%BB%E7%BB%93
