### ISSUE TITLE
is Linkis/contextservice/cs-server/bin/stop--cs-server.sh script file name misspelling

### ISSUE THREAD

**Issue by bertramlau** [apache/incubator-linkis#508]
**Describe the bug**
Excute the bin/stop-all.sh, found the error sh: /data/DSS/linkis/linkis-cs-server/bin/stop-cs-server.sh: No such file or directory 
**To Reproduce**
1. Excute the bin/stop-all.sh

**Expected behavior**
expect server  is stopped

**Screenshots**
![image](https://user-images.githubusercontent.com/2114596/98908146-f2458b80-24fa-11eb-9385-5258b0c3b51c.png)

**Desktop (please complete the following information):**
 - OS: centos 7

**Additional context**

**Comment by peacewong** [comment]
Does the /data/DSS/linkis/linkis-cs-server/ directory exist？

**Comment by bertramlau** [comment]
> Does the /data/DSS/linkis/linkis-cs-server/ directory exist？

the directory exist
