### ISSUE TITLE
kerberos principal Spelling mistake by principle

### ISSUE THREAD

**Issue by geosmart** [apache/incubator-linkis#527]
**Describe the bug**
mistake:  principle
right: principal 

![image](https://user-images.githubusercontent.com/3156608/101618205-9fed8100-3a4c-11eb-8a96-a8935e0c2dd1.png)

ref:[kerberos_principal](https://docs.oracle.com/cd/E21455_01/common/tutorials/kerberos_principal.html)

**Comment by peacewong** [comment]
Thank you for the spelling mistake you found, and you are welcome to fix it by PR
