### ISSUE TITLE
How to start linkis spring cloud gateway in idea

### ISSUE THREAD

**Issue by qdj0511** [apache/incubator-linkis#730]
version:1.0.0-RC1
版本：1.0.0-RC1

During the idea startup process, there will be
在IDEA启动过程中，会出出现
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/richardchien/software/maven/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.13.3/log4j-slf4j-impl-2.13.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/richardchien/software/maven/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: org.apache.logging.log4j.LoggingException: log4j-slf4j-impl cannot be present with log4j-to-slf4j
	at org.apache.logging.slf4j.Log4jLoggerFactory.validateContext(Log4jLoggerFactory.java:49)

The details are as follows:
具体如图：

![image](https://user-images.githubusercontent.com/8510947/118346165-1e0a0280-b56c-11eb-9734-101c246c7f07.png)

In POM. XML, after the package of exclusion, as shown in the figure below:
我在pom.xml中，exclusion这几个包以后，如下图
![image](https://user-images.githubusercontent.com/8510947/118346195-4560cf80-b56c-11eb-803b-de19645af3ae.png)

Restart the process, there will be a lack of org. Springframework. Cloud. Netflix. Hystrix. Reactive hystrix circuit breaker autoconfiguration
The details are as follows:
再启动过程，会出现缺少org.springframework.cloud.netflix.hystrix.ReactiveHystrixCircuitBreakerAutoConfiguration 
详细如下图：

![image](https://user-images.githubusercontent.com/8510947/118346151-016dca80-b56c-11eb-85d0-40925d2d0f40.png)
How to change this?
这个需要怎么改？

**Comment by peacewong** [comment]
Please use the linkis-gateway-server-support module
