### ISSUE TITLE
OPENSUSE Operating system

### ISSUE THREAD

**Issue by fengshao3** [apache/incubator-linkis#798]
hadoop@bogon:~/Linkis> bin/install.sh 
Operating system unknown, please tell us(submit issue) for better service
hadoop@bogon:~/Linkis> lsb-release -a
LSB Version:    n/a
Distributor ID: openSUSE
Description:    openSUSE Leap 15.3
Release:        15.3
Codename:       n/a

**Comment by fy403** [comment]
代码对于标准bash而言没有错，因为[Ubuntu](https://so.csdn.net/so/search?q=Ubuntu&spm=1001.2101.3001.7020)/Debian为了加快开机速度，用dash代替了传统的bash，是dash在捣鬼，解决方法就是取消dash。

解决：

1） sudo dpkg-reconfigure dash       在选择项中选No，搞定了！
