### ISSUE TITLE
Is there documentation for the local development environment?

### ISSUE THREAD

**Issue by lindychan** [apache/incubator-linkis#852]
For example, using IDEA...
How to start a project
Startup sequence
比如使用 idea ...
如何启动工程
启动顺序

**Comment by wForget** [comment]
> 比如使用 idea ...
> 如何启动工程
> 启动顺序

可以参考： [Linkis和DSS调试文档](https://github.com/WeBankFinTech/Linkis/wiki/Linkis%E5%92%8CDSS%E8%B0%83%E8%AF%95%E6%96%87%E6%A1%A3)
