### ISSUE TITLE
Remove webank copyright in License header 

### ISSUE THREAD

**Issue by Fuu3214** [apache/incubator-linkis#994]
Currently webank copyright is included in license header of all the Linkis source code. It is recommended to remove them in order to officially enter Apache incubation.

**Comment by fs3085** [comment]
Can you leave this question to me? As my first contribution in linkis

**Comment by Chiva-Zhao** [comment]
I can fix this easy issue, please assign me, thanks

**Comment by wuchunfu** [comment]
I'm willing to fix it.
