### ISSUE TITLE
Change linkis-datasource RESTFul API style

### ISSUE THREAD

**Issue by Fuu3214** [apache/incubator-linkis#998]
Source code included by the following packages define Linkis-datasource RESTFul APIs with JAX-RS annotations:

com.linkis.datasourcemanager.core.restful
com.linkis.metadata.restful
com.linkis.metadatamanager.server.restful

They need to be changed to Spring web style

**Comment by yimaixinchen** [comment]
convert jersey api to springmvc api?

**Comment by Narcasserun** [comment]
Can you leave this question to me? As my first contribution in linkis

**Comment by yimaixinchen** [comment]
> Can you leave this question to me? As my first contribution in linkis

well,if it can cancert to springmvc api.i want to become my first contribution in linkis.

**Comment by yimaixinchen** [comment]
https://github.com/WeBankFinTech/Linkis/pull/1000#issue-734344051
